"""English guides from the UK keyword review (research/keywords-uk.csv) and a live SERP review (Sept 2026).
how to create a qr code 12.1K, qr code how to get 9.9K, how to make a qr code 3.6K;
canva qr code generator 1.9K, adobe qr code generator 9.9K, adobe express qr code 880.
Shared pages (.com, .co.uk, .in). qr-code-in-canva.html also exists in German (content/de), so hreflang links them."""

_ART = {"static": True, "noindex": False, "type": "url"}

HOW_TO_MAKE = {**_ART,
    "slug": "how-to-make-a-qr-code.html",
    "crumb": "How to Make a QR Code",
    "title": "How to Make a QR Code (Free): Step-by-Step for Any Device",
    "description": "How to create a QR code in 4 steps: pick a type, add your link or details, style it, download and test. Plus free ways on iPhone, Android, Chrome and Canva.",
    "og_title": "How to Make a QR Code for Free | SmartQRCraft",
    "og_description": "Create a QR code in four steps, and every free way to make one on a phone or computer.",
    "h1": "How to Make a QR Code (Free, Step by Step)",
    "lead": "You can make a QR code in about a minute, free, without an account. Here are the four steps, the quickest method for each device, and the checks that stop a printed code from failing.",
    "faq_h2": "Questions About Making QR Codes",
    "sections": [
        {"kind": "prose", "id": "quick", "h2": "How to create a QR code in 4 steps",
         "p": ["The fastest way is a free online QR code generator, which works in any browser on a phone or computer:"],
         "steps": [
             "<strong>Choose what the code does.</strong> Open a <a href=\"index.html#generator\">QR code generator</a> and pick a type: a website link, WiFi, a contact card, a phone number, an email and more.",
             "<strong>Enter the content.</strong> Paste the link, or fill in the WiFi name and password or your contact details.",
             "<strong>Style it (optional).</strong> Change the color, add a frame such as &quot;Scan me&quot; or put your logo in the middle. Keep the code dark on a light background.",
             "<strong>Download and test.</strong> Save it as PNG for screens or SVG/PDF for print, then scan it with your phone before you share or print it.",
         ],
         "after": ["That is all a QR code is: a picture that stores text, such as a web address, which a phone camera can read. You do not need to register the code anywhere, and a code that stores its content directly (a <strong>static</strong> QR code) keeps working forever."]},
        {"kind": "prose", "id": "link", "h2": "How to make a QR code for a link or website",
         "steps": [
             "Open the page you want to share and copy the address from the browser's address bar.",
             "Paste it into the URL field of the generator. If you leave out <code>https://</code>, it is added for you.",
             "Download the code. When someone scans it, the page opens on their phone.",
         ],
         "after": ["Short links make simpler codes that print smaller. If the page might move, link to an address on your own domain, such as yourname.com/menu, and change where that address points instead of reprinting. The <a href=\"static-vs-dynamic-qr-codes.html\">static vs dynamic guide</a> explains the options."]},
        {"kind": "table", "h2": "Every free way to make a QR code",
         "p": ["Which method is best depends on what you need the code to do and where you will use it."],
         "cols": ["Method", "How", "Good for", "Limits"],
         "rows": [
             ["Online generator", "Choose a type, enter details, download", "Any content, custom design, print files", "Needs a browser"],
             ["Google Chrome", "Share menu or address bar &gt; <strong>QR code</strong> (desktop, Android and iPhone)", "The page you are looking at, right now", "Links only, no design, small image"],
             ["Microsoft Edge", "Right-click the page or use the address bar QR icon", "Sharing a page to your phone", "Links only"],
             ["iPhone Shortcuts", "Build a shortcut with the <strong>Generate QR Code</strong> action", "Quick codes for text or links", "Manual set-up, no styling"],
             ["Android WiFi settings", "Tap your network &gt; Share", "Letting a guest join your WiFi", "WiFi only, shown on screen"],
             ["Google Business Profile", "Ask for reviews &gt; copy or save the QR code", "Collecting Google reviews", "Desktop only, plain design"],
             ["Canva / Adobe Express", "Add a QR code inside your design", "Codes placed straight into flyers", "Mostly links; see <a href=\"qr-code-in-canva.html\">QR codes in Canva</a>"],
         ]},
        {"kind": "table", "h2": "Which type of QR code do you need?",
         "cols": ["You want people to...", "Use this type"],
         "rows": [
             ["open a website, menu or form", "<a href=\"index.html#generator\">URL / link</a>"],
             ["join your WiFi without typing a password", "<a href=\"wifi-qr-code-generator.html\">WiFi</a>"],
             ["save your contact details", "<a href=\"vcard-qr-code-generator.html\">vCard contact card</a>"],
             ["call or text you", "<a href=\"phone-qr-code-generator.html\">Phone</a> or <a href=\"sms-qr-code-generator.html\">SMS</a>"],
             ["email you with a subject filled in", "<a href=\"email-qr-code-generator.html\">Email</a>"],
             ["open a document", "<a href=\"pdf-to-qr-code.html\">PDF link</a>"],
             ["find your shop on a map", "<a href=\"location-qr-code-generator.html\">Location</a>"],
             ["make many codes at once", "<a href=\"bulk-qr-code-generator.html\">Bulk generator</a>"],
         ]},
        {"kind": "prose", "id": "business", "h2": "How to get a QR code for your business",
         "p": ["Most businesses start with three codes: a link to the menu, price list or website; a <a href=\"wifi-qr-code-generator.html\">WiFi code</a> for customers; and a link to leave a Google review. For reviews, copy your review link from Google Business Profile and turn it into a styled code with your logo.",
               "Print codes where people already wait or decide: tables, counters, windows, receipts and packaging. Add a short line that says what happens, such as &quot;Scan for today's menu&quot;. Ready-made layouts are in the <a href=\"printable-qr-code-templates.html\">printable templates</a>."]},
        {"kind": "prose", "id": "design", "h2": "Design tips that keep the code scannable",
         "bullets": [
             "<strong>Contrast first.</strong> A dark code on a white or light background scans best. Light-on-dark codes fail in some apps.",
             "<strong>Leave a border.</strong> Keep a blank margin (the quiet zone) around the code.",
             "<strong>Keep logos small.</strong> A centre logo works because of error correction, but only up to a point.",
             "<strong>Say what it does.</strong> A frame with a call to action gets more scans than a bare code.",
             "<strong>Match the size to the distance.</strong> About 2 cm (0.8 in) for cards; much larger for posters. See the <a href=\"qr-code-size-guide.html\">size guide</a>.",
         ]},
        {"kind": "prose", "id": "test", "h2": "Test the code before you print or share it",
         "p": ["Scan the finished code with two different phones, for example an iPhone and an Android. Check that it opens the right page on mobile data, not just on office WiFi. For printed codes, print one copy at the real size first. The <a href=\"qr-code-tester.html\">QR code tester</a> also checks whether a code still reads when it is small or blurry."]},
        {"kind": "prose", "id": "mistakes", "h2": "Common mistakes",
         "bullets": [
             "<strong>A typo in the link.</strong> Once printed, it cannot be fixed.",
             "<strong>Using a free trial's dynamic code.</strong> Some services switch codes off when a trial ends. Codes made here are static and never expire.",
             "<strong>Printing too small or on a curved or glossy surface.</strong>",
             "<strong>Linking to a page that is not mobile-friendly</strong>, since nearly every scan comes from a phone.",
             "<strong>No instructions.</strong> People need a reason to scan.",
         ]},
        {"kind": "cta", "h2": "Make your QR code now", "p": "Free, no signup, no watermark, and it never expires.", "href": "index.html#generator", "label": "Open the QR code generator"},
    ],
    "faq": [
        ("How do I create a QR code for free?",
         "Open a free QR code generator, choose the type (for example a link), enter your content and download the image. SmartQRCraft needs no signup and adds no watermark."),
        ("How do I get a QR code for a link?",
         "Copy the link, paste it into the URL field of a generator and download the code. Scanning it opens the link."),
        ("Can I make a QR code on my phone?",
         "Yes. Online generators work in a phone browser. In Chrome you can also use Share &gt; QR code for the page you are viewing, and iPhone users can build a QR code shortcut in the Shortcuts app."),
        ("Can I make a QR code without an app?",
         "Yes. A browser is enough: use an online generator or Chrome's built-in QR code option."),
        ("How long does a QR code last?",
         "A static QR code works forever, because the content is inside the code. Dynamic codes from subscription services can stop when the plan ends."),
        ("Can I change a QR code after printing it?",
         "Not a static one. You can change the destination of an address on your own website, or use a dynamic QR code service."),
        ("Do I need to register or pay for a QR code?",
         "No. QR codes are free to create and use. You only pay if you choose a service with extras such as scan tracking."),
    ],
    "related": [("what-is-a-qr-code.html", "What is a QR code?"), ("qr-code-examples.html", "QR code examples"), ("qr-code-safety.html", "QR code safety")],
}

CANVA_EN = {**_ART,
    "slug": "qr-code-in-canva.html",
    "crumb": "QR Codes in Canva",
    "title": "How to Make a QR Code in Canva (and Adobe Express)",
    "description": "Make a QR code in Canva: static and dynamic codes from Elements or Apps, what is free and what needs a paid plan, plus Adobe Express and adding WiFi or vCard codes.",
    "og_title": "How to Make a QR Code in Canva | SmartQRCraft",
    "og_description": "Canva's QR code generator step by step, what it can and cannot do, and Adobe Express.",
    "h1": "How to Make a QR Code in Canva",
    "lead": "Canva has a built-in QR code generator for links, with static and dynamic options. Here is how to use it, what needs a paid plan, how Adobe Express compares, and how to add WiFi, contact or payment codes that Canva cannot make.",
    "faq_h2": "Canva QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "quick", "h2": "Quick answer",
         "steps": [
             "Open your design in Canva.",
             "Go to <strong>Elements</strong> and search &quot;QR code&quot; (or open <strong>Apps</strong> and search for QR codes).",
             "Choose <strong>Create static</strong> for a fixed link, or <strong>Create dynamic</strong> for a link you can change later.",
             "Paste your link, adjust the colors and corners, and generate the code. It is added to your page.",
             "Export the design as PDF (print) or PNG, and scan the result before printing.",
         ],
         "after": ["Canva's menus change from time to time, so the labels you see may differ slightly."]},
        {"kind": "table", "h2": "Static or dynamic QR code in Canva?",
         "cols": ["", "Static", "Dynamic"],
         "rows": [
             ["Link can be changed later", "No", "Yes"],
             ["Scan statistics", "No", "On Canva Business and Enterprise plans"],
             ["Depends on Canva's service", "No: the link is in the code", "Yes: scans pass through Canva"],
             ["Best for", "Anything printed long-term", "Campaigns and menus that change"],
         ],
         "p": ["Canva lists extras such as scan tracking, expiry dates and replacing the Canva logo in the code as Business or Enterprise features. Check your plan before relying on them."]},
        {"kind": "prose", "id": "design", "h2": "Customizing the code in Canva",
         "p": ["You can change the code's colors and corner style. Keep the code dark and the background light, do not stretch it out of proportion, and do not place it over a busy photo. Transparency, shadows and effects on the code itself make it harder to scan."]},
        {"kind": "prose", "id": "other-types", "h2": "Adding WiFi, contact, payment or other codes to Canva",
         "p": ["Canva's generator makes codes for web links. For other types, create the code here and import it:"],
         "steps": [
             "Make the code: <a href=\"wifi-qr-code-generator.html\">WiFi</a>, <a href=\"vcard-qr-code-generator.html\">contact card</a>, <a href=\"phone-qr-code-generator.html\">phone</a>, <a href=\"email-qr-code-generator.html\">email</a> and more, with your colors and logo.",
             "Download it as <strong>SVG</strong>, which stays sharp at any size (PNG at 2048 px also works).",
             "In Canva, open <strong>Uploads</strong>, upload the file and drag it into your design.",
             "Resize it by the corner handles only, and keep a blank margin around it.",
         ]},
        {"kind": "prose", "id": "adobe", "h2": "How to make a QR code in Adobe Express",
         "p": ["Adobe Express has a free QR code generator too. Open it, paste a link, pick a style and colors, and download the code as PNG, JPG or PDF, or open it in the Adobe Express editor to add it to a design. Adobe states that its codes are for links only and do not expire, which is how static codes work."]},
        {"kind": "table", "h2": "Canva vs Adobe Express vs SmartQRCraft",
         "cols": ["", "Canva", "Adobe Express", "SmartQRCraft"],
         "rows": [
             ["Content types", "Links", "Links", "Links, WiFi, contact, phone, SMS, email, location, payments and more"],
             ["Colors and style", "Colors, corners", "Styles, colors, frames", "Colors, gradients, shapes, eyes, frames (heart, bag, bubble and more)"],
             ["Logo in the code", "Business and Enterprise plans", "Yes", "Yes, free"],
             ["Changeable link and scan stats", "Dynamic codes; stats on paid plans", "No", "No (static codes that never expire)"],
             ["Print files", "Export with your design", "PNG, JPG, PDF", "PNG, JPG, SVG, PDF, EPS"],
             ["Account needed", "Yes", "Yes, to use the editor", "No"],
         ],
         "p": ["Features change often; check each service before you rely on a specific option."]},
        {"kind": "prose", "id": "not-scanning", "h2": "Canva QR code not scanning? Check these",
         "bullets": [
             "<strong>Too small in the export.</strong> Print at least 2 cm (0.8 in) wide for handheld items.",
             "<strong>Low contrast</strong> between the code and the background, or a light code on a dark background.",
             "<strong>Something overlaps the code:</strong> text, a shape, a photo edge or a fold line.",
             "<strong>The code was cropped</strong> or stretched unevenly.",
             "<strong>Low-resolution export.</strong> Use PDF Print or a large PNG.",
             "Still stuck? Upload the exported image to the <a href=\"qr-code-tester.html\">QR code tester</a>.",
         ]},
    ],
    "faq": [
        ("Does Canva have a QR code generator?",
         "Yes. Search &quot;QR code&quot; in Elements or Apps to add a static or dynamic QR code for a link to your design."),
        ("Are Canva QR codes free?",
         "Static QR codes are free to create. Some extras, such as scan tracking and custom logos, are listed for Canva Business and Enterprise plans."),
        ("Do Canva QR codes expire?",
         "A static code does not expire because the link is stored in the code. A dynamic code relies on Canva's service to redirect scans."),
        ("Can I make a WiFi QR code in Canva?",
         "Not with Canva's generator. Make it with a <a href=\"wifi-qr-code-generator.html\">WiFi QR code generator</a>, download SVG and upload it to Canva."),
        ("How do I add a QR code with a logo in Canva?",
         "Create a code with your logo in a generator that supports logos, download it, and upload it to Canva. Canva's own logo option is listed for Business and Enterprise plans."),
        ("Is the Adobe Express QR code generator free?",
         "Yes. It makes link QR codes and lets you download them as PNG, JPG or PDF."),
    ],
    "related": [("how-to-make-a-qr-code.html", "How to make a QR code"), ("qr-code-with-logo.html", "QR code with logo"), ("qr-codes-in-print.html", "Printing QR codes")],
}

GUIDES_2 = [HOW_TO_MAKE, CANVA_EN]
