"""Guide articles: printing QR codes (flyers, t-shirts, packaging, cards, signs) and how to scan
QR codes on iPhone and Android. Keywords: qr codes in print 8.1K kd12, how to scan qr code on iphone 9.9K,
how to scan qr code on phone 3.6K (research/keywords.csv). Shared English pages."""

_ART = {"static": True, "noindex": False, "type": "url"}

PRINT = {**_ART,
    "slug": "qr-codes-in-print.html",
    "crumb": "Printing QR Codes",
    "title": "QR Codes in Print: Size, File Type and Tips for Every Material",
    "description": "How to print QR codes that scan: file formats, sizes, colors and placement for flyers, business cards, t-shirts, packaging, posters, stickers and signs.",
    "og_title": "QR Codes in Print: The Complete Guide | SmartQRCraft",
    "og_description": "File types, sizes, colors and placement for printing QR codes on any material.",
    "h1": "QR Codes in Print: How to Print a QR Code That Always Scans",
    "lead": "Most QR code problems start at the printer, not the generator. This guide covers the file to send, the size to choose and the details that matter on flyers, cards, clothing, packaging and signs.",
    "faq_h2": "Printing QR Code Questions",
    "sections": [
        {"kind": "table", "h2": "Which file to send to the printer",
         "cols": ["Format", "Use it for", "Why"],
         "rows": [
             ["SVG", "Designers, web-to-print, large formats", "Vector: sharp at any size, easy to edit in Illustrator, Inkscape, Canva and Figma"],
             ["PDF", "Print shops", "Vector, opens everywhere, keeps exact colors"],
             ["EPS", "Older print workflows, sign makers, embroidery shops", "Vector format many older tools still expect"],
             ["PNG at 2048 px or more", "Office printers, Word, PowerPoint", "Fine when the file is large enough for the print size"],
             ["JPG", "Only when nothing else is accepted", "Compression can blur the module edges"],
         ],
         "p": ["Our generator exports all five. For anything printed by a professional, choose SVG or PDF."]},
        {"kind": "prose", "id": "checklist", "h2": "The 8-point print checklist",
         "steps": [
             "<strong>Size:</strong> at least 2 cm (0.8 in) for items held in the hand. For distance, use about one tenth of the scanning distance. See the <a href=\"qr-code-size-guide.html\">size guide</a>.",
             "<strong>Quiet zone:</strong> keep a blank border of 4 modules around the code. Do not let text, borders or folds cut into it.",
             "<strong>Contrast:</strong> dark code on a light background. Light-on-dark and inverted codes fail on some scanners.",
             "<strong>Short content:</strong> shorter links make fewer, bigger modules that tolerate print errors.",
             "<strong>Error correction:</strong> use level Q or H for rough surfaces, fabric, or when you add a logo.",
             "<strong>No stretching:</strong> scale the code evenly; never squash it to fit a space.",
             "<strong>Proof at full size:</strong> print one copy at real size and scan it with an iPhone and an Android.",
             "<strong>Test the destination:</strong> make sure the link works on mobile data, not just office WiFi.",
         ]},
        {"kind": "table", "h2": "Material by material",
         "cols": ["Where", "Recommended size", "What to watch"],
         "rows": [
             ["Business cards", "2 to 2.5 cm (0.8 to 1 in)", "Matte stock; no foil on the code; keep the content short"],
             ["Flyers &amp; brochures", "3 to 4 cm (1.2 to 1.6 in)", "Not across a fold; say what the scan gives (&quot;Scan for 10% off&quot;)"],
             ["Posters", "10 to 20 cm (4 to 8 in)", "Scale to reading distance; place at eye level"],
             ["Product packaging", "2 to 3 cm", "Flat panel, not a curved edge or seam; allow for shrink-wrap glare"],
             ["Labels &amp; stickers", "2 cm or more", "Waterproof material outdoors; round stickers need extra margin"],
             ["T-shirts &amp; fabric", "8 to 12 cm (3 to 5 in)", "Screen print or DTF, not embroidery for small codes; flat area of the chest or back; stretch distorts codes, so test on the garment"],
             ["Window decals", "10 cm or more", "Print for the side people scan from; reflections reduce contrast"],
             ["Banners &amp; billboards", "One tenth of the viewing distance", "Only if people can safely stop; very short link"],
             ["Table tents &amp; menus", "3 to 5 cm", "Laminate against spills; one code per table is easier to manage"],
         ]},
        {"kind": "prose", "id": "tshirt", "h2": "Printing a QR code on a t-shirt",
         "p": ["Fabric stretches and folds, which bends the grid. Use a large code, square modules (not dots), high error correction and a plain light area of the shirt. Screen printing and DTF transfers keep edges crisp. Embroidery can work only for big codes with few modules, so test a sample before ordering in bulk."]},
        {"kind": "prose", "id": "packaging", "h2": "QR codes on packaging",
         "p": ["Put the code on a flat face of the box, away from seams, folds and barcodes that a checkout scanner reads. Glossy film and shrink wrap cause glare, so use higher contrast and a slightly larger size. If the code will be on shelves for years, link to a page on your own domain so you can change the content without reprinting."]},
        {"kind": "prose", "id": "colors", "h2": "Colors and CMYK",
         "p": ["Choose a code color that stays dark when printed in CMYK. A bright screen color can print lighter than expected. Aim for a contrast ratio of at least 4:1 between code and background; our generator warns you when contrast is low. Avoid metallic inks, gradients that fade to light shades, and backgrounds with patterns behind the code."]},
        {"kind": "cta", "h2": "Need a ready-to-print layout?",
         "p": "Make table tents, WiFi cards, counter stands and A4 sheets of QR labels, then print or save as PDF.",
         "href": "printable-qr-code-templates.html", "label": "Open printable templates"},
    ],
    "faq": [
        ("What is the best file format to print a QR code?",
         "SVG or PDF. They are vector files, so the code stays sharp at any size. Use a PNG of at least 2048 pixels if your software only accepts images."),
        ("What is the minimum size for a printed QR code?",
         "About 2 cm (0.8 in) for items held in the hand. Scale up for anything scanned from further away."),
        ("Can I print a QR code in color?",
         "Yes, as long as the code is clearly darker than the background. Test the printed piece, not just the screen."),
        ("Why does my printed QR code not scan?",
         "The usual causes are a code that is too small, a missing quiet zone, low contrast, glare, or a long link that makes the code too dense. Check it with the <a href=\"qr-code-tester.html\">QR code tester</a>."),
        ("Can I put a QR code on a t-shirt?",
         "Yes. Make it 8 cm or larger, use square modules and high error correction, and print on a flat area. Test a sample garment first."),
        ("Do printed QR codes expire?",
         "A static QR code never expires. It works as long as the link or content inside it works."),
    ],
    "related": [("qr-code-size-guide.html", "QR code size guide"), ("qr-code-tester.html", "QR code tester"), ("printable-qr-code-templates.html", "Printable QR code templates")],
}

SCAN_IPHONE = {**_ART,
    "slug": "how-to-scan-qr-code-on-iphone.html",
    "crumb": "How to Scan a QR Code on iPhone",
    "title": "How to Scan a QR Code on iPhone (Camera, Photos and Screenshots)",
    "description": "Scan QR codes on iPhone with the Camera app, the Code Scanner in Control Center, or from a photo or screenshot. Plus fixes when the iPhone will not scan.",
    "og_title": "How to Scan a QR Code on iPhone | SmartQRCraft",
    "og_description": "Every way to scan a QR code on iPhone, including from a screenshot, and what to do when it does not work.",
    "h1": "How to Scan a QR Code on iPhone",
    "lead": "You do not need an app. The iPhone camera reads QR codes on its own, and there are two more built-in ways for photos and screenshots.",
    "faq_h2": "iPhone QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "camera", "h2": "Method 1: the Camera app",
         "steps": [
             "Open the <strong>Camera</strong> app and choose Photo mode.",
             "Point the rear camera at the QR code and hold steady for a second. You do not need to take a picture.",
             "A yellow link or button appears above or below the code. Tap it to open the link, join WiFi, save a contact or start a call.",
         ],
         "after": ["Nothing appears? Go to <strong>Settings &gt; Camera</strong> and make sure <strong>Scan QR Codes</strong> is on."]},
        {"kind": "prose", "id": "code-scanner", "h2": "Method 2: Code Scanner in Control Center",
         "p": ["The Code Scanner opens a dedicated scanner with a flashlight button, handy in dark restaurants."],
         "steps": [
             "Swipe down from the top-right corner (or up from the bottom on iPhones with a Home button) to open Control Center.",
             "Tap <strong>Code Scanner</strong>. If you cannot see it, add it in Control Center settings.",
             "Point it at the code; the result opens automatically.",
         ]},
        {"kind": "prose", "id": "screenshot", "h2": "Method 3: from a photo or screenshot",
         "p": ["When the QR code is already on your iPhone, for example in a screenshot, email or chat:"],
         "steps": [
             "Open the image in the <strong>Photos</strong> app.",
             "On recent versions of iOS, a QR code button appears, or you can press and hold on the code to get the link.",
             "If your iPhone does not offer that, open our <a href=\"qr-code-scanner.html\">online QR code scanner</a> in Safari, tap <strong>Choose image</strong> and pick the screenshot. It is read on your phone; nothing is uploaded.",
         ]},
        {"kind": "table", "h2": "iPhone will not scan the QR code? Try this",
         "cols": ["Problem", "Fix"],
         "rows": [
             ["Nothing happens in Camera", "Turn on Settings &gt; Camera &gt; Scan QR Codes; use Photo mode, not Portrait or Video"],
             ["Too close or too far", "Move back until the whole code with its white border is on screen"],
             ["Dark room or glare", "Use Code Scanner and its flashlight; tilt to remove reflections"],
             ["Code on a screen", "Turn up the other screen's brightness; avoid moiré by stepping back"],
             ["Damaged or tiny code", "Try the online scanner with a sharp photo"],
             ["The link does nothing", "The code may be broken or point to a dead page; check it with the scanner to see the content"],
         ]},
        {"kind": "prose", "id": "safety", "h2": "Before you tap: a safety check",
         "p": ["The preview button shows the website name. Read it before you open it. Be careful with codes on parking meters, stickers and unexpected mail, and never enter passwords or bank details after scanning a code you do not trust. Our <a href=\"qr-code-safety.html\">QR code safety guide</a> explains common scams."]},
    ],
    "faq": [
        ("Do I need an app to scan QR codes on iPhone?",
         "No. The Camera app and the Code Scanner in Control Center both read QR codes on iOS 11 and later."),
        ("How do I scan a QR code from a screenshot on iPhone?",
         "Open the screenshot in Photos and press and hold the code, or use an online QR scanner and choose the image."),
        ("Why is my iPhone camera not scanning QR codes?",
         "Check that Scan QR Codes is on in Settings &gt; Camera, use Photo mode, and move back so the whole code fits on screen."),
        ("Can an iPhone scan a QR code to join WiFi?",
         "Yes. Scanning a WiFi QR code shows a Join Network button."),
        ("Is it safe to scan QR codes?",
         "Usually, but check the link preview before you open it, and be wary of codes stuck on top of other codes."),
    ],
    "related": [("how-to-scan-qr-code-on-android.html", "How to scan a QR code on Android"), ("qr-code-scanner.html", "Online QR code scanner"), ("qr-code-safety.html", "QR code safety")],
}

SCAN_ANDROID = {**_ART,
    "slug": "how-to-scan-qr-code-on-android.html",
    "crumb": "How to Scan a QR Code on Android",
    "title": "How to Scan a QR Code on Android (Samsung, Pixel and More)",
    "description": "Scan QR codes on any Android phone with the camera, the Quick Settings tile or Google Lens, including from a screenshot. Fixes for Samsung, Pixel and others.",
    "og_title": "How to Scan a QR Code on Android | SmartQRCraft",
    "og_description": "Every built-in way to scan a QR code on Android, including screenshots.",
    "h1": "How to Scan a QR Code on Android",
    "lead": "Most Android phones can scan QR codes without an extra app. The exact buttons depend on the brand and Android version, so here are all the built-in ways.",
    "faq_h2": "Android QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "camera", "h2": "Method 1: the camera app",
         "steps": [
             "Open the camera and point it at the QR code.",
             "Hold steady. A link or button appears on screen.",
             "Tap it to open the link or action.",
         ],
         "after": ["On Samsung Galaxy phones, if nothing appears, open the camera settings and turn on <strong>Scan QR codes</strong>. On Pixel phones the camera uses Google Lens suggestions; make sure they are switched on in camera settings."]},
        {"kind": "prose", "id": "quick-settings", "h2": "Method 2: the Quick Settings tile",
         "steps": [
             "Swipe down twice from the top of the screen to open Quick Settings.",
             "Tap <strong>Scan QR code</strong>. If it is not there, tap the pencil (edit) icon and drag it in.",
             "Point at the code.",
         ],
         "after": ["This tile is available on many phones running Android 13 or later; some brands use their own name for it."]},
        {"kind": "prose", "id": "lens", "h2": "Method 3: Google Lens (also for screenshots)",
         "steps": [
             "Open the Google app or Google Lens and tap the camera icon, or long-press the Home button or navigation handle on phones that support it.",
             "Point at a code, or choose a screenshot or photo from your gallery.",
             "Tap the link Lens finds.",
         ],
         "after": ["You can also open a screenshot in Google Photos and tap <strong>Lens</strong>. Or use our <a href=\"qr-code-scanner.html\">online QR code scanner</a> and choose the image; it runs on your phone and nothing is uploaded."]},
        {"kind": "table", "h2": "By brand",
         "cols": ["Phone", "Quickest built-in way"],
         "rows": [
             ["Samsung Galaxy", "Camera app (Scan QR codes on), Quick Settings tile, or Bixby Vision"],
             ["Google Pixel", "Camera app, Quick Settings tile, or Google Lens"],
             ["Xiaomi, Redmi, POCO", "The Scanner app or the camera; Quick Settings on newer versions"],
             ["OnePlus, OPPO, realme, vivo", "Camera app or the scan shortcut in the search bar or Quick Settings"],
             ["Motorola, Nokia and others", "Camera with Google Lens, or the Google app"],
         ],
         "p": ["Menus change between software versions, so if your phone is different, search its settings for &quot;QR&quot;."]},
        {"kind": "table", "h2": "Android will not scan? Try this",
         "cols": ["Problem", "Fix"],
         "rows": [
             ["No pop-up in the camera", "Turn on QR scanning or Google Lens suggestions in camera settings"],
             ["Code is blurry", "Clean the lens, move back a little and hold still"],
             ["Dark place", "Turn on the flashlight from Quick Settings"],
             ["Code in a screenshot", "Use Google Lens from Google Photos, or the online scanner"],
             ["Opens the wrong thing", "Check the content first with a scanner that previews, such as ours"],
         ]},
    ],
    "faq": [
        ("Can Android phones scan QR codes without an app?",
         "Yes. Most current Android phones scan QR codes with the camera, a Quick Settings tile or Google Lens."),
        ("How do I scan a QR code from a screenshot on Android?",
         "Open the screenshot in Google Photos and tap Lens, or use an online QR scanner and choose the image."),
        ("How do I scan a QR code on a Samsung phone?",
         "Open the camera and point it at the code. If nothing happens, turn on Scan QR codes in the camera settings, or use the Quick Settings tile."),
        ("Why does my Android camera not detect QR codes?",
         "QR scanning or Lens suggestions may be switched off in camera settings, or the code may be too small, blurry or dark."),
        ("Is it safe to scan QR codes on Android?",
         "Check the link before you open it and avoid codes stuck over other codes. See our safety guide for common scams."),
    ],
    "related": [("how-to-scan-qr-code-on-iphone.html", "How to scan a QR code on iPhone"), ("qr-code-scanner.html", "Online QR code scanner"), ("qr-code-safety.html", "QR code safety")],
}

GUIDES = [PRINT, SCAN_IPHONE, SCAN_ANDROID]
