"""Pages from the India keyword review (research/keywords-in.csv, Sept 2026). The English ones are shared
(.com, .co.uk, .in); the bill/receipt page is India only.
qr code blue 74K kd28, qr photo 49.5K kd27, qr code example 49.5K kd51, qr code with serial number 33.1K kd59,
heart qr code generator 12.1K kd23, qr code styles 8.1K kd63 / fancy 5.4K kd37 / shapes 3.6K kd30, receipt qr code 4.4K kd16."""

_ART = {"static": True, "noindex": False, "type": "url"}

EXAMPLES = {**_ART,
    "slug": "qr-code-examples.html",
    "crumb": "QR Code Examples",
    "title": "QR Code Examples: 8 Sample QR Codes to Scan and Test",
    "description": "Sample QR codes you can scan: link, WiFi, contact, call, email, text, a heart design and a blue QR code. See what each one contains and make your own free.",
    "og_title": "QR Code Examples to Scan | SmartQRCraft",
    "og_description": "Eight real sample QR codes to scan and test, with what each one contains.",
    "h1": "QR Code Examples to Scan and Test",
    "lead": "Here are eight real QR codes. Point your phone camera at any of them to see what happens. Each example says what is stored inside and links to the tool that makes one like it.",
    "faq_h2": "Questions About the Examples",
    "sections": [
        {"kind": "gallery", "h2": "Sample QR codes",
         "p": ["All the examples are safe to scan. The phone number is in the 555-01xx range reserved for fiction, and the email addresses use the reserved example.com domain, so nobody real is contacted."],
         "items": [
             {"img": "assets/examples/link.svg", "alt": "Sample QR code linking to smartqrcraft.com", "h3": "Website link", "p": "Opens a web page, here smartqrcraft.com.", "href": "index.html#generator", "label": "Make a link QR code"},
             {"img": "assets/examples/wifi.svg", "alt": "Sample WiFi QR code for the network Cafe_Guest", "h3": "WiFi", "p": "Offers to join the network Cafe_Guest (password Example2026).", "href": "wifi-qr-code-generator.html", "label": "Make a WiFi QR code"},
             {"img": "assets/examples/contact.svg", "alt": "Sample contact vCard QR code for Alex Example", "h3": "Contact card", "p": "Saves the contact Alex Example to the address book.", "href": "vcard-qr-code-generator.html", "label": "Make a contact QR code"},
             {"img": "assets/examples/call.svg", "alt": "Sample call QR code with a phone number", "h3": "Call", "p": "Shows a phone number with a call button. Nothing is dialled until you tap.", "href": "phone-qr-code-generator.html", "label": "Make a call QR code"},
             {"img": "assets/examples/email.svg", "alt": "Sample email QR code with a subject", "h3": "Email", "p": "Opens a new email to hello@example.com with the subject Hello.", "href": "email-qr-code-generator.html", "label": "Make an email QR code"},
             {"img": "assets/examples/hello.svg", "alt": "Sample text QR code that says hello", "h3": "Text (hello)", "p": "Shows a short hello message on screen, even offline.", "href": "text-qr-code-generator.html", "label": "Make a text QR code"},
             {"img": "assets/examples/heart.svg", "alt": "Sample heart-shaped QR code design", "h3": "Heart design", "p": "The same technology in a heart frame, with a short message.", "href": "heart-qr-code-generator.html", "label": "Make a heart QR code"},
             {"img": "assets/examples/blue.svg", "alt": "Sample blue QR code", "h3": "Blue QR code", "p": "A colored code that still scans, because the blue is dark enough.", "href": "color-qr-code-generator.html", "label": "Make a color QR code"},
         ]},
        {"kind": "table", "h2": "What is inside each example?",
         "p": ["A QR code only stores text. The start of the text tells the phone what to do with it."],
         "cols": ["Example", "Stored text"],
         "rows": [
             ["Website link", "<code>https://smartqrcraft.com</code>"],
             ["WiFi", "<code>WIFI:T:WPA;S:Cafe_Guest;P:Example2026;;</code>"],
             ["Contact card", "<code>BEGIN:VCARD ... END:VCARD</code> with name, company, phone and email"],
             ["Call", "<code>tel:+12025550147</code>"],
             ["Email", "<code>mailto:hello@example.com?subject=Hello</code>"],
             ["Text", "The message itself"],
         ]},
        {"kind": "prose", "id": "test", "h2": "Using the examples to test a scanner",
         "p": ["The samples are handy for checking that a phone camera, scanner app or point-of-sale scanner reads QR codes. Scan them straight from the screen, or print this page. If a code fails, try moving back so the whole code with its white border fits in the frame. To check a code you made yourself, use the <a href=\"qr-code-tester.html\">QR code tester</a>."]},
    ],
    "faq": [
        ("Can I scan these sample QR codes?",
         "Yes. They are real and safe: the phone number is reserved for fiction and the email domain is a reserved example domain."),
        ("What does a QR code look like?",
         "A square of black and white modules with three large squares in the corners, which scanners use to find the code."),
        ("Is there a sample QR code that just says hello?",
         "Yes, the Text (hello) example shows a hello message when scanned."),
        ("Can a QR code be colored or heart-shaped?",
         "Yes, as the heart and blue examples show. Keep the code dark on a light background so it scans."),
        ("Can I use these examples in my own project?",
         "Use them to test or to show how QR codes work. For real use, make your own code with your own details."),
    ],
    "related": [("what-is-a-qr-code.html", "What is a QR code?"), ("qr-code-tester.html", "QR code tester"), ("index.html#generator", "Free QR code generator")],
}

IMAGE = {
    "slug": "qr-code-image.html",
    "crumb": "QR Code Image Generator",
    "type": "url",
    "types": "url,text,wifi,vcard,phone,email,location,whatsapp",
    "lock": False,
    "tool_name": "QR Code Image Generator",
    "field_label": "", "field_placeholder": "",
    "cta": "SCAN ME",
    "empty": "Enter your details to create the QR code image.",
    "title": "QR Code Image Generator | Download QR as JPG, PNG or SVG — SmartQRCraft",
    "description": "Make a QR code image and download it as JPG, PNG or SVG, up to 4096 px. Add it to photos, posters or documents, or put a photo behind the code. Free, no signup.",
    "og_title": "QR Code Image Generator (JPG, PNG) | SmartQRCraft",
    "og_description": "Create a QR code image and download it as JPG, PNG or SVG. Free, no signup.",
    "h1": 'Free <span class="accent">QR Code Image</span> Generator',
    "lead": "Create a QR code and save it as an image: JPG for photos and WhatsApp, PNG for documents and websites, SVG for print. Sizes up to 4096 pixels, with no watermark.",
    "faq_h2": "QR Code Image Questions",
    "sections": [
        {"kind": "table", "h2": "Which image format should you download?",
         "cols": ["Format", "Best for", "Notes"],
         "rows": [
             ["JPG", "Sharing in chats, adding to photos, social posts", "Always has a white background; smallest file"],
             ["PNG", "Word, PowerPoint, websites, presentations", "Sharp edges; can have a transparent background"],
             ["SVG", "Print shops, Canva, Illustrator", "Vector: stays sharp at any size"],
             ["PDF / EPS", "Professional printing", "Vector files with solid colors"],
         ]},
        {"kind": "prose", "id": "how", "h2": "How to make a QR code image",
         "steps": [
             "Choose what the code should do: open a link, join WiFi, save a contact and more.",
             "Enter your details and style the code: colors, shapes, frame text and logo.",
             "Pick a download size. 1024 px suits screens and documents; 2048 px or more suits large prints.",
             "Click <strong>Download JPG</strong> or <strong>Download PNG</strong>. The image is saved to your device.",
         ]},
        {"kind": "prose", "id": "photo", "h2": "A QR code with your photo in it",
         "p": ["Want the code to look like a picture? Open the <strong>Logo</strong> tab and turn on <strong>Picture QR (photo behind the code)</strong>. Your photo shows through small dots while the code still scans. Picture QR codes download as PNG or JPG.",
               "A QR code cannot store the photo itself, because it only holds a few thousand characters. To share a photo, upload it to a service such as Google Photos or Google Drive, copy the share link and make a QR code of that link."]},
        {"kind": "prose", "id": "tips", "h2": "Tips for QR code images",
         "bullets": [
             "<strong>Do not resize small images up.</strong> Download at the size you need; enlarging a small JPG makes it blurry.",
             "<strong>Keep a white border</strong> around the code when you place it on a photo or colored background.",
             "<strong>Screenshots work,</strong> but a downloaded file is sharper and has no phone status bar.",
             "<strong>Test before sharing:</strong> scan the saved image with a second phone, or check it with the <a href=\"qr-code-tester.html\">QR code tester</a>.",
         ]},
    ],
    "faq": [
        ("How do I download a QR code as an image?",
         "Create the code above and click Download JPG or Download PNG. Choose the size first."),
        ("Can I get the QR code as a JPEG?",
         "Yes. Click Download JPG. JPG images always have a white background."),
        ("How do I make a QR code with a picture?",
         "Turn on Picture QR in the Logo tab and choose a photo. The photo appears behind the code and it still scans."),
        ("Can a QR code contain a photo?",
         "No. It can contain a link to a photo. Upload the photo online and make a QR code of the share link."),
        ("Is the QR code image free to use?",
         "Yes, for personal and business use, with no watermark and no expiry."),
    ],
    "related": [("qr-code-with-logo.html", "QR code with logo"), ("color-qr-code-generator.html", "Color QR code generator"), ("qr-code-examples.html", "QR code examples")],
}

COLOR = {
    "slug": "color-qr-code-generator.html",
    "crumb": "Color QR Code Generator",
    "type": "url",
    "types": "url,text,wifi,vcard,phone,email,location,whatsapp",
    "lock": False,
    "fg": "#1D4ED8",
    "tool_name": "Color QR Code Generator",
    "field_label": "", "field_placeholder": "",
    "cta": "SCAN ME",
    "empty": "Enter your details to create a colored QR code.",
    "title": "Blue & Color QR Code Generator | Custom Color QR Codes Free — SmartQRCraft",
    "description": "Make a blue, red, green or gold QR code in your brand color, with gradients and a color check that keeps it scannable. Free, no signup, PNG, JPG or SVG.",
    "og_title": "Blue & Color QR Code Generator | SmartQRCraft",
    "og_description": "Colored QR codes in any shade, with a contrast check so they still scan.",
    "h1": 'Blue &amp; <span class="accent">Color QR Code</span> Generator',
    "lead": "The generator opens with a blue QR code. Pick any color, add a gradient or a second color for the corners, and the contrast check tells you if the code may be hard to scan.",
    "faq_h2": "Color QR Code Questions",
    "sections": [
        {"kind": "table", "h2": "Colors that scan well",
         "p": ["Scanners look for a dark code on a light background. These shades have strong contrast on white:"],
         "cols": ["Color", "Hex code", "Contrast on white"],
         "rows": [
             ["Royal blue", "<code>#1D4ED8</code>", "Strong"],
             ["Navy", "<code>#1E3A8A</code>", "Very strong"],
             ["Red", "<code>#B91C1C</code>", "Strong"],
             ["Forest green", "<code>#065F46</code>", "Very strong"],
             ["Purple", "<code>#6D28D9</code>", "Strong"],
             ["Gold / brown", "<code>#78350F</code> on cream <code>#FEF3C7</code>", "Strong"],
             ["Light blue, yellow, pink", "", "Too light: avoid for the code itself"],
         ]},
        {"kind": "prose", "id": "how", "h2": "How to make a colored QR code",
         "steps": [
             "Enter your link or details.",
             "In <strong>Color &amp; Shape</strong>, pick a color or type your brand's hex code.",
             "For a two-tone look, choose a gradient or a different color for the corner squares.",
             "Watch for the low-contrast warning. If it appears, pick a darker code color or a lighter background.",
             "Download and test the printed version before you print many copies.",
         ]},
        {"kind": "prose", "id": "rules", "h2": "Three rules for colored QR codes",
         "bullets": [
             "<strong>Dark on light.</strong> A white QR code on a black or blue background looks striking, but some scanners cannot read inverted codes.",
             "<strong>Keep enough contrast.</strong> Aim for a contrast ratio of at least 4:1; the generator warns below 3:1.",
             "<strong>Check print colors.</strong> Bright screen colors can print lighter in CMYK. Test a printed sample.",
         ]},
        {"kind": "cards", "eyebrow": "Ideas", "h2": "Popular color choices",
         "cards": [
             ("Blue", "Trustworthy and easy to scan; popular for businesses, clinics and banks."),
             ("Brand color", "Match your logo so the code looks like part of the design."),
             ("Red and pink", "Food, retail and celebrations; try the <a href=\"heart-qr-code-generator.html\">heart frame</a>."),
             ("Green", "Eco, health and outdoor brands."),
             ("Gold on cream", "Weddings, invitations and premium packaging."),
             ("Black", "Still the most reliable choice for tiny codes."),
         ]},
    ],
    "faq": [
        ("Can a QR code be blue?",
         "Yes. A dark or medium blue on a white background scans well. Very light blues may not."),
        ("Do colored QR codes still work?",
         "Yes, as long as the code is clearly darker than the background. The generator warns you when contrast is low."),
        ("Can I make a white QR code on a black background?",
         "You can, but some scanner apps cannot read inverted codes. A dark code on a light background is safer."),
        ("How do I use my exact brand color?",
         "Type the hex code, for example #1D4ED8, into the color field."),
        ("Is it free?",
         "Yes, with no signup, no watermark and no expiry."),
    ],
    "related": [("qr-code-styles.html", "QR code styles and designs"), ("heart-qr-code-generator.html", "Heart QR code generator"), ("qr-code-with-logo.html", "QR code with logo")],
}

HEART = {
    "slug": "heart-qr-code-generator.html",
    "crumb": "Heart QR Code Generator",
    "type": "text",
    "types": "text,url,wifi,vcard,phone,whatsapp",
    "lock": False,
    "fg": "#BE123C",
    "frame": "heart",
    "tool_name": "Heart QR Code Generator",
    "field_label": "", "field_placeholder": "",
    "cta": "SCAN ME",
    "empty": "Type a message or link to create your heart QR code.",
    "title": "Heart QR Code Generator | Free Heart-Shaped QR Code Design — SmartQRCraft",
    "description": "Make a heart QR code for a love note, wedding, Valentine's card or gift. A secret message or link inside a heart frame, free, no signup, PNG, JPG or SVG.",
    "og_title": "Heart QR Code Generator | SmartQRCraft",
    "og_description": "A QR code inside a heart: love notes, weddings and gifts. Free, no signup.",
    "h1": 'Free <span class="accent">Heart QR Code</span> Generator',
    "lead": "The generator opens with a red code inside a heart frame. Type a secret message, or add a link to a song, video or photo album, and download a heart QR code for a card or gift.",
    "faq_h2": "Heart QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how", "h2": "How to make a heart QR code",
         "steps": [
             "Choose <strong>Text</strong> for a hidden message, or <strong>URL</strong> for a song, video or photo album link.",
             "Type your message. Short messages make simpler codes that print well.",
             "Change the frame text under the heart, for example &quot;SCAN ME&quot; or &quot;FOR YOU&quot;.",
             "Pick a color: red, pink or gold all work if they are dark enough.",
             "Download PNG or JPG for sharing, or SVG for printing on a card.",
         ]},
        {"kind": "cards", "eyebrow": "Ideas", "h2": "What to put inside a heart QR code",
         "cards": [
             ("Love note", "A short secret message that appears when scanned. Works offline."),
             ("Your song", "A link to a song or playlist on Spotify or YouTube."),
             ("Photo album", "A shared album link from Google Photos or iCloud."),
             ("Wedding", "The wedding website, RSVP form or a guest photo upload link."),
             ("Gift tag", "A video message or a thank-you note."),
             ("Proposal", "The question, hidden in plain sight."),
         ]},
        {"kind": "prose", "id": "print", "h2": "Printing a heart QR code",
         "p": ["The heart frame adds space around the code, so print the whole design at least 4 cm (1.6 in) wide for cards and larger for posters. Keep the code itself dark on white. The heart outline and text are decoration; the square code in the middle is what the phone reads. Test one printed copy before you print more."]},
    ],
    "faq": [
        ("How do I make a QR code in a heart shape?",
         "Use this generator: it opens with the heart frame already selected. Add your message or link and download."),
        ("Does a heart QR code still scan?",
         "Yes. The code in the middle is a normal square QR code; the heart is a frame around it."),
        ("Can I hide a secret message in a QR code?",
         "Yes. Choose Text and type the message. It shows on the phone screen when scanned, without needing the internet."),
        ("Can I change the color of the heart?",
         "Yes. The heart takes the code color. Choose any color that is dark enough to scan."),
        ("Is it free?",
         "Yes, with no signup and no watermark."),
    ],
    "related": [("qr-code-for-wedding-photos.html", "QR code for wedding photos"), ("color-qr-code-generator.html", "Color QR code generator"), ("qr-code-styles.html", "QR code styles")],
}

STYLES = {
    "slug": "qr-code-styles.html",
    "crumb": "QR Code Styles",
    "type": "url",
    "types": "url,text,wifi,vcard,phone,email,location,whatsapp",
    "lock": False,
    "fg": "#6D28D9",
    "style": "diamond",
    "tool_name": "Fancy QR Code Designer",
    "field_label": "", "field_placeholder": "",
    "cta": "SCAN ME",
    "empty": "Enter your details to design your QR code.",
    "title": "QR Code Styles & Designs | Fancy, Cute and Custom Shapes — SmartQRCraft",
    "description": "Design a fancy QR code: dot shapes, rounded corners, gradients, frames like hearts and shopping bags, plus templates. See every style and which ones scan best. Free.",
    "og_title": "QR Code Styles & Fancy Designs | SmartQRCraft",
    "og_description": "Every QR code style in one place: shapes, eyes, colors, frames and templates.",
    "h1": 'Fancy <span class="accent">QR Code Styles</span> and Designs',
    "lead": "A QR code does not have to be plain black squares. Change the module shape, the corner eyes, the colors and the frame, then check that it still scans.",
    "faq_h2": "QR Code Style Questions",
    "sections": [
        {"kind": "table", "h2": "Every style option",
         "cols": ["Option", "Choices", "Scanning"],
         "rows": [
             ["Module shape", "Square, rounded, dots, diamond", "Square and rounded scan best; dots and diamond need a larger print and a test"],
             ["Corner eyes", "Classic, soft, circle", "All scan well"],
             ["Colors", "Any color, gradients, separate eye color", "Keep the code dark on a light background"],
             ["Frames", "Bar, badge, speech bubble, outline, corners, heart, shopping bag, gift box, coffee cup, envelope, chef hat, phone", "Frames sit around the code and do not affect scanning"],
             ["Logo", "Your logo in the middle", "Uses high error correction; keep the logo small"],
             ["Picture QR", "A photo behind small dots", "PNG and JPG only; test carefully"],
             ["Templates", "Classic, violet, sunset, ocean, forest, midnight, gold", "All tested dark-on-light combinations"],
         ]},
        {"kind": "prose", "id": "how", "h2": "How to design a fancy QR code",
         "steps": [
             "Enter your link or details. The designer opens with a purple diamond style you can change.",
             "Start from a template, then adjust shape, eyes and colors in <strong>Color &amp; Shape</strong>.",
             "Add a frame with a call to action in the <strong>Frame</strong> tab.",
             "Add your logo or a background photo in the <strong>Logo</strong> tab.",
             "Download, then check the saved image with the <a href=\"qr-code-tester.html\">QR code tester</a>.",
         ]},
        {"kind": "cards", "eyebrow": "Looks", "h2": "Style ideas",
         "cards": [
             ("Minimalist", "Black rounded modules, soft eyes and no frame."),
             ("Cute", "Dots with circle eyes in pink or purple, plus a heart frame."),
             ("Luxury", "Gold template on cream with a thin outline frame."),
             ("Café", "Brown code in the coffee cup frame for menus."),
             ("Shop", "Your brand color in the shopping bag frame."),
             ("Tech", "Navy to blue gradient with square modules."),
         ]},
        {"kind": "prose", "id": "limits", "h2": "What cannot change",
         "p": ["The three large corner squares, the quiet zone around the code and good contrast are what scanners rely on. Circular or star-shaped outlines are possible as frames, but the code itself stays square. Designs that hide the corner squares or fade the code into the background often fail on older phones."]},
    ],
    "faq": [
        ("Can I change the shape of a QR code?",
         "You can change the shape of the modules (dots, rounded, diamond) and the corner eyes, and add frames such as a heart. The code itself stays square."),
        ("Which QR code style scans best?",
         "Square or rounded modules, dark on white, with a clear border. Dots and diamonds look great but need a larger print."),
        ("How do I make a cute QR code?",
         "Use dots with circle eyes, a pink or purple color and the heart frame."),
        ("Do fancy QR codes expire?",
         "No. Style does not affect expiry. Static codes made here never expire."),
        ("Is the designer free?",
         "Yes, every style is free, with no signup and no watermark."),
    ],
    "related": [("color-qr-code-generator.html", "Color QR code generator"), ("heart-qr-code-generator.html", "Heart QR code generator"), ("qr-code-with-logo.html", "QR code with logo")],
}

SERIAL = {
    "slug": "serial-number-qr-code-generator.html",
    "crumb": "Serial Number QR Code Generator",
    "widget": "bulk",
    "type": "url",
    "tool_name": "Serial Number QR Codes",
    "field_label": "", "field_placeholder": "", "cta": "", "empty": "",
    "title": "Serial Number QR Code Generator | Numbered QR Codes in Bulk — SmartQRCraft",
    "description": "Make QR codes with serial numbers: SN-0001 to SN-1000 or numbered links, generated in bulk and downloaded as one ZIP with a CSV list. Free, private, no signup.",
    "og_title": "Serial Number QR Code Generator | SmartQRCraft",
    "og_description": "Numbered QR codes in bulk: one ZIP, up to 1000 codes, free and private.",
    "h1": 'Serial Number <span class="accent">QR Code Generator</span>',
    "lead": "Open <strong>Make a numbered list</strong>, set a prefix and a number range, and get one QR code per serial number, all in a single ZIP with a CSV index.",
    "faq_h2": "Serial Number QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how", "h2": "How to make numbered QR codes",
         "steps": [
             "Click <strong>Make a numbered list (serial numbers)</strong> in the tool.",
             "Set a prefix such as <code>SN-</code> or <code>INV-2026-</code>, the first and last number, and the number of digits (0001).",
             "Click <strong>Fill the list</strong>. Each line becomes one QR code.",
             "Choose color, size and PNG or SVG, then <strong>Generate QR codes</strong> and <strong>Download ZIP</strong>.",
             "Print them on labels with the <a href=\"printable-qr-code-templates.html\">printable templates</a>, or give the ZIP to your printer.",
         ]},
        {"kind": "table", "h2": "Prefix examples",
         "cols": ["Prefix", "Result", "Use"],
         "rows": [
             ["<code>SN-</code> + 4 digits", "SN-0001, SN-0002 ...", "Product serial labels"],
             ["<code>ASSET-</code>", "ASSET-0001 ...", "Office equipment and IT asset tags"],
             ["<code>https://example.com/item/</code>", "One link per item", "Product pages, warranty registration"],
             ["<code>TICKET-2026-</code>", "TICKET-2026-0001 ...", "Event tickets and raffle numbers"],
             ["<code>TABLE-</code>", "TABLE-01 ...", "Restaurant tables"],
         ]},
        {"kind": "prose", "id": "tips", "h2": "Tips for serial QR codes",
         "bullets": [
             "<strong>Keep the serial printed too.</strong> Print the number as text next to each code for people and for checking.",
             "<strong>Use the CSV.</strong> The ZIP includes <code>manifest.csv</code> listing each file and its content, useful for stock sheets.",
             "<strong>Linking to pages?</strong> A prefix like <code>https://yoursite.com/p/</code> gives each item its own page you control.",
             "<strong>Up to 1,000 codes per batch.</strong> For more, run several batches with different ranges.",
         ]},
    ],
    "faq": [
        ("How do I make QR codes with serial numbers?",
         "Open Make a numbered list in the tool, set a prefix and a number range, fill the list and generate. You get one QR code per number in a ZIP."),
        ("Can I add leading zeros like 0001?",
         "Yes. Choose the number of digits, for example 0001."),
        ("How many numbered QR codes can I make?",
         "Up to 1,000 per batch. Run more batches for larger ranges."),
        ("Can each number link to its own web page?",
         "Yes. Use a web address as the prefix, for example https://example.com/item/, and each code opens its own page."),
        ("Is my list uploaded anywhere?",
         "No. Everything is generated on your device."),
    ],
    "related": [("bulk-qr-code-generator.html", "Bulk QR code generator"), ("barcode-generator.html", "Barcode generator"), ("printable-qr-code-templates.html", "Printable QR labels")],
}

BILL = {
    "domain": "smartqrcraft.in", "lang": "en-IN",
    "slug": "qr-code-for-bill.html",
    "crumb": "QR Code for Bills and Receipts",
    "type": "upi",
    "tool_name": "Bill Payment QR Code",
    "field_label": "", "field_placeholder": "",
    "cta": "SCAN & PAY",
    "empty": "Enter your UPI ID to make a payment QR code for your bill.",
    "title": "QR Code for Bill & Receipt | UPI Payment QR on Invoices — SmartQRCraft",
    "description": "Add a UPI payment QR code to your bills, receipts and invoices. Fixed amount and bill number included, works with GPay, PhonePe, Paytm and BHIM. Free, no signup.",
    "og_title": "QR Code for Bills and Receipts | SmartQRCraft India",
    "og_description": "A UPI payment QR code with amount and bill number for your invoices and receipts.",
    "h1": 'UPI <span class="accent">QR Code for Bills</span> and Receipts',
    "lead": "Put a payment QR code on every bill. Enter your UPI ID, the bill amount and the bill number, and the customer pays the exact amount from any UPI app.",
    "faq_h2": "Bill QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how", "h2": "How to add a payment QR code to a bill",
         "steps": [
             "Enter your UPI ID and business name.",
             "Type the bill total in <strong>Amount</strong> and the bill or invoice number in <strong>Payment note</strong>.",
             "Download the PNG and place it on the bill in Word, Excel, Google Docs or your billing software.",
             "When the payment arrives, the note shows which bill was paid.",
         ]},
        {"kind": "table", "h2": "Fixed amount or open amount?",
         "cols": ["", "Fixed amount on each bill", "One open QR for all bills"],
         "rows": [
             ["Customer effort", "Only confirms", "Types the amount"],
             ["Mistakes", "Amount is always right", "Customer may enter the wrong amount"],
             ["Work for you", "One QR per bill", "Print once"],
             ["Best for", "Invoices, fees, rent, subscriptions", "Counters, small shops"],
         ]},
        {"kind": "cards", "eyebrow": "Where to Use It", "h2": "Bills that work well with a QR code",
         "cards": [
             ("GST invoices", "Freelancers and small firms get paid faster."),
             ("Restaurant bills", "Guests pay at the table from the printed bill."),
             ("Tuition and school fees", "The fee slip carries its own QR code."),
             ("Rent and maintenance", "Societies add a QR code with the flat number as the note."),
             ("Clinic and pharmacy receipts", "Patients pay without cash."),
             ("Delivery and COD slips", "Customers pay on delivery by scanning."),
         ]},
        {"kind": "prose", "id": "safe", "h2": "Safety tips",
         "bullets": [
             "<strong>Always confirm the payment in your own UPI app</strong> or bank before marking a bill paid. A screenshot is not proof.",
             "<strong>Print your business name next to the code</strong> so customers can see who they are paying.",
             "<strong>Never ask customers for a UPI PIN</strong> except inside their own UPI app when they pay.",
         ]},
    ],
    "faq": [
        ("How do I put a UPI QR code on a bill?",
         "Make the code here with your UPI ID, the amount and the bill number, download it and paste it into your bill or invoice."),
        ("Can the QR code include the bill amount?",
         "Yes. Enter the amount; the customer's UPI app opens with it filled in."),
        ("Will I know which bill was paid?",
         "Yes, if you put the bill number in the payment note. It appears with the payment in your UPI app."),
        ("Does it work with GPay, PhonePe and Paytm?",
         "Yes. It is a standard UPI QR code that works with any UPI app."),
        ("Is it free?",
         "Yes. The code is free, and we never see your UPI ID because it is made in your browser."),
    ],
    "related": [("upi-qr-code-generator.html", "UPI QR code generator"), ("shop-qr-code.html", "QR code for shop"), ("printable-qr-code-templates.html", "Printable Scan & Pay stand")],
}

IN4_SHARED = [EXAMPLES, IMAGE, COLOR, HEART, STYLES, SERIAL]
IN4_LOCAL = [BILL]
