"""Generator pages for the remaining built-in QR types: phone, email, SMS, plain text, app store,
Telegram, X, MeCard and Bitcoin. English; shared pages appear on .com, .co.uk and .in."""


def _test():
    return "Scan the finished code with two different phones (for example an iPhone and an Android) before you print it."


PHONE = {
    "slug": "phone-qr-code-generator.html",
    "crumb": "Phone Call QR Code Generator",
    "type": "phone",
    "tool_name": "Phone Call QR Code Generator",
    "field_label": "Phone number with country code",
    "field_placeholder": "+1 555 019 2834",
    "cta": "CALL US",
    "empty": "Enter a phone number to generate the QR code.",
    "title": "Free Calling QR Code Generator | QR Code for a Phone Number — SmartQRCraft",
    "description": "Make a free calling QR code: people scan it and their phone offers to call your number. Custom colors, logo, PNG or SVG. No signup, never expires.",
    "og_title": "Free Calling QR Code Generator | SmartQRCraft",
    "og_description": "Turn a phone number into a QR code that starts a call. Free, no signup, PNG or SVG.",
    "h1": 'Free <span class="accent">Calling QR Code</span> Generator',
    "lead": "Type a phone number and download a QR code. When someone scans it, their phone shows your number and offers to call it, so nobody has to dial by hand.",
    "faq_h2": "Phone QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make a QR code for a phone number",
         "p": ["A calling QR code stores your number in the standard <code>tel:</code> format that phones understand."],
         "steps": [
             "Type the number <strong>with the country code</strong>, for example +1 for the US, +44 for the UK or +91 for India.",
             "Choose colors and a frame such as &quot;Call us&quot;, and add your logo if you want.",
             "Download PNG for screens and documents, or SVG for print.",
             _test(),
         ]},
        {"kind": "prose", "id": "what-happens", "h2": "What happens when someone scans it",
         "p": ["The phone camera reads the code and shows a prompt such as &quot;Call +1 555 019 2834&quot;. The call only starts when the person taps it. A QR code cannot place a call on its own, which is a good thing: people stay in control.",
               "Spaces, dashes and brackets are removed automatically, because phones expect only digits and a leading plus sign."]},
        {"kind": "table", "h2": "Country code examples",
         "p": ["Always include the country code. Without it, a code scanned by a visitor from abroad may dial the wrong number."],
         "cols": ["Country", "Local number", "What to type"],
         "rows": [
             ["United States", "(555) 019-2834", "+1 555 019 2834"],
             ["United Kingdom", "020 7946 0000", "+44 20 7946 0000 (drop the first 0)"],
             ["India", "098765 43210", "+91 98765 43210 (drop the first 0)"],
             ["Germany", "030 123456", "+49 30 123456 (drop the first 0)"],
         ]},
        {"kind": "cards", "eyebrow": "Where to Use It", "h2": "Where a calling QR code helps",
         "cards": [
             ("Shop windows &amp; doors", "Let people call when you are closed or busy."),
             ("Vehicles &amp; vans", "Trades and delivery services get calls from parked vans."),
             ("For-sale signs", "Buyers call from the street without typing."),
             ("Flyers &amp; posters", "Turn a printed ad into a phone call in one step."),
             ("Equipment &amp; machines", "Put a support or service line right on the device."),
             ("Lost-item tags", "Keys, bags and pet tags that call the owner."),
         ]},
        {"kind": "prose", "id": "tips", "h2": "Tips for phone QR codes",
         "bullets": [
             "<strong>Print the number too.</strong> Some people prefer to dial, and it builds trust to see where the call goes.",
             "<strong>Say when you answer.</strong> &quot;Scan to call, Mon to Fri 9 to 5&quot; avoids missed calls.",
             "<strong>Want a chat instead?</strong> A <a href=\"sms-qr-code-generator.html\">text message QR code</a> or a WhatsApp code may suit people who dislike calls.",
             "<strong>Size:</strong> about 2 cm (0.8 in) is enough for a card, larger for signs read from a distance. See the <a href=\"qr-code-size-guide.html\">size guide</a>.",
         ]},
    ],
    "faq": [
        ("How do I make a QR code that calls a phone number?",
         "Type the number with its country code into the generator on this page and download the code. Scanning it shows the number and a call button."),
        ("Does scanning the code call automatically?",
         "No. The phone shows the number and the person taps to call. A QR code cannot start a call without the person agreeing."),
        ("Does it work on iPhone and Android?",
         "Yes. Both the iPhone camera and Android cameras recognise phone number QR codes."),
        ("Can I change the number later?",
         "No. The number is stored in the code itself. If it changes, make and print a new code."),
        ("Is it free?",
         "Yes. The code is free, has no watermark and never expires."),
        ("Can I add my logo?",
         "Yes. Turn on Center Logo and upload a square image. Keep it small so the code still scans."),
    ],
    "related": [
        ("sms-qr-code-generator.html", "SMS QR code generator"),
        ("email-qr-code-generator.html", "Email QR code generator"),
        ("vcard-qr-code-generator.html", "vCard QR code generator (save the whole contact)"),
    ],
}

EMAIL = {
    "slug": "email-qr-code-generator.html",
    "crumb": "Email QR Code Generator",
    "type": "email",
    "tool_name": "Email QR Code Generator",
    "field_label": "Recipient email",
    "field_placeholder": "hello@example.com",
    "cta": "EMAIL US",
    "empty": "Enter an email address to generate the QR code.",
    "title": "Free Email QR Code Generator | Pre-filled Subject and Message — SmartQRCraft",
    "description": "Create a free email QR code with a pre-filled address, subject and message. People scan and a new email opens ready to send. PNG or SVG, no signup.",
    "og_title": "Free Email QR Code Generator | SmartQRCraft",
    "og_description": "A QR code that opens a ready-to-send email. Free, no signup, PNG or SVG.",
    "h1": 'Free <span class="accent">Email QR Code</span> Generator',
    "lead": "Add an email address, and if you like a subject and a message. Scanning the code opens a new email in the person's mail app, already filled in and ready to send.",
    "faq_h2": "Email QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make an email QR code",
         "steps": [
             "Enter the address that should receive the email.",
             "Add a subject, for example &quot;Quote request&quot; or &quot;Feedback: table 12&quot;, so you can sort replies easily.",
             "Optionally add a message. Keep it short; the sender can still edit it before sending.",
             "Style the code, then download PNG or SVG.",
             _test(),
         ]},
        {"kind": "prose", "id": "how-it-works", "h2": "How an email QR code works",
         "p": ["The code stores a standard <code>mailto:</code> link with the subject and message attached. When scanned, the phone opens its default mail app with everything filled in. Nothing is sent until the person taps Send.",
               "The person needs a mail app set up on their phone. Most people have one, but for audiences that may not, a <a href=\"index.html#generator\">link to a contact form</a> is a safe alternative."]},
        {"kind": "table", "h2": "Subject line ideas",
         "p": ["A fixed subject line tells you exactly where an email came from."],
         "cols": ["Where the code is", "Subject line", "Why"],
         "rows": [
             ["Product packaging", "Support: model X200", "Routes to the right team"],
             ["Restaurant table", "Feedback: table 12", "Know which table wrote in"],
             ["Job fair stand", "CV for the marketing role", "Easy to filter applications"],
             ["Printed catalogue", "Quote request: catalogue 2026", "Measures which print piece works"],
             ["Event poster", "Sign me up: open day", "Simple sign-up list"],
         ]},
        {"kind": "prose", "id": "tips", "h2": "Tips",
         "bullets": [
             "<strong>Use a shared inbox</strong> such as hello@ or support@, not a personal address that may change.",
             "<strong>Long messages make dense codes.</strong> A short subject and one line of text keep the code easy to scan.",
             "<strong>Tell people what happens:</strong> &quot;Scan to email us&quot; under the code sets the right expectation.",
         ]},
    ],
    "faq": [
        ("How do I create a QR code for an email address?",
         "Enter the address, and optionally a subject and message, in the generator above. Download the code; scanning it opens a new email."),
        ("Does the email send automatically?",
         "No. The mail app opens with the email ready, and the person decides whether to send it."),
        ("Can I pre-fill the subject and body?",
         "Yes. Both are optional fields in the generator."),
        ("Why does nothing happen on some phones?",
         "The phone needs a default mail app. If none is set up, the phone may ask which app to use or do nothing."),
        ("Is it free and does it expire?",
         "It is free, has no watermark and never expires, because the email details are stored in the code itself."),
    ],
    "related": [
        ("phone-qr-code-generator.html", "Phone call QR code generator"),
        ("sms-qr-code-generator.html", "SMS QR code generator"),
        ("vcard-qr-code-generator.html", "vCard QR code generator"),
    ],
}

SMS = {
    "slug": "sms-qr-code-generator.html",
    "crumb": "SMS QR Code Generator",
    "type": "sms",
    "tool_name": "SMS QR Code Generator",
    "field_label": "Mobile number",
    "field_placeholder": "+1 555 123 4567",
    "cta": "TEXT US",
    "empty": "Enter a mobile number to generate the QR code.",
    "title": "Free SMS QR Code Generator | Text Message QR Code — SmartQRCraft",
    "description": "Make a free SMS QR code: scanning opens a text message to your number with a pre-written message. Great for opt-ins, feedback and orders. No signup.",
    "og_title": "Free SMS QR Code Generator | SmartQRCraft",
    "og_description": "A QR code that opens a ready-to-send text message. Free, no signup, PNG or SVG.",
    "h1": 'Free <span class="accent">SMS QR Code</span> Generator',
    "lead": "Enter a mobile number and an optional message. Scanning the code opens the phone's messaging app with the text ready to send to you.",
    "faq_h2": "SMS QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make a text message QR code",
         "steps": [
             "Type the mobile number with its country code.",
             "Write a short message, for example a keyword such as &quot;JOIN&quot; or &quot;Book a table for Friday&quot;.",
             "Choose colors and a frame like &quot;Text us&quot;, then download.",
             _test(),
         ]},
        {"kind": "prose", "id": "how-it-works", "h2": "How it works",
         "p": ["The code uses the widely supported <code>SMSTO:</code> format, which holds a number and a message. The person's messaging app opens with both filled in, and nothing is sent until they tap Send. Normal text message charges from their carrier apply."]},
        {"kind": "cards", "eyebrow": "Ideas", "h2": "What people use SMS QR codes for",
         "cards": [
             ("Text-to-join lists", "A keyword like JOIN starts an SMS marketing opt-in, if your SMS provider supports keywords."),
             ("Quick feedback", "&quot;Rate your visit 1 to 5&quot; on a receipt or table card."),
             ("Orders &amp; bookings", "Customers text a pre-written order or booking request."),
             ("Support requests", "A code on a device texts the support line with the model number included."),
             ("Contests &amp; votes", "Each option gets its own code with a different message."),
             ("Real estate", "&quot;Send me details for 12 Oak Lane&quot; on a yard sign."),
         ]},
        {"kind": "prose", "id": "rules", "h2": "Before you use SMS for marketing",
         "p": ["If you use texts for marketing, the person must agree to receive messages and must be able to opt out. Rules differ by country, for example the TCPA in the US and PECR in the UK. The QR code itself only starts a message the person chooses to send; what you do with the number afterwards is where the rules apply."]},
    ],
    "faq": [
        ("How do I make a QR code that sends a text?",
         "Enter the number and a message above, then download the code. Scanning it opens a text message ready to send."),
        ("Does the text send automatically?",
         "No. The person always taps Send themselves."),
        ("Does it work on iPhone?",
         "Yes. The iPhone camera and Android phones both recognise SMS QR codes."),
        ("Can I leave the message empty?",
         "Yes. The code then opens a blank text to your number."),
        ("Can I use it for WhatsApp instead?",
         "Use a WhatsApp QR code for that, which opens a WhatsApp chat rather than a text message."),
        ("Is it free?",
         "Yes, free, no signup and no expiry."),
    ],
    "related": [
        ("phone-qr-code-generator.html", "Phone call QR code generator"),
        ("email-qr-code-generator.html", "Email QR code generator"),
        ("telegram-qr-code-generator.html", "Telegram QR code generator"),
    ],
}

TEXT = {
    "slug": "text-qr-code-generator.html",
    "crumb": "Text QR Code Generator",
    "type": "text",
    "tool_name": "Text QR Code Generator",
    "field_label": "Your text",
    "field_placeholder": "Type any message, code or note...",
    "cta": "SCAN ME",
    "empty": "Type some text to generate the QR code.",
    "title": "Free Text to QR Code Generator | Plain Text QR Code — SmartQRCraft",
    "description": "Convert any text to a QR code for free. Messages, codes, serial numbers or instructions that show on screen when scanned. Works offline, no signup.",
    "og_title": "Free Text to QR Code Generator | SmartQRCraft",
    "og_description": "Turn plain text into a QR code that works offline. Free, no signup.",
    "h1": 'Free <span class="accent">Text to QR Code</span> Generator',
    "lead": "Type any text and turn it into a QR code. When scanned, the text appears on the phone's screen. No internet connection is needed to read it.",
    "faq_h2": "Text QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to turn text into a QR code",
         "steps": [
             "Type or paste your text into the box.",
             "Watch the preview: the more text, the denser the code.",
             "Download PNG or SVG.",
             "Scan it once to check the text shows correctly, including any special characters.",
         ]},
        {"kind": "table", "h2": "How much text fits?",
         "p": ["A QR code can technically hold a few thousand characters, but dense codes are hard to scan. As a rule of thumb:"],
         "cols": ["Text length", "Result"],
         "rows": [
             ["Up to about 100 characters", "Simple code, scans easily even small"],
             ["100 to 300 characters", "Fine at normal print sizes"],
             ["300 to 1,000 characters", "Dense; print larger and test carefully"],
             ["More than 1,000", "Not recommended. Put the text on a web page and link to it instead"],
         ]},
        {"kind": "cards", "eyebrow": "Ideas", "h2": "Uses for text QR codes",
         "cards": [
             ("Offline instructions", "Steps or safety notes that work without mobile data."),
             ("Serial &amp; asset numbers", "Scan instead of typing long codes."),
             ("Hidden messages", "Treasure hunts, puzzles and gifts."),
             ("Classroom activities", "Questions and answers students scan."),
             ("Event info", "A door code or schedule on a badge."),
             ("Voucher codes", "A code people copy at checkout."),
         ]},
        {"kind": "prose", "id": "privacy", "h2": "Is the text private?",
         "p": ["The text is written into the image itself, so anyone who scans the code can read it. Do not put passwords or personal data in a text code that others might see. This generator runs in your browser, so the text is not sent to our server."]},
    ],
    "faq": [
        ("How do I convert text to a QR code?",
         "Type the text into the box above and download the code. Scanning it shows the text."),
        ("Does a text QR code need the internet?",
         "No. The text is stored in the code, so any scanner can read it offline."),
        ("What is the maximum text length?",
         "Several thousand characters in theory, but keep it under about 300 for reliable scanning."),
        ("Can I use other languages and emoji?",
         "Yes. The code stores text as UTF-8, so most languages work. Test with the phones your audience uses."),
        ("Can I edit the text later?",
         "No. The text is part of the code, so a change needs a new code."),
    ],
    "related": [
        ("what-is-a-qr-code.html", "What is a QR code?"),
        ("qr-code-scanner.html", "QR code scanner"),
        ("bulk-qr-code-generator.html", "Bulk QR code generator"),
    ],
}

APP = {
    "slug": "app-store-qr-code-generator.html",
    "crumb": "App Store QR Code Generator",
    "type": "app",
    "tool_name": "App Download QR Code Generator",
    "field_label": "App Store or Google Play link",
    "field_placeholder": "https://apps.apple.com/app/yourapp",
    "cta": "GET THE APP",
    "empty": "Paste your App Store or Google Play link.",
    "title": "Free App Store QR Code Generator | App Download QR Code — SmartQRCraft",
    "description": "Make a free app download QR code for the Apple App Store or Google Play. Tips for reaching iPhone and Android users with one code. PNG or SVG, no signup.",
    "og_title": "Free App Download QR Code Generator | SmartQRCraft",
    "og_description": "A QR code that opens your app in the App Store or Google Play. Free, no signup.",
    "h1": 'Free <span class="accent">App Download QR Code</span> Generator',
    "lead": "Paste your App Store or Google Play link and download a QR code. Scanning it opens your app's store page, one tap away from installing.",
    "faq_h2": "App QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make an app download QR code",
         "steps": [
             "Open your app's page in the App Store or Google Play and copy the link.",
             "Paste it above and choose a frame such as &quot;Get the app&quot;.",
             "Download PNG or SVG, and test it on the matching phone type.",
         ]},
        {"kind": "table", "h2": "One code for iPhone and Android?",
         "p": ["A store link opens only its own store. An App Store link on an Android phone opens a web page, not Google Play. Here are your options:"],
         "cols": ["Option", "How it works", "Good for"],
         "rows": [
             ["Two codes side by side", "One labelled App Store, one labelled Google Play", "Print where there is room; no setup"],
             ["A download page on your site", "One code links to yourapp.com/download, which shows both badges or detects the phone", "One code, full control, works forever"],
             ["A single store", "If almost all your users are on one platform", "Simple, but excludes the others"],
         ]},
        {"kind": "prose", "id": "download-page", "h2": "Best practice: link to your own download page",
         "p": ["Making a static code of <strong>yourapp.com/download</strong> means the printed code never breaks, even if your store links change. That page can show both store badges, or a developer can redirect automatically based on the visitor's device."]},
        {"kind": "cards", "eyebrow": "Where to Use It", "h2": "Where app QR codes work",
         "cards": [
             ("Packaging &amp; manuals", "Companion apps for devices and products."),
             ("Shop counters", "Loyalty and ordering apps."),
             ("Websites on desktop", "Visitors scan from the screen to install on their phone."),
             ("Events", "Event apps and schedules."),
             ("Restaurants", "Order and pay apps on tables."),
             ("Print ads", "Magazines, posters and flyers."),
         ]},
    ],
    "faq": [
        ("How do I create a QR code for my app?",
         "Copy your app's App Store or Google Play link, paste it into the generator above and download the code."),
        ("Can one QR code open the right store on each phone?",
         "Not with a plain store link. Use two codes, or link to a download page on your website that shows both stores or redirects by device."),
        ("Is the app QR code free?",
         "Yes. It is free, with no signup and no expiry."),
        ("What if my store link changes?",
         "A static code keeps pointing to the old link. Linking to your own download page avoids this."),
        ("Can I add my app icon in the middle?",
         "Yes. Turn on Center Logo and upload your icon as a square PNG."),
    ],
    "related": [
        ("static-vs-dynamic-qr-codes.html", "Static vs dynamic QR codes"),
        ("qr-code-with-logo.html", "QR code with logo"),
        ("index.html#generator", "Free QR code generator"),
    ],
}

TELEGRAM = {
    "slug": "telegram-qr-code-generator.html",
    "crumb": "Telegram QR Code Generator",
    "type": "telegram",
    "tool_name": "Telegram QR Code Generator",
    "field_label": "Telegram username, channel or group",
    "field_placeholder": "@yourname",
    "cta": "CHAT ON TELEGRAM",
    "empty": "Enter a Telegram username to generate the QR code.",
    "title": "Free Telegram QR Code Generator | Chat, Channel or Group — SmartQRCraft",
    "description": "Create a free Telegram QR code for your username, channel, group or bot. Scanning opens Telegram straight to you. Custom design, PNG or SVG, no signup.",
    "og_title": "Free Telegram QR Code Generator | SmartQRCraft",
    "og_description": "A QR code that opens your Telegram chat, channel or group. Free, no signup.",
    "h1": 'Free <span class="accent">Telegram QR Code</span> Generator',
    "lead": "Enter a Telegram username, channel, group or bot. Scanning the code opens Telegram right on that chat, so people can message or join in one step.",
    "faq_h2": "Telegram QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make a Telegram QR code",
         "steps": [
             "Find your public username in Telegram under Settings (it starts with @). For a channel or group, use its public link name.",
             "Type it above, with or without the @. You can also paste a t.me link.",
             "Optionally add a message that is pre-filled when someone opens a chat with you.",
             "Style the code, download it and test it with Telegram installed.",
         ]},
        {"kind": "table", "h2": "What you can link to",
         "cols": ["Link to", "What people see", "Needs"],
         "rows": [
             ["Your personal username", "A chat with you", "A public username set in Settings"],
             ["A public channel", "The channel with a Join button", "The channel's public link name"],
             ["A public group", "The group with a Join button", "The group's public link name"],
             ["A bot", "The bot with a Start button", "The bot's username (ends in bot)"],
         ]},
        {"kind": "prose", "id": "private", "h2": "Private groups and invite links",
         "p": ["Private groups use invite links such as t.me/+AbCdEf. Paste the full invite link into the <a href=\"index.html#generator\">URL generator</a> instead. Anyone with the code can join, so treat it like the invite link itself, and revoke the link in Telegram if it leaks."]},
        {"kind": "prose", "id": "tips", "h2": "Tips",
         "bullets": [
             "<strong>Usernames must be public.</strong> Without a username, a QR code cannot open a chat with you.",
             "<strong>Telegram also has built-in QR codes</strong> for profiles, but they cannot be restyled or given your logo. This page lets you design and print your own.",
             "<strong>Pre-filled messages</strong> work on recent Telegram versions; older apps just open the chat.",
         ]},
    ],
    "faq": [
        ("How do I create a QR code for Telegram?",
         "Type your Telegram username, channel or group above and download the code. Scanning it opens Telegram on that chat."),
        ("Does it work for Telegram channels and groups?",
         "Yes, for public ones. For private groups, make a code of the invite link with the URL generator."),
        ("What if the person does not have Telegram?",
         "The link opens a Telegram web page that offers to install the app or open Telegram Web."),
        ("Can I pre-fill a message?",
         "Yes, for chats with a user or bot. Channels and groups ignore it."),
        ("Is it free?",
         "Yes. No signup, no watermark, no expiry."),
    ],
    "related": [
        ("whatsapp-qr-code-generator.html", "WhatsApp QR code generator"),
        ("discord-qr-code-generator.html", "Discord QR code generator"),
        ("sms-qr-code-generator.html", "SMS QR code generator"),
    ],
}

X_PAGE = {
    "slug": "twitter-x-qr-code-generator.html",
    "crumb": "X (Twitter) QR Code Generator",
    "type": "x",
    "tool_name": "X (Twitter) QR Code Generator",
    "field_label": "Your X username",
    "field_placeholder": "@yourname",
    "cta": "FOLLOW US",
    "empty": "Enter an X username to generate the QR code.",
    "title": "Free X (Twitter) QR Code Generator | Profile or Pre-filled Post — SmartQRCraft",
    "description": "Make a free X (Twitter) QR code that opens your profile or starts a pre-filled post. Custom colors and logo, PNG or SVG download. No signup.",
    "og_title": "Free X (Twitter) QR Code Generator | SmartQRCraft",
    "og_description": "A QR code for your X profile, or one that starts a post. Free, no signup.",
    "h1": 'Free <span class="accent">X (Twitter) QR Code</span> Generator',
    "lead": "Enter your X username to make a code that opens your profile, or write a post so people who scan can share it in one tap.",
    "faq_h2": "X (Twitter) QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make an X QR code",
         "steps": [
             "Type your username, with or without the @.",
             "Or, to get people posting, write a pre-filled post with your hashtag or event name. This replaces the profile link.",
             "Choose colors and a frame such as &quot;Follow us&quot;, then download.",
             _test(),
         ]},
        {"kind": "table", "h2": "Profile code or post code?",
         "cols": ["Type", "What happens", "Best for"],
         "rows": [
             ["Profile", "Opens x.com/yourname, with a Follow button", "Cards, packaging, signatures"],
             ["Pre-filled post", "Opens a new post with your text and hashtag", "Events, contests, product launches"],
         ]},
        {"kind": "prose", "id": "tips", "h2": "Tips",
         "bullets": [
             "<strong>Use one hashtag.</strong> A short post with a single tag is more likely to be shared unchanged.",
             "<strong>People can edit the post</strong> before they share it, and nothing is posted without them.",
             "<strong>Links still say twitter.com in some places.</strong> Both x.com and twitter.com addresses open the same profile.",
         ]},
    ],
    "faq": [
        ("How do I make a QR code for my X profile?",
         "Type your username above and download the code. Scanning it opens your profile."),
        ("Can a QR code open a pre-written post?",
         "Yes. Fill in the pre-filled post field. The person sees the post and chooses whether to share it."),
        ("Does it still work with Twitter links?",
         "Yes. X and Twitter addresses lead to the same place."),
        ("Is it free?",
         "Yes, free with no signup and no expiry."),
    ],
    "related": [
        ("instagram-qr-code-generator.html", "Instagram QR code generator"),
        ("facebook-qr-code-generator.html", "Facebook QR code generator"),
        ("youtube-qr-code-generator.html", "YouTube QR code generator"),
    ],
}

MECARD = {
    "slug": "mecard-qr-code-generator.html",
    "crumb": "MeCard QR Code Generator",
    "type": "mecard",
    "tool_name": "MeCard QR Code Generator",
    "field_label": "First name",
    "field_placeholder": "Alex",
    "cta": "SAVE CONTACT",
    "empty": "Enter a name to generate the QR code.",
    "title": "Free MeCard QR Code Generator | Compact Contact QR Code — SmartQRCraft",
    "description": "Create a free MeCard QR code: a compact contact card with name, phone, email and website that makes a smaller, easier-to-scan code than vCard. No signup.",
    "og_title": "Free MeCard QR Code Generator | SmartQRCraft",
    "og_description": "Compact contact QR codes in the MeCard format. Free, no signup.",
    "h1": 'Free <span class="accent">MeCard QR Code</span> Generator',
    "lead": "MeCard is a short contact format. It stores your name, number, email and website in fewer characters than vCard, so the QR code is less dense and easier to print small.",
    "faq_h2": "MeCard QR Code Questions",
    "sections": [
        {"kind": "table", "h2": "MeCard vs vCard",
         "p": ["Both formats save a contact to the phone. The difference is size and how much they can hold."],
         "cols": ["", "MeCard", "vCard"],
         "rows": [
             ["Code density", "Lower (smaller data)", "Higher"],
             ["Fields", "Name, phone, email, website, address", "Also company, job title, several numbers and more"],
             ["Support", "Most Android scanners and many apps; test on iPhone", "Very wide, including the iPhone camera"],
             ["Best for", "Tiny codes, stickers, badges", "Business cards and anything formal"],
         ]},
        {"kind": "prose", "id": "how-to", "h2": "How to make a MeCard QR code",
         "steps": [
             "Fill in your first and last name. Every other field is optional.",
             "Add a phone number with the country code, an email and a website.",
             "Download the code and scan it with both an iPhone and an Android before printing.",
         ]},
        {"kind": "prose", "id": "which", "h2": "Which one should you use?",
         "p": ["If you need a very small code, or your audience mostly uses Android, MeCard is a good fit. If you are not sure, the <a href=\"vcard-qr-code-generator.html\">vCard QR code generator</a> is the safer choice because nearly every phone camera supports it."]},
    ],
    "faq": [
        ("What is a MeCard QR code?",
         "A QR code that holds contact details in the MeCard format, a shorter alternative to vCard. Scanning it offers to save the contact."),
        ("Does MeCard work on iPhone?",
         "Support varies by iOS version and scanner app. Test it first; if it does not work for your audience, use vCard."),
        ("Why is the MeCard code smaller?",
         "The format uses short labels, so the same details take fewer characters and the code has fewer modules."),
        ("Is it free?",
         "Yes. No signup, no expiry, and the details stay in your browser."),
    ],
    "related": [
        ("vcard-qr-code-generator.html", "vCard QR code generator"),
        ("phone-qr-code-generator.html", "Phone call QR code generator"),
        ("email-qr-code-generator.html", "Email QR code generator"),
    ],
}

BITCOIN = {
    "slug": "bitcoin-qr-code-generator.html",
    "crumb": "Bitcoin QR Code Generator",
    "type": "bitcoin",
    "tool_name": "Bitcoin QR Code Generator",
    "field_label": "Bitcoin address",
    "field_placeholder": "bc1q...",
    "cta": "PAY WITH BITCOIN",
    "empty": "Enter a valid Bitcoin address to generate the QR code.",
    "title": "Free Bitcoin QR Code Generator | BTC Payment QR with Amount — SmartQRCraft",
    "description": "Make a free Bitcoin QR code from your BTC address with an optional amount, label and message (BIP21). Wallets read it instantly. Private, runs in your browser.",
    "og_title": "Free Bitcoin QR Code Generator | SmartQRCraft",
    "og_description": "Create a BIP21 Bitcoin payment QR code with amount and label. Free and private.",
    "h1": 'Free <span class="accent">Bitcoin QR Code</span> Generator',
    "lead": "Paste your Bitcoin address, and optionally an amount, label and message. The code uses the standard bitcoin: format (BIP21) that wallet apps read.",
    "faq_h2": "Bitcoin QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make a Bitcoin payment QR code",
         "steps": [
             "Copy a <strong>receive address</strong> from your wallet. Addresses start with bc1, 1 or 3.",
             "Paste it above. The code only appears when the address format is valid.",
             "Optionally set an amount in BTC and a label such as your shop name.",
             "Download the code, then scan it with your own wallet to check the address matches <strong>character by character</strong> before you share it.",
         ]},
        {"kind": "table", "h2": "What the fields do",
         "cols": ["Field", "Effect in the payer's wallet"],
         "rows": [
             ["Address", "Where the Bitcoin is sent. Required."],
             ["Amount", "Pre-fills the amount in BTC. The payer can usually change it."],
             ["Label", "Shows who is being paid, for example a shop name."],
             ["Message", "A note, such as an order number."],
         ]},
        {"kind": "prose", "id": "safety", "h2": "Safety notes",
         "bullets": [
             "<strong>Always verify the address</strong> after scanning your own code. A wrong character sends funds that cannot be recovered.",
             "<strong>Watch for stickers over your code.</strong> Scammers sometimes paste their own code over a public one.",
             "<strong>This page never sees your keys.</strong> A receive address is public information; never put a private key or seed phrase in a QR code.",
             "<strong>Lightning invoices are different.</strong> This generator makes on-chain BIP21 codes only.",
         ]},
    ],
    "faq": [
        ("How do I create a Bitcoin QR code?",
         "Paste your Bitcoin receive address above, optionally add an amount, and download the code."),
        ("Which wallets can read it?",
         "Most Bitcoin wallets read BIP21 codes. Support for the label and message fields varies."),
        ("Can I include an amount?",
         "Yes, in BTC with up to 8 decimal places. Leave it blank so the payer enters the amount."),
        ("Is it safe to share my Bitcoin address as a QR code?",
         "A receive address is meant to be shared. Some people use a new address for each payment for privacy; many wallets do this automatically."),
        ("Do you store my address?",
         "No. The code is created in your browser and nothing is sent to our server."),
        ("Can I use this for other cryptocurrencies?",
         "No. It checks for Bitcoin address formats only. Sending another coin to a Bitcoin address can lose the funds."),
    ],
    "related": [
        ("paypal-qr-code-generator.html", "PayPal QR code generator"),
        ("qr-code-safety.html", "QR code safety guide"),
        ("index.html#generator", "Free QR code generator"),
    ],
}

TYPES_SHARED = [PHONE, EMAIL, SMS, TEXT, APP, TELEGRAM, X_PAGE, MECARD, BITCOIN]
