"""Pillar guides and industry pages (English, shared on .com/.co.uk/.in). Article template: static + indexable."""


def _cta(h2, p, href, label):
    return {"kind": "cta", "h2": h2, "p": p, "href": href, "label": label}


_ART = {"static": True, "noindex": False, "type": "url"}

WHAT_IS = {**_ART,
    "slug": "what-is-a-qr-code.html",
    "crumb": "What Is a QR Code?",
    "title": "What Is a QR Code? How It Works, Types and Uses",
    "description": "A QR code is a square pattern that stores text or a link a phone camera can read. Learn how QR codes work, their parts, types, capacity and safe uses.",
    "og_title": "What Is a QR Code? How It Works | SmartQRCraft",
    "og_description": "How QR codes work, what is inside them, what types exist and how to use them well.",
    "h1": "What Is a QR Code and How Does It Work?",
    "lead": "A QR code is a square pattern of black and white modules that stores information, most often a web link, in a form a phone camera can read in a moment.",
    "faq_h2": "QR Code Basics",
    "sections": [
        {"kind": "prose", "id": "definition", "h2": "The short answer",
         "p": [
             "QR stands for Quick Response. A QR code is a two-dimensional barcode: instead of a row of bars read left to right, it stores data in a grid of small squares, which lets it hold far more than an ordinary barcode. Pointing a phone camera at the pattern turns it back into text, such as a web address, a WiFi login, a phone number or a contact card.",
             "The code itself is only a container. What happens next depends on what is inside: a link opens in the browser, a WiFi code offers to join a network, a contact code offers to save the person. Most current phones read QR codes with the ordinary camera app, without an extra app."]},
        {"kind": "prose", "id": "history", "h2": "Where QR codes came from",
         "p": [
             "QR codes were created in 1994 by Denso Wave, a Japanese company in the Toyota group, to track car parts on assembly lines. Ordinary barcodes held too little data and were slow to scan from an angle. The company chose to leave the specification open, which is a big reason QR codes spread so widely. The format is described in the international standard ISO/IEC 18004."]},
        {"kind": "prose", "id": "how-it-works", "h2": "How a QR code works",
         "p": ["A scanner does not look at a QR code like a picture. It finds specific patterns, reads the grid and applies error correction."],
         "steps": [
             "The camera finds the <strong>three large squares</strong> in the corners. These finder patterns tell the scanner where the code is, how big it is and which way it is rotated.",
             "It reads the <strong>timing and alignment patterns</strong> that keep the grid straight, even when the code is on a curved or tilted surface.",
             "It reads <strong>format information</strong> that says which error correction level and mask were used.",
             "It reads the dark and light modules as bits and turns them back into data.",
             "It uses <strong>error correction</strong> to repair any parts that are dirty, damaged or hidden."]},
        {"kind": "table", "h2": "Parts of a QR code",
         "p": ["Every QR code has the same building blocks."],
         "cols": ["Part", "What it does"],
         "rows": [
             ["Finder patterns (three corner squares)", "Show the scanner where the code is and how it is rotated"],
             ["Alignment pattern", "Helps correct distortion in larger codes"],
             ["Timing patterns", "Alternating modules that define the grid"],
             ["Format and version information", "Store the error correction level and the code size"],
             ["Data and error correction modules", "Hold your content and the extra data used for repair"],
             ["Quiet zone", "The blank margin around the code, at least four modules wide in the specification"]]},
        {"kind": "table", "h2": "How much can a QR code hold?",
         "p": ["Capacity depends on the size of the grid and the error correction level. QR codes come in 40 sizes called versions, from version 1 (21 by 21 modules) to version 40 (177 by 177 modules). At the largest size with the lowest error correction, a code can hold the following."],
         "cols": ["Type of data", "Maximum characters (version 40, lowest error correction)"],
         "rows": [["Numbers only", "7,089"], ["Letters, numbers and a few symbols", "4,296"], ["Any text (bytes)", "2,953"]]},
        {"kind": "prose", "id": "error-correction", "h2": "Error correction: why damaged codes still scan",
         "p": ["QR codes carry extra data so a scanner can rebuild missing parts. There are four levels, and a higher level survives more damage but needs a denser, larger pattern."],
         "bullets": [
             "<strong>L (low):</strong> repairs roughly 7% of the code.",
             "<strong>M (medium):</strong> roughly 15%. A common default.",
             "<strong>Q (quartile):</strong> roughly 25%.",
             "<strong>H (high):</strong> roughly 30%. Used when a logo covers the center."],
         "after": ["This is why a small logo in the middle of a QR code can still scan, and why it must stay small."]},
        {"kind": "cards", "eyebrow": "Types", "h2": "What a QR code can contain",
         "cards": [
             ("Web link", "The most common use. Opens a page in the browser. Try the <a href=\"index.html#generator\">QR code generator</a>."),
             ("WiFi login", "Lets guests join a network without typing a password."),
             ("Contact card", "A vCard that saves a name, number and email. See <a href=\"vcard-qr-code-generator.html\">vCard QR codes</a>."),
             ("Email, phone or SMS", "Starts a message or call with details filled in."),
             ("Location", "Opens a place in a maps app."),
             ("Calendar event", "Adds an event to a calendar."),
             ("Payment details", "Some regions use QR codes for payments, such as UPI in India or the GiroCode in Europe."),
             ("Plain text", "Any text, such as a code or short note.")]},
        {"kind": "prose", "id": "static-dynamic", "h2": "Static and dynamic QR codes",
         "p": ["A static code has its content built into the pattern. A dynamic code contains a short link to a service that redirects to the real destination, which lets the destination change later and lets the service count scans. Read the full comparison in <a href=\"static-vs-dynamic-qr-codes.html\">static vs dynamic QR codes</a>."]},
        _cta("Make your own QR code", "Create a free QR code in seconds. No signup, no watermark.", "index.html#generator", "Open the generator"),
        {"kind": "prose", "id": "using-well", "h2": "How to use QR codes well",
         "p": ["A QR code is only useful if people scan it and land somewhere worthwhile."],
         "bullets": [
             "<strong>Say what it does.</strong> A short call to action such as &quot;Scan for the menu&quot; beats a bare code.",
             "<strong>Print it large enough.</strong> Read the <a href=\"qr-code-size-guide.html\">QR code size guide</a>.",
             "<strong>Keep contrast high.</strong> Dark code on a light background is safest.",
             "<strong>Send people to a mobile-friendly page.</strong>",
             "<strong>Test before you print,</strong> with the <a href=\"qr-code-tester.html\">QR code tester</a> and two real phones.",
             "<strong>Be careful what you scan.</strong> See <a href=\"qr-code-safety.html\">how to check a QR code is safe</a>."]},
    ],
    "faq": [
        ("What does QR stand for?", "QR stands for Quick Response. The name reflects the goal of the original design, which was to be read quickly."),
        ("Who invented the QR code?", "Denso Wave, a Japanese company, created the QR code in 1994 to track car parts in factories."),
        ("How do I scan a QR code?", "Open your phone's camera app and point it at the code. Most current iPhones and Android phones show a link or an action. You can also use the <a href=\"qr-code-scanner.html\">online QR code scanner</a> with an image or a webcam."),
        ("Do QR codes expire?", "A static QR code never expires because its content is inside the pattern. It can stop being useful if the page it points to disappears. Dynamic codes can stop working if the service or subscription ends."),
        ("Are QR codes safe?", "Scanning a code only reads its text. Risk comes from what you do next, such as opening a link or approving a payment. Check the destination first."),
        ("What is the difference between a QR code and a barcode?", "A traditional barcode stores a short number in a row of bars and is read by a scanner in a checkout. A QR code stores much more data in a square grid and is read by phone cameras. See the <a href=\"barcode-generator.html\">barcode generator</a> for the other format."),
        ("Can I make a QR code for free?", "Yes. Static QR codes are free to make on this site with no signup and no watermark."),
    ],
    "related": [("static-vs-dynamic-qr-codes.html", "Static vs dynamic QR codes"), ("qr-code-safety.html", "QR code safety guide"), ("qr-code-size-guide.html", "QR code size guide")],
}

STATIC_DYNAMIC = {**_ART,
    "slug": "static-vs-dynamic-qr-codes.html",
    "crumb": "Static vs Dynamic QR Codes",
    "title": "Static vs Dynamic QR Codes: Differences and Which to Use",
    "description": "Static QR codes hold the content directly and never expire. Dynamic codes redirect and can be edited and tracked. Compare costs, risks and when to use each.",
    "og_title": "Static vs Dynamic QR Codes | SmartQRCraft",
    "og_description": "The real differences between static and dynamic QR codes, and how to choose.",
    "h1": "Static vs Dynamic QR Codes: What Is the Difference?",
    "lead": "The difference is where the destination lives. A static code contains it. A dynamic code points to a service that decides where to send people, which is why it can be edited and tracked.",
    "faq_h2": "Static and Dynamic QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "quick", "h2": "The quick answer",
         "p": [
             "A <strong>static</strong> QR code stores your content, for example a web address, directly in the pattern. Once it is made, it cannot be changed, it needs no server and it works as long as the destination does.",
             "A <strong>dynamic</strong> QR code stores a short link to a redirect service. When someone scans it, the service forwards them to your real destination. You can change that destination later and often see how many people scanned."]},
        {"kind": "table", "h2": "Side by side",
         "p": ["Here is how the two compare on the things that matter."],
         "cols": ["", "Static QR code", "Dynamic QR code"],
         "rows": [
             ["Where the content lives", "Inside the pattern", "At a redirect service, the code holds a short link"],
             ["Edit after printing", "No", "Yes, change the destination"],
             ["Scan tracking", "No", "Yes, through the service"],
             ["Cost", "Free", "Usually a subscription after a small free allowance"],
             ["Depends on a company", "No", "Yes. If the service or plan ends, the code can stop working"],
             ["Pattern complexity", "Grows with the content", "Always simple, because the link is short"],
             ["Privacy", "Nobody sees your scans", "The service can see scan data"],
             ["Works offline (for text, WiFi, contacts)", "Yes", "No, it needs a redirect"]]},
        {"kind": "prose", "id": "static-when", "h2": "When a static QR code is the right choice",
         "p": ["Static codes suit anything that does not need to change or be counted."],
         "bullets": [
             "WiFi details, contact cards, plain text and calendar events, which are stored in the code itself.",
             "Links to pages you control, such as your website, menu, portfolio or social profile.",
             "Business cards, stickers and packaging where you do not want to depend on a subscription.",
             "Situations where you want a code to work for years without paying anyone."]},
        {"kind": "prose", "id": "dynamic-when", "h2": "When a dynamic QR code makes sense",
         "p": ["Dynamic codes earn their cost when you need flexibility or measurement."],
         "bullets": [
             "Large print runs where the destination might change, such as posters, packaging or campaigns.",
             "Marketing where you want to know how many people scanned, and when.",
             "Testing different landing pages.",
             "Cases where a printed mistake would be expensive to fix."]},
        {"kind": "prose", "id": "risks", "h2": "Risks of dynamic codes to know about",
         "p": ["The flexibility comes with trade-offs."],
         "bullets": [
             "<strong>Dependence.</strong> If you stop paying, or the company closes, the codes you printed may stop working or show an ad.",
             "<strong>Free plans can be short.</strong> Some services allow only a few dynamic codes, or free codes that expire.",
             "<strong>An extra hop.</strong> The scan goes through a redirect, which adds a delay and a point of failure.",
             "<strong>Privacy.</strong> The service records scans and can see device information.",
             "<strong>Lock-in.</strong> Codes are tied to the provider's short links, so you cannot easily move them to another service."]},
        {"kind": "prose", "id": "diy", "h2": "A simple alternative: make your own redirect",
         "p": [
             "You can get most of the flexibility of a dynamic code without a subscription. Choose a short address on a domain you own, for example yourbrand.com/menu. Point that address at your real page, and make a <strong>static</strong> QR code of the short address. If the destination changes later, you update where yourbrand.com/menu points, and the printed code keeps working.",
             "This depends only on your own domain, not on a QR code company. It does not give scan counts, but your website analytics can count visits to the short address."]},
        _cta("Make a static QR code for free", "No signup, no watermark, and it never expires.", "index.html#generator", "Open the generator"),
        {"kind": "prose", "id": "choose", "h2": "How to choose",
         "p": ["Ask three questions:"],
         "steps": [
             "<strong>Might the destination change after printing?</strong> If yes, use a dynamic code or your own redirect.",
             "<strong>Do I need scan counts?</strong> If yes, dynamic. If not, static is enough.",
             "<strong>Am I comfortable depending on a company for years?</strong> If not, choose static or your own redirect."]},
    ],
    "faq": [
        ("Is a QR code static or dynamic by default?", "It depends on the tool. Codes that hold your content directly are static. Codes that use a short link from a service are dynamic. On this site all codes are static."),
        ("Can I convert a static QR code into a dynamic one?", "No. The pattern is fixed. You would create a new dynamic code, or point the old code at a short link you control."),
        ("Do static QR codes expire?", "No. They keep working as long as their destination works."),
        ("Are dynamic QR codes free?", "Usually only a few, or for a limited time. Long-term or unlimited dynamic codes are normally part of a paid plan."),
        ("Do dynamic QR codes work if I stop paying?", "Often not. The redirect may stop or show a notice, so check the provider's terms before printing."),
        ("Which is better for a restaurant menu?", "A static code that points to a stable menu page you control. Update the page, not the code. See the <a href=\"qr-code-menu-generator.html\">QR code menu guide</a>."),
    ],
    "related": [("what-is-a-qr-code.html", "What is a QR code?"), ("qr-code-safety.html", "QR code safety guide"), ("qr-code-menu-generator.html", "QR code menu generator")],
}

SAFETY = {**_ART,
    "slug": "qr-code-safety.html",
    "crumb": "QR Code Safety",
    "title": "Are QR Codes Safe? How to Spot QR Code Scams",
    "description": "Scanning a QR code only reads text, but the link or payment that follows can be a scam. Learn how QR phishing works and how to check a code before you open it.",
    "og_title": "Are QR Codes Safe? QR Code Scams | SmartQRCraft",
    "og_description": "How QR code scams work, the warning signs, and a simple checklist before you scan.",
    "h1": "Are QR Codes Safe? How to Spot QR Code Scams",
    "lead": "Scanning a QR code is not dangerous by itself. The risk is what the code sends you to, and criminals count on you not checking. Here is how QR scams work and how to stay safe.",
    "faq_h2": "QR Code Safety Questions",
    "sections": [
        {"kind": "prose", "id": "short", "h2": "The short answer",
         "p": [
             "A QR code is just text stored in a pattern. When your camera scans it, it reads that text and offers an action, usually opening a link. Nothing harmful happens in the scan itself. The danger comes from the next step: opening a fake website, entering a password, approving a payment or installing something.",
             "Security researchers call QR code phishing <strong>quishing</strong>. Consumer protection and law enforcement agencies, including the FTC in the US and the FBI, have published warnings about it."]},
        {"kind": "prose", "id": "fake", "h2": "What is a fake QR code?",
         "p": ["A fake QR code is a code made by a scammer to look like a real one. It sends you to a copy of a genuine website, a fake payment page or a harmful download instead of where you expect. Many fake codes are printed stickers placed over the real code on a parking machine, poster or menu, so they look official."]},
        {"kind": "table", "h2": "Where fake QR codes turn up",
         "cols": ["Place", "What the scam usually wants"],
         "rows": [
             ["Car parks and parking machines", "Your card details, through a fake parking payment page"],
             ["EV chargers, bike and scooter hire", "Card details or an account login"],
             ["Restaurant tables and menus", "Card details at &quot;checkout&quot;"],
             ["Posters, bus stops and stations", "Logins, prize or survey scams"],
             ["Letters and parcels you did not expect", "Delivery fees, account or bank details"],
             ["Emails and texts claiming to be from a bank, tax office or delivery firm", "Passwords and one-time codes; the code dodges email link filters"],
             ["Fake parking fines or penalty notices", "A quick &quot;fine&quot; payment to the scammer"],
         ]},
        {"kind": "prose", "id": "how-scams-work", "h2": "How QR code scams work",
         "p": ["These are the common patterns."],
         "bullets": [
             "<strong>Sticker overlays.</strong> A fake code is stuck over a real one on a parking meter, poster, menu or restaurant table, sending payments or logins to a criminal.",
             "<strong>Unexpected mail or packages.</strong> A letter or parcel with a QR code that asks you to confirm a delivery, a payment or an account.",
             "<strong>Fake urgency in email.</strong> An email with a QR code says your account is locked or a payment failed. Because it is an image, some email filters do not read it.",
             "<strong>Fake support or login pages.</strong> The link goes to a page that looks like your bank or a well-known brand and asks for a password or card.",
             "<strong>Payment swaps.</strong> A code is replaced with the scammer's payment details. Someone tells you to scan to receive money, but scanning in a payment app sends money out.",
             "<strong>Malicious apps.</strong> A code leads to a download that is not from the official app store."]},
        {"kind": "table", "h2": "Warning signs at a glance",
         "p": ["Any one of these is a reason to pause."],
         "cols": ["Sign", "Why it matters"],
         "rows": [
             ["The code is a sticker on top of another one", "Someone may have covered the real code"],
             ["It arrived unrequested, by post or email", "Scammers send codes to many people at once"],
             ["It creates urgency, or promises a prize or refund", "Pressure stops you from checking"],
             ["The domain looks slightly wrong", "Fake sites copy real names with small changes"],
             ["It asks you to log in or enter a card", "A legitimate code rarely needs this immediately"],
             ["A person says scan to receive money", "Scanning to pay never receives money"],
             ["It shortens the link so you cannot see the destination", "Hidden destinations are easier to abuse"]]},
        {"kind": "prose", "id": "checklist", "h2": "A checklist before you scan",
         "steps": [
             "<strong>Look at the physical code.</strong> Is it stuck on? Does the edge of another sticker show?",
             "<strong>Preview the content.</strong> Use a scanner that shows the link before it opens, such as the <a href=\"qr-code-scanner.html\">SmartQRCraft scanner</a>, and read the domain.",
             "<strong>Check the domain.</strong> Does it match the company? Watch for extra words, odd endings and misspellings.",
             "<strong>Do not enter passwords or card details</strong> on a page you reached only through a code. Type the address yourself or use the official app.",
             "<strong>Be extra careful with payments.</strong> Confirm the payee name and the amount before you approve.",
             "<strong>Use your phone's built-in camera</strong> or a scanner you trust. Some free scanner apps are full of ads or collect data.",
             "<strong>Do not trust the padlock alone.</strong> A web address starting with https only means the connection is encrypted; many fake sites use it too.",
             "<strong>When in doubt, skip it.</strong> Go to the company's website yourself."]},
        _cta("Check a code before you open it", "The scanner shows what a QR code contains, without opening anything.", "qr-code-scanner.html", "Open the scanner"),
        {"kind": "prose", "id": "parking", "h2": "Paying for parking safely",
         "p": ["Car parks are one of the most common places for fake codes, because people are in a hurry and expect to pay by phone. In the UK, figures from the national fraud reporting service quoted by Which? put reported losses to QR code scams at about &pound;3.5 million in 2024."],
         "bullets": [
             "<strong>Download the parking app from the App Store or Google Play</strong>, using the app name printed on the official signs, instead of scanning a code on the machine.",
             "<strong>Pay at the machine</strong> by card or coins when you can.",
             "<strong>Look closely at the sign.</strong> A sticker that sits on top of the print, a different font or a peeling edge are warning signs.",
             "<strong>Check the web address</strong> matches the operator or council named on the sign."]},
        {"kind": "prose", "id": "for-businesses", "h2": "If you put QR codes in public",
         "p": ["Businesses can protect customers too."],
         "bullets": [
             "<strong>Check your codes regularly.</strong> Look for stickers placed over yours, especially in public places.",
             "<strong>Print the destination in words</strong> near the code, so people can compare.",
             "<strong>Use tamper-resistant materials</strong> where codes are exposed, or place them behind glass or on hard-to-cover surfaces.",
             "<strong>Send people to your own domain,</strong> not a shortened link you cannot verify.",
             "<strong>Never ask customers for passwords</strong> through a code.",
             "<strong>Test your own code</strong> with the <a href=\"qr-code-tester.html\">QR code tester</a> after you print."]},
        {"kind": "prose", "id": "if-scammed", "h2": "What to do if you scanned a fake QR code",
         "p": ["Scanning alone rarely causes harm. What matters is what you did next:"],
         "steps": [
             "<strong>You only opened the page:</strong> close it and clear the tab. Do not enter anything.",
             "<strong>You entered a password:</strong> change it straight away on the real site, and on any other account that uses the same password. Turn on two-step verification.",
             "<strong>You entered card or bank details, or paid:</strong> call your bank using the number on your card. In the UK you can dial <strong>159</strong> to reach most banks' fraud teams.",
             "<strong>You installed something:</strong> uninstall it, update your phone and run a security scan.",
             "<strong>Report it</strong>, so others are warned and the site can be taken down.",
         ]},
        {"kind": "table", "h2": "Where to report a fake QR code",
         "cols": ["Country", "Report fraud or a loss", "Report the scam message or website"],
         "rows": [
             ["United Kingdom", "Report Fraud (replaced Action Fraud): reportfraud.police.uk or 0300 123 2040. In Scotland, call Police Scotland on 101", "Forward scam emails to report@phishing.gov.uk and scam texts to 7726"],
             ["United States", "ReportFraud.ftc.gov; for cyber crime, the FBI's ic3.gov", "Report phishing to the company being impersonated"],
             ["India", "National Cyber Crime helpline 1930 or cybercrime.gov.in", "Chakshu on the Sanchar Saathi portal for suspicious calls and messages"],
         ],
         "p": ["Tell the business or council whose code was covered, too, so they can remove the sticker."]},
    ],
    "faq": [
        ("How can you tell if a QR code is fake?",
         "Look for a sticker placed over another code, check the web address in the preview before opening it, and be wary of codes that ask for card details, passwords or urgent payments."),
        ("What should I do if I scanned a fake QR code?",
         "If you did not enter anything, close the page. If you entered a password, change it; if you entered card details, call your bank (159 in the UK). Then report it."),
        ("How do I report a fake QR code in the UK?",
         "Report fraud to Report Fraud at reportfraud.police.uk or 0300 123 2040 (Police Scotland on 101 in Scotland), forward scam emails to report@phishing.gov.uk and texts to 7726, and tell the owner of the covered code."),
        ("Can scanning a QR code hack my phone?", "Scanning alone only reads text. Harm usually needs another step, such as opening a malicious link, entering credentials or installing an app. Keep your phone and browser updated."),
        ("What is quishing?", "Quishing is phishing done with a QR code. The code sends you to a fake page that tries to steal information or money."),
        ("Is it safe to scan a QR code in a restaurant?", "Usually, but check that the code is not a sticker placed over another one, and check the web address before you enter any details."),
        ("Can a QR code contain a virus?", "A QR code holds only text. It cannot carry a virus itself, but it can point to a page or file that is harmful."),
        ("How can I see the link before I open it?", "Many phone cameras show a preview of the link. You can also use the <a href=\"qr-code-scanner.html\">online scanner</a>, which shows the full content before opening anything."),
        ("Are QR codes for payments safe?", "They are safe when they come from a recipient you trust and you verify the name and amount. Never scan to receive money, because scanning in a payment app sends money out."),
        ("Are the QR codes I make here safe?", "They contain exactly what you enter, and nothing is sent to our servers. The safety of a code depends on the link you choose, so only point to sites you control or trust."),
    ],
    "related": [("qr-code-scanner.html", "QR code scanner"), ("what-is-a-qr-code.html", "What is a QR code?"), ("static-vs-dynamic-qr-codes.html", "Static vs dynamic QR codes")],
}

SIZE_GUIDE = {**_ART,
    "slug": "qr-code-size-guide.html",
    "crumb": "QR Code Size Guide",
    "title": "QR Code Size Guide: Minimum Size for Print and Screens",
    "description": "What size should a QR code be? Use the 10:1 rule, a size-by-distance table, quiet zone and contrast tips for business cards, menus, posters and stickers.",
    "og_title": "QR Code Size Guide | SmartQRCraft",
    "og_description": "How big a QR code should be for cards, menus, posters and signs, with a distance table.",
    "h1": "QR Code Size Guide: How Big Should a QR Code Be?",
    "lead": "A QR code that is too small will not scan, and one that is too big wastes space. Use this guide to choose a size for cards, menus, posters and stickers.",
    "faq_h2": "QR Code Size Questions",
    "sections": [
        {"kind": "prose", "id": "rule", "h2": "The 10:1 rule of thumb",
         "p": [
             "A widely used guide is that the QR code should be about one tenth of the distance it will be scanned from. If people scan from 30 cm (12 inches), aim for about 3 cm (1.2 inches). If they scan from 2 metres (6.5 feet), aim for about 20 cm (8 inches).",
             "It is a starting point, not a law. Longer content, low contrast, poor lighting and cheap printing all need more size."]},
        {"kind": "table", "h2": "Size by use",
         "p": ["Suggested minimum sizes for common places. Go larger if you can."],
         "cols": ["Where", "Typical distance", "Suggested minimum"],
         "rows": [
             ["Business card, receipt", "About 20 cm (8 in)", "2 cm (0.8 in), 2.5 cm is better"],
             ["Product label, packaging", "20 to 30 cm", "2 to 3 cm (0.8 to 1.2 in)"],
             ["Menu, table tent, leaflet", "30 to 40 cm", "3 cm (1.2 in) or more"],
             ["Poster at a bus stop or notice board", "About 1 m (3 ft)", "10 cm (4 in)"],
             ["Shop window or door", "1 to 2 m", "10 to 20 cm (4 to 8 in)"],
             ["Banner or large sign", "3 m and more", "30 cm (12 in) and more"],
             ["Screen, slide or video", "Depends on room", "Large and on screen long enough to scan"]]},
        {"kind": "prose", "id": "what-changes", "h2": "What makes a code need more size",
         "p": ["The same physical size can be fine for one code and too small for another."],
         "bullets": [
             "<strong>More content.</strong> A long link creates more, smaller modules, so it needs more space. Shorten links where you can.",
             "<strong>A logo.</strong> A center logo raises the error correction level, which also adds density. Keep the logo small.",
             "<strong>Low contrast.</strong> Pale colors or a busy background make scanning harder at any size.",
             "<strong>Poor print quality.</strong> Blurry edges and low resolution hurt small codes the most.",
             "<strong>Surface and angle.</strong> Curved, glossy or angled surfaces need a bigger code."]},
        {"kind": "prose", "id": "quiet-zone", "h2": "Do not forget the quiet zone",
         "p": ["The blank margin around the code is called the quiet zone. The QR specification calls for at least four modules of empty space on every side. Cropping it, or letting a border or picture touch the code, is a common cause of failed scans. This site's generators add a four-module margin by default."]},
        {"kind": "prose", "id": "file-formats", "h2": "File format and resolution",
         "p": ["For print, use <strong>SVG</strong>, which stays sharp at any size. If you use PNG, export a large size (2048 or 4096 px) and do not enlarge a small image. Keep proportions and never stretch the code."]},
        _cta("Test your code before you print", "The tester checks that your code still scans when it is small, blurry or low in contrast.", "qr-code-tester.html", "Open the tester"),
        {"kind": "prose", "id": "checklist", "h2": "Print checklist",
         "steps": [
             "Choose the size from the table, based on the real scanning distance.",
             "Check contrast: dark code, light background.",
             "Keep the quiet zone clear.",
             "Print a test at the final size on the real material.",
             "Scan it with at least two phones, at the real distance and in the real lighting.",
             "Then print the full run."]},
    ],
    "faq": [
        ("What is the minimum size for a QR code?", "About 2 cm (0.8 inches) for close-up use such as business cards, and more for anything scanned from further away. Longer content needs more size."),
        ("How big should a QR code be on a business card?", "At least 2 cm square, with 2.5 cm a safer choice, and a clear margin around it."),
        ("How big should a QR code on a poster be?", "Use the one-tenth rule: for a poster scanned from 1 metre, aim for about 10 cm."),
        ("Does a QR code need a white border?", "Yes. A blank margin, called the quiet zone, helps scanners find the code. The specification asks for at least four modules."),
        ("Can I make a QR code bigger without losing quality?", "Yes, if you use SVG or a high-resolution PNG. Never enlarge a small PNG, because it will blur."),
        ("Why does my small QR code not scan?", "It may be too small for its content, too low in contrast, or blurry. Shorten the link, increase contrast and print larger."),
    ],
    "related": [("qr-code-tester.html", "QR code tester"), ("qr-code-stickers.html", "QR code stickers"), ("what-is-a-qr-code.html", "What is a QR code?")],
}

RESTAURANTS = {**_ART,
    "slug": "qr-codes-for-restaurants.html",
    "crumb": "QR Codes for Restaurants",
    "title": "QR Codes for Restaurants: Menus, WiFi, Reviews and More",
    "description": "How restaurants, cafes and bars use QR codes for menus, table ordering links, WiFi, reviews and feedback, with setup tips and free tools.",
    "og_title": "QR Codes for Restaurants | SmartQRCraft",
    "og_description": "Practical ways restaurants use QR codes, and how to set each one up.",
    "h1": "QR Codes for Restaurants, Cafes and Bars",
    "lead": "A few well-placed QR codes save your staff time and give guests menus, WiFi and a way to leave a review without asking. Here is what works and how to set it up.",
    "faq_h2": "Restaurant QR Code Questions",
    "sections": [
        {"kind": "cards", "eyebrow": "Use Cases", "h2": "Where QR codes help a restaurant",
         "cards": [
             ("Digital menu", "Link a PDF or web menu on table tents, windows and takeout bags. See the <a href=\"qr-code-menu-generator.html\">QR code menu generator</a>."),
             ("WiFi for guests", "Put a WiFi code on tables or the counter. See the <a href=\"wifi-qr-code-generator.html\">WiFi QR code generator</a>."),
             ("Google reviews", "Ask happy guests for a review on the receipt. See the <a href=\"google-review-qr-code-generator.html\">Google review QR code</a>."),
             ("Feedback form", "A short form on the table catches problems before they become public. Use a <a href=\"google-forms-qr-code-generator.html\">Google Forms QR code</a>."),
             ("Social follow", "A code on the counter grows your Instagram or Facebook. Try <a href=\"instagram-qr-code-generator.html\">Instagram</a> or <a href=\"facebook-qr-code-generator.html\">Facebook</a>."),
             ("Table numbers", "Give each table its own code with the number in the link, using the <a href=\"bulk-qr-code-generator.html\">bulk QR code generator</a>.")]},
        {"kind": "prose", "id": "menu", "h2": "Setting up a QR code menu",
         "p": ["The menu code is the one most guests will use, so it is worth getting right."],
         "steps": [
             "Publish your menu as a mobile-friendly web page or a small PDF on your website.",
             "Make a static QR code that points to that address, and keep the address the same forever.",
             "When prices or dishes change, update the page or file, not the code.",
             "Put &quot;Scan for menu&quot; next to the code.",
             "Test on an iPhone and an Android phone, in the dining room's lighting."]},
        {"kind": "prose", "id": "best-practices", "h2": "Best practices",
         "p": ["A few habits decide whether guests enjoy QR codes or resent them."],
         "bullets": [
             "<strong>Keep a paper option.</strong> Some guests prefer not to scan, and older guests may need help.",
             "<strong>Keep menus light.</strong> A heavy PDF loads slowly on weak restaurant WiFi. Compress images.",
             "<strong>Print at least 3 cm (1.2 in)</strong> on table tents. See the <a href=\"qr-code-size-guide.html\">size guide</a>.",
             "<strong>Show allergens clearly</strong> in the menu itself.",
             "<strong>Protect the codes.</strong> Check tables regularly for stickers placed over your codes. See <a href=\"qr-code-safety.html\">QR code safety</a>.",
             "<strong>Do not put guest passwords or payment logins behind a scan</strong> unless you control the page."]},
        {"kind": "prose", "id": "reviews", "h2": "Getting more reviews the right way",
         "p": [
             "A review code on the receipt or table is a natural way to collect Google reviews from happy guests. Ask everyone, not just the ones who seem satisfied, and never offer a discount or gift in exchange for a review, because review platforms prohibit incentives."]},
        _cta("Make your restaurant QR codes", "Free, no signup, and no expiry.", "qr-code-menu-generator.html", "Create a menu QR code"),
    ],
    "faq": [
        ("Do restaurants need a QR code menu?", "Not required, but it lets you update the menu instantly and saves printing. Keep a paper option for guests who want one."),
        ("Should a restaurant menu QR code be static or dynamic?", "A static code pointing to a stable page you control works well. Update the page when the menu changes. See <a href=\"static-vs-dynamic-qr-codes.html\">static vs dynamic QR codes</a>."),
        ("How big should the QR code be on a table?", "At least about 3 cm (1.2 inches), with a clear margin. Larger is safer for dim rooms."),
        ("Can I take payments with a QR code?", "Some regions and payment providers support it, for example UPI in India and payment links in other countries. Check your provider's terms."),
        ("How do I stop people from tampering with my QR codes?", "Check tables regularly, use tamper-resistant stickers or holders, and print the web address in words next to the code."),
        ("Is it free to make restaurant QR codes here?", "Yes. Static QR codes are free, with no signup and no watermark."),
    ],
    "related": [("qr-code-menu-generator.html", "QR code menu generator"), ("google-review-qr-code-generator.html", "Google review QR code"), ("wifi-qr-code-generator.html", "WiFi QR code generator")],
}

REAL_ESTATE = {**_ART,
    "slug": "qr-codes-for-real-estate.html",
    "crumb": "QR Codes for Real Estate",
    "title": "QR Codes for Real Estate: Signs, Flyers and Open Houses",
    "description": "How real estate agents use QR codes on yard signs, flyers and business cards to share listings, virtual tours and open house sign-ins. Size and placement tips.",
    "og_title": "QR Codes for Real Estate | SmartQRCraft",
    "og_description": "Use QR codes on signs, flyers and cards to send buyers to listings and tours.",
    "h1": "QR Codes for Real Estate Agents and Landlords",
    "lead": "A QR code on a sign or flyer lets someone walking past a property see photos, price and a tour on their phone in seconds, and gives you a way to reach them.",
    "faq_h2": "Real Estate QR Code Questions",
    "sections": [
        {"kind": "cards", "eyebrow": "Use Cases", "h2": "Where real estate QR codes work",
         "cards": [
             ("Yard and window signs", "Link to the listing page, photos or a video tour."),
             ("Flyers and brochures", "Link to the full property sheet. See <a href=\"pdf-to-qr-code.html\">PDF to QR code</a>."),
             ("Open house sign-in", "Replace paper sheets with a <a href=\"google-forms-qr-code-generator.html\">Google Forms QR code</a>."),
             ("Business cards", "Save your contact details with a <a href=\"vcard-qr-code-generator.html\">vCard QR code</a>."),
             ("Virtual tours", "Link to a video. See the <a href=\"youtube-qr-code-generator.html\">YouTube QR code</a>."),
             ("Directions", "Send visitors to the exact address with a <a href=\"index.html#generator\">location QR code</a>.")]},
        {"kind": "prose", "id": "sign", "h2": "Putting a QR code on a yard sign",
         "p": ["A sign is read by people walking or pulling over, not by drivers, so design for a pedestrian at the curb."],
         "bullets": [
             "<strong>Size:</strong> for scanning from 1 to 2 metres, aim for about 10 to 20 cm. See the <a href=\"qr-code-size-guide.html\">size guide</a>.",
             "<strong>Contrast:</strong> dark code on a white panel, even if the rest of the sign is colorful.",
             "<strong>Call to action:</strong> &quot;Scan for photos and price&quot; beats a bare code.",
             "<strong>Weather:</strong> use vinyl or a laminated panel, and choose a matte finish to avoid glare.",
             "<strong>Reuse:</strong> a code that points to a page you control can be reused for the next listing if you update the page."]},
        {"kind": "prose", "id": "landing", "h2": "Where the code should send people",
         "p": [
             "A phone user wants price, photos and a way to contact you quickly. Send them to a mobile-friendly listing page, not a desktop brochure or a large PDF. Put your phone number and a contact button near the top.",
             "Because static QR codes cannot be edited, aim each code at a stable page. If the listing changes, update the page. For a property that sells, you can redirect that page to your next listing."]},
        {"kind": "prose", "id": "rules", "h2": "Check local rules",
         "p": ["Advertising rules, sign regulations and your brokerage or listing board's requirements differ by place. Check them before you print signs and marketing. This page is general information, not legal advice."]},
        _cta("Create your listing QR code", "Free, no signup. Download PNG or SVG for print.", "index.html#generator", "Open the generator"),
    ],
    "faq": [
        ("How do real estate agents use QR codes?", "On signs, flyers and cards to send people to listings, virtual tours and contact details, and at open houses for sign-in."),
        ("What size should a QR code on a yard sign be?", "For scanning from 1 to 2 metres, about 10 to 20 cm. Larger signs can use larger codes."),
        ("Should I use one code per property?", "Yes, if each property has its own page. You can also use one code that points to your listings page."),
        ("Can I track how many people scan my sign?", "Not with a static code. Use your website analytics on the listing page, or a page address unique to each sign."),
        ("How do I make many QR codes for many listings?", "Use the <a href=\"bulk-qr-code-generator.html\">bulk QR code generator</a> with one link per line."),
        ("Is it free?", "Yes. The QR codes are free, with no signup and no watermark."),
    ],
    "related": [("vcard-qr-code-generator.html", "vCard QR code generator"), ("pdf-to-qr-code.html", "PDF to QR code"), ("bulk-qr-code-generator.html", "Bulk QR code generator")],
}

HOTELS = {**_ART,
    "slug": "qr-codes-for-hotels-and-airbnb.html",
    "crumb": "QR Codes for Hotels and Airbnb",
    "title": "QR Codes for Hotels and Airbnb: WiFi, Guides and Reviews",
    "description": "How hotels, hostels and Airbnb hosts use QR codes for WiFi, guest guides, house rules, local maps and reviews. Setup tips and free tools.",
    "og_title": "QR Codes for Hotels and Airbnb | SmartQRCraft",
    "og_description": "QR codes that help guests connect, find things and leave reviews.",
    "h1": "QR Codes for Hotels, Hostels and Airbnb Hosts",
    "lead": "Guests ask the same questions again and again: the WiFi password, where to eat, how the heating works, when to check out. A few QR codes answer them without a phone call.",
    "faq_h2": "Hotel and Airbnb QR Code Questions",
    "sections": [
        {"kind": "cards", "eyebrow": "Use Cases", "h2": "QR codes that guests actually use",
         "cards": [
             ("WiFi", "Guests join the network with one scan. See the <a href=\"wifi-qr-code-generator.html\">WiFi QR code generator</a>."),
             ("Digital guidebook", "Link a PDF or page with house rules, appliance help and local tips. See <a href=\"pdf-to-qr-code.html\">PDF to QR code</a>."),
             ("Local map", "A <a href=\"index.html#generator\">location code</a> to your favorite cafes and sights."),
             ("Room dining and spa menus", "Use a <a href=\"qr-code-menu-generator.html\">menu QR code</a>."),
             ("Reviews", "A <a href=\"google-review-qr-code-generator.html\">Google review QR code</a> on the check-out card."),
             ("Messaging the host", "Add a <a href=\"whatsapp-qr-code-generator.html\">WhatsApp QR code</a> so guests can reach you.")]},
        {"kind": "prose", "id": "wifi", "h2": "WiFi codes: the biggest time saver",
         "p": [
             "A WiFi code removes the most common question you get. Print it on a card by the entrance or in a frame in the living area. If your router offers a guest network, use that one, so guests do not join the network your own devices use.",
             "Remember that a WiFi code contains the password in readable form for anyone who scans it. Place it in guest areas, and change the password if the printed code gets out."]},
        {"kind": "prose", "id": "guide", "h2": "Creating a guest guide that works on a phone",
         "p": ["Guests read on their phones, often on the go."],
         "bullets": [
             "Keep it short and sectioned: arrival, WiFi, house rules, appliances, transport, food, emergencies, checkout.",
             "Use a mobile-friendly page or a compact PDF with large text.",
             "Add a phone number for emergencies as plain text too.",
             "Keep the address stable, and update the page when things change.",
             "Offer the guide in the languages your guests speak."]},
        {"kind": "prose", "id": "reviews", "h2": "Asking for reviews",
         "p": ["A review code on the checkout card or in a thank-you message makes it easy for guests to review you on Google. Ask every guest, and do not offer a reward for a review, since platforms prohibit incentives."]},
        {"kind": "prose", "id": "tips", "h2": "Practical tips",
         "bullets": [
             "<strong>Print at least 3 cm (1.2 in)</strong> wide, and laminate codes in kitchens and bathrooms.",
             "<strong>Label each code,</strong> for example &quot;Scan for WiFi&quot;.",
             "<strong>Test after each change.</strong> If you change the WiFi name or password, make a new code.",
             "<strong>Use codes as a supplement,</strong> not a replacement. Keep essential information on paper too."]},
        _cta("Make a WiFi code for your guests", "Free, no signup.", "wifi-qr-code-generator.html", "Create a WiFi QR code"),
    ],
    "faq": [
        ("Is it safe to put a WiFi QR code in a guest room?", "The code contains the password in readable form, so use a guest network and place it only where guests are. Change the password if it leaks."),
        ("Do I need to make a new WiFi code when I change the password?", "Yes. The password is stored inside the code, so a changed password needs a new code."),
        ("How do I share a guidebook with a QR code?", "Host it as a web page or PDF, copy the link, and make a QR code of that link. See <a href=\"pdf-to-qr-code.html\">PDF to QR code</a>."),
        ("Can guests scan codes without an app?", "Yes. Current iPhones and most Android phones read QR codes with the camera app."),
        ("Are QR codes free to make?", "Yes. Static QR codes are free here, with no signup and no watermark."),
    ],
    "related": [("wifi-qr-code-generator.html", "WiFi QR code generator"), ("google-review-qr-code-generator.html", "Google review QR code"), ("pdf-to-qr-code.html", "PDF to QR code")],
}

RETAIL = {**_ART,
    "slug": "qr-codes-for-retail.html",
    "crumb": "QR Codes for Retail",
    "title": "QR Codes for Retail Stores: Products, Reviews and Payments",
    "description": "How shops use QR codes on products, shelves, receipts and windows for product info, reviews, social follow, payments and store details. Free tools and tips.",
    "og_title": "QR Codes for Retail | SmartQRCraft",
    "og_description": "Ways shops use QR codes to inform, sell and stay in touch with customers.",
    "h1": "QR Codes for Retail Stores and Small Shops",
    "lead": "In a shop, a QR code is a bridge from the physical product to something your shelf label cannot hold: a video, a manual, a review page or a way to pay.",
    "faq_h2": "Retail QR Code Questions",
    "sections": [
        {"kind": "cards", "eyebrow": "Use Cases", "h2": "Where shops use QR codes",
         "cards": [
             ("Product pages and manuals", "Link a label to a setup video, care guide or spec sheet. See <a href=\"youtube-qr-code-generator.html\">YouTube QR codes</a> and <a href=\"pdf-to-qr-code.html\">PDF QR codes</a>."),
             ("Shelf labels", "Make a code per product in bulk. See the <a href=\"bulk-qr-code-generator.html\">bulk generator</a>."),
             ("Receipts and bags", "Ask for a review or a follow. See <a href=\"google-review-qr-code-generator.html\">Google review QR code</a>."),
             ("Social follow", "A counter code for <a href=\"instagram-qr-code-generator.html\">Instagram</a> or <a href=\"facebook-qr-code-generator.html\">Facebook</a>."),
             ("Payments", "Where supported, a payment link code, such as <a href=\"venmo-qr-code-generator.html\">Venmo</a>, <a href=\"cash-app-qr-code-generator.html\">Cash App</a> or <a href=\"paypal-qr-code-generator.html\">PayPal</a>."),
             ("Windows and stickers", "Show store hours, location or offers. See <a href=\"qr-code-stickers.html\">QR code stickers</a>.")]},
        {"kind": "prose", "id": "barcode", "h2": "QR code or barcode on products?",
         "p": [
             "They do different jobs. A barcode (EAN or UPC) identifies a product at the checkout and in inventory systems. A QR code is for customers, giving them information on their phone. Most products can carry both. If you need internal barcodes for stock, see the <a href=\"barcode-generator.html\">barcode generator</a>. Retail barcodes for selling through retailers need officially issued numbers."]},
        {"kind": "prose", "id": "tips", "h2": "Tips for retail QR codes",
         "bullets": [
             "<strong>Give a reason to scan,</strong> like &quot;Scan for the setup video&quot;.",
             "<strong>Aim at mobile-friendly pages</strong> that load fast on store WiFi or mobile data.",
             "<strong>Keep codes at least 2 to 3 cm</strong> wide on labels, and check the <a href=\"qr-code-size-guide.html\">size guide</a>.",
             "<strong>Use stable links.</strong> Codes on packaging last as long as the product is on the shelf.",
             "<strong>Test on real packaging,</strong> including glossy or curved surfaces.",
             "<strong>Protect customers.</strong> Check counters and windows for stickers placed over your codes."]},
        _cta("Make QR codes for your products", "Make many at once with the bulk generator.", "bulk-qr-code-generator.html", "Open the bulk generator"),
    ],
    "faq": [
        ("How can a small shop use QR codes?", "For product information, reviews, following your social accounts, store details and, where available, payments."),
        ("Can I put a QR code on product packaging?", "Yes. Use a static code that points to a stable page. Test it on the real material."),
        ("What is the difference between a QR code and a barcode?", "A barcode identifies a product at a checkout. A QR code carries information for customers' phones."),
        ("How do I make a code for every product?", "Use the <a href=\"bulk-qr-code-generator.html\">bulk QR code generator</a> with one link per product."),
        ("Is it free?", "Yes. Static QR codes are free here, with no signup and no watermark."),
    ],
    "related": [("bulk-qr-code-generator.html", "Bulk QR code generator"), ("barcode-generator.html", "Barcode generator"), ("qr-code-stickers.html", "QR code stickers")],
}

ARTICLES = [WHAT_IS, STATIC_DYNAMIC, SAFETY, SIZE_GUIDE, RESTAURANTS, REAL_ESTATE, HOTELS, RETAIL]
