"""More India (smartqrcraft.in) pages: shop payment QR code, visiting card QR code.
Keywords (research/keywords-in.csv): how to get qr code for shop 5.4K, shop qr code 1K, qr code visiting card 2.4K."""

_IN = {"domain": "smartqrcraft.in", "lang": "en-IN"}

SHOP = {**_IN,
    "slug": "shop-qr-code.html",
    "crumb": "QR Code for Shop",
    "type": "upi",
    "tool_name": "Shop Payment QR Code Generator",
    "field_label": "",
    "field_placeholder": "",
    "cta": "SCAN & PAY",
    "empty": "Enter your UPI ID (like shopname@bank) to make your shop QR code.",
    "title": "How to Get a QR Code for Your Shop (Free UPI Payment QR) — SmartQRCraft",
    "description": "Get a QR code for your shop in 2 minutes: make a free UPI payment QR from your UPI ID, or apply for a merchant QR. Compare both, print tips and safety checks.",
    "og_title": "How to Get a QR Code for Your Shop | SmartQRCraft India",
    "og_description": "Free UPI payment QR code for shops, plus when to get a merchant QR instead.",
    "h1": 'How to Get a <span class="accent">QR Code for Your Shop</span>',
    "lead": "There are two ways to get a payment QR code for a shop in India: make one yourself from your UPI ID in a couple of minutes, or apply for a merchant QR from a UPI app or bank. This page lets you do the first, and explains when the second is better.",
    "faq_h2": "Shop QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "quick", "h2": "Make your shop QR code now (2 minutes)",
         "steps": [
             "Open your UPI app and copy your UPI ID. It looks like <code>shopname@okaxis</code> or <code>98xxxxxx10@ybl</code>.",
             "Paste it into the <strong>UPI ID</strong> field above and add your shop name as the payee name.",
             "Leave the amount blank so customers type what they owe.",
             "Turn on the frame and write &quot;Scan &amp; Pay&quot; or your shop name, then download the PNG.",
             "Print it, then pay ₹1 to yourself from a different phone to check the name and account are right.",
         ]},
        {"kind": "table", "h2": "Your own UPI QR vs a merchant QR",
         "p": ["Both work with every UPI app. The difference is in the extras."],
         "cols": ["", "UPI QR made here", "Merchant QR (PhonePe, Paytm, GPay for Business or your bank)"],
         "rows": [
             ["Cost", "Free", "Usually free to start; some devices and plans are paid"],
             ["Setup time", "About 2 minutes", "Registration and KYC, from minutes to a few days"],
             ["Needs", "Any UPI ID", "Business details and KYC documents"],
             ["Payment alerts", "In your own UPI app", "Business app, often a speaker box that announces payments"],
             ["Reports &amp; settlement", "Your normal bank statement", "Business dashboard and daily reports"],
             ["Design", "Your colors, logo and frame", "Standard printed standee"],
             ["Good for", "Small shops, stalls, home businesses, starting out", "Busy counters and growing businesses"],
         ]},
        {"kind": "prose", "id": "which", "h2": "Which one should your shop use?",
         "p": ["If you are starting out or take a handful of payments a day, a UPI QR from your own UPI ID is enough. Many small shops begin this way.",
               "If you take many payments, want a speaker that announces each payment, or need clean business reports, apply for a merchant QR in the business version of your UPI app or at your bank. Banks and apps may also ask you to move regular business collections to a business account, so check your bank's terms.",
               "You can use both: the merchant standee at the counter and a designed code from this page on your menu board, invoices or WhatsApp catalogue."]},
        {"kind": "cards", "eyebrow": "Print Tips", "h2": "Printing your shop QR code",
         "cards": [
             ("Size", "At least 5 cm (2 in) wide for a counter; 10 cm or more for a wall behind the counter."),
             ("Lamination", "Laminate it or use a plastic stand so it survives water and dust."),
             ("Placement", "At chest height, near the billing area, with good light and no glare."),
             ("Name on it", "Print your shop name next to the code so customers know they are paying the right shop."),
             ("Spare copy", "Keep a second print in case the first is damaged."),
             ("Check weekly", "Look for stickers pasted over your code. Replace it if anything looks changed."),
         ]},
        {"kind": "prose", "id": "safety", "h2": "Keep your shop QR code safe",
         "bullets": [
             "<strong>Customers pay you; you never scan to receive money.</strong> If anyone asks you to scan a code or enter your PIN to receive a payment, it is a scam.",
             "<strong>Always confirm the credit</strong> in your own app or on your speaker before handing over goods. A screenshot is not proof.",
             "<strong>Watch for code swaps.</strong> Fraudsters sometimes paste their own QR code over a shop's code.",
             "<strong>Your UPI ID is safe to share.</strong> It only lets people pay you. Never share your UPI PIN or OTPs.",
         ]},
        {"kind": "cta", "h2": "Want a stand for your counter?",
         "p": "Make a printable &quot;Scan &amp; Pay&quot; counter card with your shop name, ready to print on A4.",
         "href": "printable-qr-code-templates.html", "label": "Make a printable stand"},
    ],
    "faq": [
        ("How can I get a QR code for my shop for free?",
         "Copy your UPI ID from any UPI app, paste it into the generator on this page and download the code. It is free and works with GPay, PhonePe, Paytm, BHIM and other UPI apps."),
        ("Do I need a business bank account for a shop QR code?",
         "Not to make a UPI QR code. For many regular business payments, your bank or UPI app may ask you to use a business or current account; check their terms."),
        ("Will the money go straight to my bank account?",
         "Yes. UPI payments go from the customer's bank account to the account linked to your UPI ID."),
        ("Can I get a speaker that announces payments with this QR code?",
         "Payment speakers come with merchant QR codes from UPI apps and banks. A code from this page shows payments in your own UPI app instead."),
        ("Can I put a fixed amount on the shop QR code?",
         "You can, but for a shop it is better to leave the amount blank so customers type what they owe."),
        ("Is my UPI ID stored on your website?",
         "No. The QR code is generated in your browser, and your UPI ID is not sent to our server."),
    ],
    "related": [
        ("upi-qr-code-generator.html", "UPI QR code generator"),
        ("printable-qr-code-templates.html", "Printable QR code stands and cards"),
        ("qr-code-safety.html", "QR code safety guide"),
    ],
}

VISITING = {**_IN,
    "slug": "qr-code-visiting-card.html",
    "crumb": "QR Code for Visiting Card",
    "type": "vcard",
    "tool_name": "Visiting Card QR Code Generator",
    "field_label": "",
    "field_placeholder": "",
    "cta": "SAVE MY CONTACT",
    "empty": "Enter your name to make the visiting card QR code.",
    "title": "QR Code for Visiting Card | Free Maker + Printing Guide — SmartQRCraft",
    "description": "Make a free QR code for your visiting card that saves your name, mobile, email and address to the phone. Plus where to place it, size and printing tips.",
    "og_title": "QR Code for Visiting Card | SmartQRCraft India",
    "og_description": "Free visiting card QR code that saves your contact in one scan, with printing tips.",
    "h1": 'Free <span class="accent">QR Code for Visiting Card</span>',
    "lead": "Add a QR code to your visiting card so people can save your number, email and address in one scan, instead of typing them from the card.",
    "faq_h2": "Visiting Card QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to add a QR code to your visiting card",
         "steps": [
             "Fill in your name, mobile number with +91, email, company and designation above.",
             "Keep to the details that matter. Fewer details make a simpler code that prints cleanly small.",
             "Download the <strong>SVG</strong> for your printer or designer; it stays sharp at any size.",
             "Place it on the back of the card, or in a corner on the front, at least 2 cm wide.",
             "Before printing 500 cards, print one on paper at actual size and scan it with two phones.",
         ]},
        {"kind": "table", "h2": "Which QR code should go on the card?",
         "cols": ["QR type", "What it does", "Best for"],
         "rows": [
             ["Contact (vCard)", "Saves your contact straight to the phone", "Most visiting cards"],
             ["WhatsApp", "Opens a WhatsApp chat with you", "Shops and service businesses that work on WhatsApp"],
             ["Website or catalogue", "Opens your website or product list", "Businesses with an online catalogue"],
             ["UPI", "Lets people pay you", "Freelancers, tutors, small traders"],
             ["Location", "Opens your shop on Google Maps", "Shops, clinics and offices people visit"],
         ]},
        {"kind": "prose", "id": "design", "h2": "Design and printing tips",
         "bullets": [
             "<strong>Size:</strong> 2 cm (about 0.8 in) is the practical minimum on a card. 2.5 cm is safer.",
             "<strong>Quiet zone:</strong> keep a blank margin around the code; do not print text or borders right up to it.",
             "<strong>Contrast:</strong> dark code on a light background. Avoid gold or silver foil for the code itself.",
             "<strong>Finish:</strong> matte cards scan better than glossy ones under shop lights.",
             "<strong>Add a line of text</strong> such as &quot;Scan to save my number&quot; so people know what it does.",
         ]},
        {"kind": "prose", "id": "update", "h2": "What if my number changes?",
         "p": ["The details are stored inside the code, so a new number needs a new code and new cards. If you change jobs or numbers often, make the code point to a web page you control, such as a LinkedIn profile or your own contact page, using the <a href=\"index.html#generator\">URL generator</a>. Then you only update the page."]},
    ],
    "faq": [
        ("How do I make a QR code for my visiting card?",
         "Fill in your contact details in the generator above and download the code as SVG or PNG. Give the SVG to your printer."),
        ("What size should the QR code be on a visiting card?",
         "At least 2 cm wide, with a small blank margin around it."),
        ("Does it work on all phones?",
         "Yes. iPhone and Android cameras both read contact QR codes and offer to save the contact."),
        ("Is the visiting card QR code free?",
         "Yes. It is free, has no watermark and never expires."),
        ("Can I put my logo in the QR code?",
         "Yes, but keep it small. For tiny codes on cards it is often better to put the logo next to the code."),
    ],
    "related": [
        ("vcard-qr-code-generator.html", "vCard QR code generator"),
        ("whatsapp-qr-code-generator.html", "WhatsApp QR code generator"),
        ("qr-codes-in-print.html", "Printing QR codes: complete guide"),
    ],
}

IN_PAGES_3 = [SHOP, VISITING]
