"""German (smartqrcraft.de) versions of the round-3 English pages: phone, e-mail, SMS, text, app,
printing guide, printable templates, scanning guide, website widget.
Keywords (research/keywords-de.csv): qr code drucken 480 kd28, qr code drucken lassen 210 kd10, qr code for app 720 kd27,
qr code für app erstellen 110 kd26, text to qr code 390, qr code mit eigenem handy scannen 140 kd28.
No German search data exists for Telegram, X, MeCard or Bitcoin QR codes, so those pages are English only."""

_D = {"domain": "smartqrcraft.de", "lang": "de"}
_ART = {**_D, "static": True, "noindex": False, "type": "url"}


def _test():
    return "Scanne den fertigen Code vor dem Druck mit zwei verschiedenen Handys, zum Beispiel einem iPhone und einem Android-Gerät."


TELEFON = {**_D,
    "slug": "qr-code-telefonnummer.html",
    "crumb": "QR-Code für Telefonnummer",
    "type": "phone",
    "tool_name": "QR-Code für Telefonnummer",
    "field_label": "Telefonnummer mit Ländervorwahl",
    "field_placeholder": "+49 30 1234567",
    "cta": "JETZT ANRUFEN",
    "empty": "Gib eine Telefonnummer ein, um den QR-Code zu erstellen.",
    "title": "QR-Code für Telefonnummer erstellen | Anruf per Scan, kostenlos — SmartQRCraft",
    "description": "QR-Code für eine Telefonnummer kostenlos erstellen: Scannen, und das Handy bietet den Anruf an. Farben, Logo, PNG oder SVG. Ohne Anmeldung, läuft nie ab.",
    "og_title": "QR-Code für Telefonnummer | SmartQRCraft",
    "og_description": "Eine Telefonnummer als QR-Code: scannen und anrufen. Kostenlos und ohne Anmeldung.",
    "h1": 'QR-Code für <span class="accent">Telefonnummer</span> erstellen',
    "lead": "Gib eine Telefonnummer ein und lade den QR-Code herunter. Wer ihn scannt, sieht deine Nummer und kann dich mit einem Tipp anrufen, ohne sie abzutippen.",
    "faq_h2": "Fragen zum Telefon-QR-Code",
    "sections": [
        {"kind": "prose", "id": "anleitung", "h2": "So erstellst du einen QR-Code für deine Telefonnummer",
         "p": ["Der Code speichert deine Nummer im Standardformat <code>tel:</code>, das alle Handys verstehen."],
         "steps": [
             "Gib die Nummer <strong>mit Ländervorwahl</strong> ein, also +49 für Deutschland, +43 für Österreich oder +41 für die Schweiz. Die führende 0 der Vorwahl fällt dabei weg.",
             "Wähle Farben und einen Rahmen wie &quot;Jetzt anrufen&quot; und füge bei Bedarf dein Logo hinzu.",
             "Lade PNG für Bildschirme und Dokumente oder SVG für den Druck herunter.",
             _test(),
         ]},
        {"kind": "prose", "id": "scannen", "h2": "Was beim Scannen passiert",
         "p": ["Die Kamera erkennt den Code und zeigt einen Hinweis wie &quot;+49 30 1234567 anrufen&quot;. Der Anruf startet erst, wenn die Person darauf tippt. Ein QR-Code kann nie selbst einen Anruf auslösen.",
               "Leerzeichen, Bindestriche und Klammern werden automatisch entfernt, weil Telefone nur Ziffern und ein führendes Pluszeichen erwarten."]},
        {"kind": "table", "h2": "Beispiele für die richtige Schreibweise",
         "p": ["Mit Ländervorwahl funktioniert der Code auch für Gäste aus dem Ausland."],
         "cols": ["Land", "So steht die Nummer oft da", "So gibst du sie ein"],
         "rows": [
             ["Deutschland, Festnetz", "030 1234567", "+49 30 1234567"],
             ["Deutschland, Handy", "0151 23456789", "+49 151 23456789"],
             ["Österreich", "01 2345678", "+43 1 2345678"],
             ["Schweiz", "044 123 45 67", "+41 44 123 45 67"],
         ]},
        {"kind": "cards", "eyebrow": "Einsatzideen", "h2": "Wo ein Anruf-QR-Code hilft",
         "cards": [
             ("Schaufenster &amp; Türen", "Kunden rufen an, auch wenn du gerade geschlossen hast."),
             ("Firmenfahrzeuge", "Handwerker und Lieferdienste bekommen Anrufe vom geparkten Wagen."),
             ("Verkaufsschilder", "Interessenten rufen direkt vom Gehweg aus an."),
             ("Flyer &amp; Plakate", "Aus einer gedruckten Anzeige wird ein Anruf."),
             ("Geräte &amp; Maschinen", "Die Service-Hotline klebt direkt am Gerät."),
             ("Fundsachen", "Schlüsselanhänger oder Taschen, die den Besitzer anrufen."),
         ]},
        {"kind": "prose", "id": "tipps", "h2": "Tipps",
         "bullets": [
             "<strong>Drucke die Nummer zusätzlich aus.</strong> Manche Menschen wählen lieber selbst, und die sichtbare Nummer schafft Vertrauen.",
             "<strong>Nenne deine Erreichbarkeit:</strong> &quot;Scannen und anrufen, Mo bis Fr 9 bis 17 Uhr&quot;.",
             "<strong>Lieber schreiben als telefonieren?</strong> Ein <a href=\"sms-qr-code-erstellen.html\">SMS-QR-Code</a> passt für Kunden, die ungern anrufen.",
             "<strong>Größe:</strong> Auf einer Visitenkarte reichen etwa 2 cm. Wie groß es sonst sein sollte, steht im <a href=\"qr-code-drucken.html\">Druck-Ratgeber</a>.",
         ]},
    ],
    "faq": [
        ("Wie erstelle ich einen QR-Code für eine Telefonnummer?",
         "Gib die Nummer mit Ländervorwahl in den Generator oben ein und lade den Code herunter. Beim Scannen erscheint die Nummer mit einem Anruf-Button."),
        ("Ruft der Code automatisch an?",
         "Nein. Das Handy zeigt die Nummer an, und die Person tippt selbst auf Anrufen."),
        ("Funktioniert das mit iPhone und Android?",
         "Ja. Die Kamera-Apps von iPhone und Android erkennen Telefon-QR-Codes."),
        ("Kann ich die Nummer später ändern?",
         "Nein. Die Nummer steckt im Code selbst. Ändert sie sich, brauchst du einen neuen Code."),
        ("Ist der QR-Code kostenlos?",
         "Ja, ohne Anmeldung, ohne Wasserzeichen und ohne Ablaufdatum."),
    ],
    "related": [
        ("sms-qr-code-erstellen.html", "SMS-QR-Code erstellen"),
        ("e-mail-qr-code-erstellen.html", "E-Mail-QR-Code erstellen"),
        ("visitenkarte-qr-code-generator.html", "QR-Code für die Visitenkarte (ganzer Kontakt)"),
    ],
}

EMAIL = {**_D,
    "slug": "e-mail-qr-code-erstellen.html",
    "crumb": "E-Mail-QR-Code erstellen",
    "type": "email",
    "tool_name": "E-Mail-QR-Code Generator",
    "field_label": "", "field_placeholder": "",
    "cta": "SCHREIB UNS",
    "empty": "Gib eine E-Mail-Adresse ein, um den QR-Code zu erstellen.",
    "title": "E-Mail-QR-Code erstellen kostenlos | Mit Betreff und Text — SmartQRCraft",
    "description": "E-Mail-QR-Code kostenlos erstellen: Adresse, Betreff und Nachricht vorausfüllen. Beim Scannen öffnet sich eine fertige E-Mail. PNG oder SVG, ohne Anmeldung.",
    "og_title": "E-Mail-QR-Code erstellen | SmartQRCraft",
    "og_description": "Ein QR-Code, der eine fertig ausgefüllte E-Mail öffnet. Kostenlos und ohne Anmeldung.",
    "h1": '<span class="accent">E-Mail-QR-Code</span> erstellen',
    "lead": "Gib eine E-Mail-Adresse ein, auf Wunsch mit Betreff und Nachricht. Beim Scannen öffnet sich im Mailprogramm eine neue E-Mail, bereits ausgefüllt und bereit zum Senden.",
    "faq_h2": "Fragen zum E-Mail-QR-Code",
    "sections": [
        {"kind": "prose", "id": "anleitung", "h2": "So erstellst du einen E-Mail-QR-Code",
         "steps": [
             "Gib die Adresse ein, an die die E-Mail gehen soll.",
             "Lege einen Betreff fest, zum Beispiel &quot;Angebotsanfrage&quot; oder &quot;Feedback: Tisch 12&quot;. So kannst du Antworten leicht sortieren.",
             "Schreibe bei Bedarf eine kurze Nachricht. Der Absender kann sie vor dem Senden noch ändern.",
             "Gestalte den Code und lade ihn als PNG oder SVG herunter.",
             _test(),
         ]},
        {"kind": "prose", "id": "funktion", "h2": "So funktioniert ein E-Mail-QR-Code",
         "p": ["Der Code enthält einen Standard-<code>mailto:</code>-Link mit Betreff und Text. Beim Scannen öffnet das Handy das eingestellte Mailprogramm mit allen Angaben. Gesendet wird erst, wenn die Person auf Senden tippt.",
               "Auf dem Handy muss ein Mailprogramm eingerichtet sein. Das ist meist der Fall. Wenn nicht, ist ein Link zu einem Kontaktformular die sichere Alternative."]},
        {"kind": "table", "h2": "Ideen für den Betreff",
         "p": ["Ein fester Betreff zeigt dir sofort, woher eine E-Mail kommt."],
         "cols": ["Wo der Code hängt", "Betreff", "Warum"],
         "rows": [
             ["Produktverpackung", "Support: Modell X200", "Landet direkt beim richtigen Team"],
             ["Restauranttisch", "Feedback: Tisch 12", "Du weißt, welcher Tisch geschrieben hat"],
             ["Messestand", "Bewerbung Marketing", "Bewerbungen lassen sich leicht filtern"],
             ["Gedruckter Katalog", "Anfrage: Katalog 2026", "Zeigt, welches Druckstück wirkt"],
             ["Veranstaltungsplakat", "Anmeldung: Tag der offenen Tür", "Einfache Anmeldeliste"],
         ]},
        {"kind": "prose", "id": "tipps", "h2": "Tipps",
         "bullets": [
             "<strong>Nimm ein Sammelpostfach</strong> wie info@ oder kontakt@, keine persönliche Adresse, die sich ändern kann.",
             "<strong>Lange Texte machen dichte Codes.</strong> Ein kurzer Betreff und eine Zeile Text lassen sich leichter scannen.",
             "<strong>Sag, was passiert:</strong> &quot;Scannen und uns schreiben&quot; unter dem Code.",
         ]},
    ],
    "faq": [
        ("Wie erstelle ich einen QR-Code für eine E-Mail-Adresse?",
         "Gib die Adresse und optional Betreff und Nachricht oben ein und lade den Code herunter. Beim Scannen öffnet sich eine neue E-Mail."),
        ("Wird die E-Mail automatisch gesendet?",
         "Nein. Das Mailprogramm öffnet sich mit der fertigen E-Mail, und die Person entscheidet selbst, ob sie sie sendet."),
        ("Kann ich Betreff und Text vorausfüllen?",
         "Ja. Beides sind optionale Felder im Generator."),
        ("Warum passiert auf manchen Handys nichts?",
         "Das Handy braucht ein eingerichtetes Mailprogramm. Fehlt es, fragt das Handy nach einer App oder tut nichts."),
        ("Ist der Code kostenlos und läuft er ab?",
         "Er ist kostenlos, ohne Wasserzeichen und läuft nie ab, weil alle Angaben im Code selbst stecken."),
    ],
    "related": [
        ("qr-code-telefonnummer.html", "QR-Code für Telefonnummer"),
        ("sms-qr-code-erstellen.html", "SMS-QR-Code erstellen"),
        ("visitenkarte-qr-code-generator.html", "QR-Code für die Visitenkarte"),
    ],
}

SMS = {**_D,
    "slug": "sms-qr-code-erstellen.html",
    "crumb": "SMS-QR-Code erstellen",
    "type": "sms",
    "tool_name": "SMS-QR-Code Generator",
    "field_label": "", "field_placeholder": "",
    "cta": "SCHREIB UNS",
    "empty": "Gib eine Handynummer ein, um den QR-Code zu erstellen.",
    "title": "SMS-QR-Code erstellen kostenlos | Vorausgefüllte SMS per Scan — SmartQRCraft",
    "description": "SMS-QR-Code kostenlos erstellen: Beim Scannen öffnet sich eine SMS an deine Nummer mit vorgeschriebenem Text. Für Feedback, Bestellungen und Anfragen. Ohne Anmeldung.",
    "og_title": "SMS-QR-Code erstellen | SmartQRCraft",
    "og_description": "Ein QR-Code, der eine fertige SMS öffnet. Kostenlos und ohne Anmeldung.",
    "h1": '<span class="accent">SMS-QR-Code</span> erstellen',
    "lead": "Gib eine Handynummer und optional eine Nachricht ein. Beim Scannen öffnet sich die SMS-App mit dem fertigen Text an dich.",
    "faq_h2": "Fragen zum SMS-QR-Code",
    "sections": [
        {"kind": "prose", "id": "anleitung", "h2": "So erstellst du einen SMS-QR-Code",
         "steps": [
             "Gib die Handynummer mit Ländervorwahl ein, zum Beispiel +49 151 23456789.",
             "Schreibe eine kurze Nachricht, etwa &quot;Tisch für Freitag reservieren&quot;.",
             "Wähle Farben und einen Rahmen wie &quot;Schreib uns&quot; und lade den Code herunter.",
             _test(),
         ]},
        {"kind": "prose", "id": "funktion", "h2": "So funktioniert es",
         "p": ["Der Code nutzt das weit verbreitete Format <code>SMSTO:</code> mit Nummer und Nachricht. Die SMS-App öffnet sich mit beidem, gesendet wird erst nach einem Tipp auf Senden. Es fallen die normalen SMS-Kosten des Absenders an."]},
        {"kind": "cards", "eyebrow": "Ideen", "h2": "Wofür SMS-QR-Codes genutzt werden",
         "cards": [
             ("Schnelles Feedback", "&quot;Bewerte deinen Besuch von 1 bis 5&quot; auf dem Kassenbon oder Tischaufsteller."),
             ("Bestellungen &amp; Reservierungen", "Kunden schicken eine vorformulierte Anfrage."),
             ("Service-Anfragen", "Ein Code am Gerät schickt die Modellnummer gleich mit."),
             ("Gewinnspiele &amp; Abstimmungen", "Jede Antwort bekommt einen eigenen Code mit eigenem Text."),
             ("Immobilien", "&quot;Bitte Exposé für Musterstraße 12&quot; am Verkaufsschild."),
             ("Handwerk", "Terminanfrage direkt vom Firmenwagen."),
         ]},
        {"kind": "prose", "id": "recht", "h2": "Wichtig bei SMS-Werbung",
         "p": ["Wenn du Nummern für Werbe-SMS nutzen willst, brauchst du in Deutschland eine ausdrückliche Einwilligung, und Empfänger müssen sich jederzeit abmelden können. Der QR-Code selbst öffnet nur eine Nachricht, die die Person bewusst sendet. Was du danach mit der Nummer machst, unterliegt dem Datenschutz- und Wettbewerbsrecht. Lass dich im Zweifel beraten."]},
    ],
    "faq": [
        ("Wie erstelle ich einen QR-Code, der eine SMS öffnet?",
         "Gib Nummer und Nachricht oben ein und lade den Code herunter. Beim Scannen öffnet sich eine fertige SMS."),
        ("Wird die SMS automatisch gesendet?",
         "Nein. Die Person tippt immer selbst auf Senden."),
        ("Funktioniert das mit dem iPhone?",
         "Ja. iPhone und Android erkennen SMS-QR-Codes mit der Kamera."),
        ("Kann ich die Nachricht leer lassen?",
         "Ja. Dann öffnet sich eine leere SMS an deine Nummer."),
        ("Ist der Code kostenlos?",
         "Ja, ohne Anmeldung und ohne Ablaufdatum."),
    ],
    "related": [
        ("qr-code-telefonnummer.html", "QR-Code für Telefonnummer"),
        ("e-mail-qr-code-erstellen.html", "E-Mail-QR-Code erstellen"),
        ("index.html#generator", "Kostenloser QR-Code Generator"),
    ],
}

TEXT = {**_D,
    "slug": "text-in-qr-code.html",
    "crumb": "Text in QR-Code umwandeln",
    "type": "text",
    "tool_name": "Text in QR-Code umwandeln",
    "field_label": "Dein Text",
    "field_placeholder": "Nachricht, Code oder Notiz eingeben ...",
    "cta": "SCAN MICH",
    "empty": "Gib einen Text ein, um den QR-Code zu erstellen.",
    "title": "Text in QR-Code umwandeln kostenlos | Text-QR-Code erstellen — SmartQRCraft",
    "description": "Text in einen QR-Code umwandeln, kostenlos: Nachrichten, Codes, Seriennummern oder Hinweise, die beim Scannen auf dem Bildschirm erscheinen. Funktioniert offline.",
    "og_title": "Text in QR-Code umwandeln | SmartQRCraft",
    "og_description": "Beliebigen Text als QR-Code, der auch offline funktioniert. Kostenlos und ohne Anmeldung.",
    "h1": '<span class="accent">Text in QR-Code</span> umwandeln',
    "lead": "Tippe einen beliebigen Text ein und mach daraus einen QR-Code. Beim Scannen erscheint der Text auf dem Handy, ganz ohne Internetverbindung.",
    "faq_h2": "Fragen zum Text-QR-Code",
    "sections": [
        {"kind": "prose", "id": "anleitung", "h2": "So wandelst du Text in einen QR-Code um",
         "steps": [
             "Tippe oder füge deinen Text in das Feld ein.",
             "Achte auf die Vorschau: Je mehr Text, desto dichter wird der Code.",
             "Lade PNG oder SVG herunter.",
             "Scanne den Code einmal zur Kontrolle, besonders bei Umlauten und Sonderzeichen.",
         ]},
        {"kind": "table", "h2": "Wie viel Text passt hinein?",
         "p": ["Technisch fasst ein QR-Code einige tausend Zeichen, aber dichte Codes lassen sich schlecht scannen. Als Faustregel:"],
         "cols": ["Textlänge", "Ergebnis"],
         "rows": [
             ["Bis etwa 100 Zeichen", "Einfacher Code, scannt auch klein gut"],
             ["100 bis 300 Zeichen", "Gut in normaler Druckgröße"],
             ["300 bis 1.000 Zeichen", "Dicht: größer drucken und sorgfältig testen"],
             ["Mehr als 1.000", "Nicht empfohlen. Stell den Text lieber auf eine Webseite und verlinke sie"],
         ]},
        {"kind": "cards", "eyebrow": "Ideen", "h2": "Wofür Text-QR-Codes praktisch sind",
         "cards": [
             ("Hinweise ohne Internet", "Anleitungen oder Sicherheitshinweise, die auch ohne Netz lesbar sind."),
             ("Serien- &amp; Inventarnummern", "Scannen statt lange Nummern abtippen."),
             ("Schnitzeljagd &amp; Rätsel", "Versteckte Botschaften für Spiele und Geschenke."),
             ("Unterricht", "Fragen und Lösungen zum Scannen."),
             ("Veranstaltungen", "Türcode oder Ablaufplan auf dem Namensschild."),
             ("Gutscheincodes", "Ein Code, den Kunden an der Kasse eingeben."),
         ]},
        {"kind": "prose", "id": "datenschutz", "h2": "Ist der Text privat?",
         "p": ["Der Text steckt im Bild selbst. Jeder, der den Code scannt, kann ihn lesen. Schreib also keine Passwörter oder persönlichen Daten in einen Code, den andere sehen. Der Generator läuft in deinem Browser, der Text wird nicht an unseren Server gesendet."]},
    ],
    "faq": [
        ("Wie wandle ich Text in einen QR-Code um?",
         "Gib den Text in das Feld oben ein und lade den Code herunter. Beim Scannen erscheint der Text."),
        ("Braucht ein Text-QR-Code Internet?",
         "Nein. Der Text steckt im Code, jeder Scanner kann ihn offline lesen."),
        ("Wie lang darf der Text sein?",
         "Theoretisch einige tausend Zeichen, für sicheres Scannen aber besser unter 300."),
        ("Funktionieren Umlaute und Emojis?",
         "Ja. Der Text wird als UTF-8 gespeichert. Teste den Code trotzdem mit den Handys deiner Zielgruppe."),
        ("Kann ich den Text später ändern?",
         "Nein. Der Text ist Teil des Codes, für eine Änderung brauchst du einen neuen Code."),
    ],
    "related": [
        ("qr-code-scanner-online.html", "QR-Code Scanner online"),
        ("qr-code-testen.html", "QR-Code testen"),
        ("index.html#generator", "Kostenloser QR-Code Generator"),
    ],
}

APP = {**_D,
    "slug": "qr-code-fuer-app-erstellen.html",
    "crumb": "QR-Code für App erstellen",
    "type": "app",
    "tool_name": "App-Download QR-Code",
    "field_label": "Link zum App Store oder Google Play",
    "field_placeholder": "https://apps.apple.com/de/app/deineapp",
    "cta": "APP LADEN",
    "empty": "Füge den Link zu deiner App im App Store oder bei Google Play ein.",
    "title": "QR-Code für App erstellen kostenlos | App Store & Google Play — SmartQRCraft",
    "description": "QR-Code für deine App kostenlos erstellen: führt zum App Store oder zu Google Play. Mit Tipps, wie ein Code iPhone- und Android-Nutzer erreicht. PNG oder SVG, ohne Anmeldung.",
    "og_title": "QR-Code für App erstellen | SmartQRCraft",
    "og_description": "Ein QR-Code, der deine App im App Store oder bei Google Play öffnet. Kostenlos.",
    "h1": 'QR-Code für <span class="accent">App</span> erstellen',
    "lead": "Füge den Link zu deiner App im App Store oder bei Google Play ein und lade den QR-Code herunter. Beim Scannen öffnet sich die Store-Seite, einen Tipp vom Download entfernt.",
    "faq_h2": "Fragen zum App-QR-Code",
    "sections": [
        {"kind": "prose", "id": "anleitung", "h2": "So erstellst du einen QR-Code für deine App",
         "steps": [
             "Öffne die Seite deiner App im App Store oder bei Google Play und kopiere den Link.",
             "Füge ihn oben ein und wähle einen Rahmen wie &quot;App laden&quot;.",
             "Lade PNG oder SVG herunter und teste den Code mit dem passenden Handy.",
         ]},
        {"kind": "table", "h2": "Ein Code für iPhone und Android?",
         "p": ["Ein Store-Link öffnet nur seinen eigenen Store. Ein App-Store-Link zeigt auf Android nur eine Webseite, nicht Google Play. Deine Möglichkeiten:"],
         "cols": ["Möglichkeit", "So funktioniert es", "Passt für"],
         "rows": [
             ["Zwei Codes nebeneinander", "Einer mit &quot;App Store&quot;, einer mit &quot;Google Play&quot; beschriftet", "Druck mit genug Platz, ohne Technik"],
             ["Download-Seite auf deiner Website", "Ein Code führt zu deineapp.de/download, die Seite zeigt beide Stores oder erkennt das Handy", "Ein Code, volle Kontrolle, funktioniert dauerhaft"],
             ["Nur ein Store", "Wenn fast alle Nutzer dieselbe Plattform haben", "Einfach, schließt aber andere aus"],
         ]},
        {"kind": "prose", "id": "download-seite", "h2": "Am besten: auf eine eigene Download-Seite verlinken",
         "p": ["Ein statischer Code für <strong>deineapp.de/download</strong> geht nie kaputt, auch wenn sich deine Store-Links ändern. Die Seite kann beide Store-Buttons zeigen, oder ein Entwickler leitet je nach Gerät automatisch weiter."]},
        {"kind": "cards", "eyebrow": "Einsatzorte", "h2": "Wo App-QR-Codes wirken",
         "cards": [
             ("Verpackung &amp; Anleitungen", "Begleit-Apps für Geräte und Produkte."),
             ("Kassen &amp; Theken", "Bonus- und Bestell-Apps."),
             ("Website am Computer", "Besucher scannen vom Bildschirm und installieren auf dem Handy."),
             ("Veranstaltungen", "Event-Apps und Programme."),
             ("Gastronomie", "Bestell- und Bezahl-Apps am Tisch."),
             ("Printwerbung", "Zeitschriften, Plakate und Flyer."),
         ]},
    ],
    "faq": [
        ("Wie erstelle ich einen QR-Code für meine App?",
         "Kopiere den Link deiner App aus dem App Store oder von Google Play, füge ihn oben ein und lade den Code herunter."),
        ("Kann ein Code auf jedem Handy den richtigen Store öffnen?",
         "Mit einem einfachen Store-Link nicht. Nutze zwei Codes oder verlinke eine Download-Seite auf deiner Website, die beide Stores zeigt oder nach Gerät weiterleitet."),
        ("Ist der App-QR-Code kostenlos?",
         "Ja, ohne Anmeldung und ohne Ablaufdatum."),
        ("Was passiert, wenn sich mein Store-Link ändert?",
         "Ein statischer Code zeigt weiter auf den alten Link. Mit einer eigenen Download-Seite passiert das nicht."),
        ("Kann ich mein App-Icon in die Mitte setzen?",
         "Ja. Lade dein Icon als quadratisches PNG im Bereich Logo hoch."),
    ],
    "related": [
        ("qr-code-mit-logo.html", "QR-Code mit Logo"),
        ("qr-code-widget-website.html", "QR-Code Widget für deine Website"),
        ("index.html#generator", "Kostenloser QR-Code Generator"),
    ],
}

DRUCKEN = {**_ART,
    "slug": "qr-code-drucken.html",
    "crumb": "QR-Code drucken",
    "title": "QR-Code drucken: Größe, Dateiformat und Tipps für jedes Material",
    "description": "QR-Code drucken, der sicher scannt: das richtige Dateiformat, Größen und Farben für Flyer, Visitenkarten, T-Shirts, Verpackungen, Plakate und Aufkleber.",
    "og_title": "QR-Code drucken: der Ratgeber | SmartQRCraft",
    "og_description": "Dateiformat, Größe, Farben und Platzierung für gedruckte QR-Codes.",
    "h1": "QR-Code drucken: So scannt er garantiert",
    "lead": "Die meisten Probleme mit QR-Codes entstehen beim Druck, nicht im Generator. Hier steht, welche Datei du an die Druckerei schickst, welche Größe du wählst und worauf es bei Flyern, Karten, Kleidung und Verpackungen ankommt.",
    "faq_h2": "Fragen zum Drucken von QR-Codes",
    "sections": [
        {"kind": "table", "h2": "Welche Datei für den Druck?",
         "cols": ["Format", "Wofür", "Warum"],
         "rows": [
             ["SVG", "Grafiker, Online-Druckereien, große Formate", "Vektor: scharf in jeder Größe, bearbeitbar in Illustrator, Inkscape, Canva und Figma"],
             ["PDF", "Druckereien", "Vektor, öffnet sich überall, Farben bleiben exakt"],
             ["EPS", "Ältere Druckabläufe, Schilder, Stickereien", "Vektorformat, das viele ältere Programme erwarten"],
             ["PNG ab 2048 px", "Bürodrucker, Word, PowerPoint", "Reicht, wenn die Datei groß genug für die Druckgröße ist"],
             ["JPG", "Nur wenn nichts anderes geht", "Die Kompression kann die Kanten verwischen"],
         ],
         "p": ["Unser Generator exportiert alle fünf. Für alles, was eine Druckerei druckt, nimm SVG oder PDF."]},
        {"kind": "prose", "id": "checkliste", "h2": "Die 8-Punkte-Checkliste vor dem Druck",
         "steps": [
             "<strong>Größe:</strong> mindestens 2 cm für Dinge, die man in der Hand hält. Aus der Entfernung etwa ein Zehntel des Scan-Abstands.",
             "<strong>Ruhezone:</strong> ein weißer Rand von 4 Modulen rundherum. Kein Text, kein Rahmen und kein Falz darf hineinragen.",
             "<strong>Kontrast:</strong> dunkler Code auf hellem Grund. Helle Codes auf dunklem Grund lesen manche Scanner nicht.",
             "<strong>Kurzer Inhalt:</strong> Kurze Links ergeben weniger, größere Module, die Druckfehler besser verkraften.",
             "<strong>Fehlerkorrektur:</strong> Stufe Q oder H für raue Oberflächen, Stoff oder ein Logo in der Mitte.",
             "<strong>Nicht verzerren:</strong> immer proportional skalieren.",
             "<strong>Probedruck in Originalgröße</strong> und mit einem iPhone und einem Android-Handy scannen.",
             "<strong>Ziel testen:</strong> Funktioniert der Link auch im Mobilfunknetz, nicht nur im Büro-WLAN?",
         ]},
        {"kind": "table", "h2": "Material für Material",
         "cols": ["Wo", "Empfohlene Größe", "Worauf achten"],
         "rows": [
             ["Visitenkarten", "2 bis 2,5 cm", "Matte Karten, keine Folienprägung auf dem Code, kurzer Inhalt"],
             ["Flyer &amp; Broschüren", "3 bis 4 cm", "Nicht über den Falz; sagen, was der Scan bringt (&quot;Scannen für 10 % Rabatt&quot;)"],
             ["Plakate", "10 bis 20 cm", "An den Leseabstand anpassen, auf Augenhöhe platzieren"],
             ["Verpackungen", "2 bis 3 cm", "Flache Seite statt Kante oder Naht; Glanzfolie spiegelt"],
             ["Etiketten &amp; Aufkleber", "ab 2 cm", "Wetterfestes Material für draußen"],
             ["T-Shirts &amp; Stoff", "8 bis 12 cm", "Siebdruck oder DTF statt Stickerei bei kleinen Codes; flache Stelle wählen; Stoff dehnt sich, also am Kleidungsstück testen"],
             ["Schaufenster-Aufkleber", "ab 10 cm", "Für die Seite drucken, von der gescannt wird; Spiegelungen verringern den Kontrast"],
             ["Tischaufsteller &amp; Speisekarten", "3 bis 5 cm", "Laminieren gegen Flecken"],
         ]},
        {"kind": "prose", "id": "druckerei", "h2": "QR-Code drucken lassen",
         "p": ["Online-Druckereien und Copyshops brauchen eine Vektordatei. Lade das SVG oder PDF herunter und setze den Code im Layout ein, bevor du die Druckdatei hochlädst. Frag nach einem Proof oder bestelle zuerst ein einzelnes Exemplar, wenn die Auflage groß ist. Achte bei CMYK-Druck darauf, dass die Codefarbe dunkel bleibt: Leuchtende Bildschirmfarben wirken gedruckt oft heller."]},
        {"kind": "prose", "id": "tshirt", "h2": "QR-Code auf T-Shirts und Stoff",
         "p": ["Stoff dehnt sich und wirft Falten, dadurch verzieht sich das Raster. Nimm einen großen Code, eckige Module statt Punkte, hohe Fehlerkorrektur und eine glatte, helle Fläche. Siebdruck und DTF-Transfers halten die Kanten scharf. Stickerei klappt nur bei großen Codes mit wenigen Modulen, also erst ein Muster bestellen."]},
        {"kind": "cta", "h2": "Du brauchst eine fertige Druckvorlage?",
         "p": "Tischaufsteller, WLAN-Karten, Theken-Schilder und Etikettenbögen mit deinem QR-Code. Drucken oder als PDF speichern.",
         "href": "qr-code-vorlagen-drucken.html", "label": "Zu den Druckvorlagen"},
    ],
    "faq": [
        ("Welches Dateiformat ist am besten zum Drucken?",
         "SVG oder PDF. Beides sind Vektordateien, der Code bleibt in jeder Größe scharf. Nimm ein PNG ab 2048 Pixel, wenn dein Programm nur Bilder annimmt."),
        ("Wie klein darf ein gedruckter QR-Code sein?",
         "Etwa 2 cm für Dinge, die man in der Hand hält. Für größere Abstände entsprechend größer."),
        ("Kann ich einen QR-Code farbig drucken?",
         "Ja, solange der Code deutlich dunkler ist als der Hintergrund. Teste das gedruckte Stück, nicht nur den Bildschirm."),
        ("Warum scannt mein gedruckter QR-Code nicht?",
         "Meist ist er zu klein, der weiße Rand fehlt, der Kontrast ist zu gering, es spiegelt, oder ein langer Link macht den Code zu dicht. Prüfe ihn mit dem <a href=\"qr-code-testen.html\">QR-Code-Test</a>."),
        ("Kann ich einen QR-Code drucken lassen?",
         "Ja. Lade SVG oder PDF herunter und gib die Datei deiner Druckerei oder lade sie bei einer Online-Druckerei hoch."),
        ("Laufen gedruckte QR-Codes ab?",
         "Ein statischer QR-Code läuft nie ab. Er funktioniert, solange der Link oder Inhalt darin funktioniert."),
    ],
    "related": [("qr-code-vorlagen-drucken.html", "QR-Code Vorlagen zum Drucken"), ("qr-code-testen.html", "QR-Code testen"), ("qr-code-mit-logo.html", "QR-Code mit Logo")],
}

VORLAGEN = {**_D,
    "slug": "qr-code-vorlagen-drucken.html",
    "crumb": "QR-Code Vorlagen zum Drucken",
    "widget": "print",
    "template": "tent",
    "type": "url",
    "tool_name": "QR-Code Vorlagen zum Drucken",
    "field_label": "", "field_placeholder": "", "cta": "", "empty": "",
    "title": "QR-Code Vorlage zum Drucken kostenlos | Tischaufsteller, WLAN-Karte — SmartQRCraft",
    "description": "Kostenlose QR-Code Vorlagen zum Drucken: Tischaufsteller, Theken-Schild, WLAN-Karten und Etikettenbögen in A4. Text und Farben anpassen, drucken oder als PDF speichern.",
    "og_title": "QR-Code Vorlagen zum Drucken | SmartQRCraft",
    "og_description": "Tischaufsteller, Schilder, WLAN-Karten und Etiketten mit deinem QR-Code. Drucken oder als PDF.",
    "h1": '<span class="accent">QR-Code Vorlagen</span> zum Drucken',
    "lead": "Wähle eine Vorlage, gib Link, WLAN oder Kontaktdaten und deinen Text ein und drucke alles auf A4. Ganz ohne Grafikprogramm.",
    "faq_h2": "Fragen zu den Druckvorlagen",
    "sections": [
        {"kind": "table", "h2": "Welche Vorlage passt?",
         "cols": ["Vorlage", "Was du bekommst", "Passt für"],
         "rows": [
             ["Tischaufsteller", "Eine A4-Seite zum Falten, damit sie auf dem Tisch steht, mit dem Code auf beiden Seiten", "Speisekarten, Feedback, WLAN im Café"],
             ["Theken-Schild", "Ein A4-Schild mit großer Überschrift und großem Code", "Kasse, Empfang, Schaufenster"],
             ["Karten (4 pro A4)", "Vier A6-Karten mit Schnittmarken", "Handzettel, Zimmerkarten, Regale"],
             ["WLAN-Karten", "Vier Karten mit Netzwerkname, optionalem Passwort und WLAN-QR-Code", "Hotels, Ferienwohnungen, Büros"],
             ["Etikettenbogen", "Derselbe Code mehrfach im Raster, mit optionalem Text", "Aufkleber, Verpackungen, Inventar"],
         ]},
        {"kind": "prose", "id": "anleitung", "h2": "So druckst du deine Vorlage",
         "steps": [
             "Wähle eine Vorlage und gib ein, was der QR-Code tun soll.",
             "Trage Überschrift, Firmennamen und Kleingedrucktes ein und wähle eine Akzentfarbe.",
             "Klicke auf <strong>Drucken / als PDF speichern</strong> und stelle im Druckdialog <strong>Originalgröße</strong> bzw. 100 % ein.",
             "Für ein PDF wählst du <strong>Als PDF speichern</strong> als Drucker. Das PDF kannst du an eine Druckerei schicken.",
             "Scanne ein gedrucktes Exemplar, bevor du den Rest druckst.",
         ]},
        {"kind": "prose", "id": "falten", "h2": "Den Tischaufsteller falten",
         "p": ["Drucke auf dickeres Papier (ab 160 g/m²), wenn dein Drucker das kann. Falte an der gestrichelten Linie, sodass beide Hälften nach außen zeigen. Die obere Hälfte steht absichtlich auf dem Kopf, damit sie nach dem Falten richtig herum ist. Klebe die unteren Kanten zusammen oder stecke die Seite in einen Acryl-Aufsteller."]},
        {"kind": "prose", "id": "etiketten", "h2": "Auf Etikettenbögen drucken",
         "p": ["Etikettenbögen unterscheiden sich je nach Hersteller, auch bei gleicher Anzahl. Drucke zuerst eine Seite auf normales Papier und halte sie gegen das Licht vor deinen Bogen. Passt alles, druckst du auf die Etiketten."],
         "bullets": [
             "<strong>24 pro Bogen (70 × 37 mm)</strong> und <strong>65 pro Bogen (38 × 21 mm)</strong> entsprechen gängigen A4-Adress- und Mini-Etiketten.",
             "Kleine Etiketten funktionieren nur mit kurzem Inhalt, etwa einem kurzen Link.",
             "Für draußen wetterfeste Folienetiketten nehmen.",
         ]},
    ],
    "faq": [
        ("Sind die Vorlagen kostenlos?",
         "Ja. Ohne Anmeldung und ohne Wasserzeichen, so oft du willst."),
        ("Wie speichere ich die Vorlage als PDF?",
         "Klicke auf Drucken / als PDF speichern und wähle im Druckdialog Als PDF speichern (oder Microsoft Print to PDF) als Drucker."),
        ("Warum ist die gedruckte Seite kleiner als A4?",
         "Im Druckdialog ist wahrscheinlich An Seite anpassen gewählt. Stelle Originalgröße oder 100 % ein."),
        ("Kann ich das Design weiter anpassen?",
         "Lade das SVG herunter und öffne es in Canva, Figma, Illustrator oder Inkscape."),
        ("Wird mein WLAN-Passwort gespeichert?",
         "Nein. Die Seite entsteht in deinem Browser, es wird nichts hochgeladen."),
    ],
    "related": [
        ("qr-code-drucken.html", "QR-Code drucken: der Ratgeber"),
        ("wlan-qr-code-generator.html", "WLAN QR-Code Generator"),
        ("visitenkarte-qr-code-generator.html", "QR-Code für die Visitenkarte"),
    ],
}

SCANNEN = {**_ART,
    "slug": "qr-code-scannen-handy.html",
    "crumb": "QR-Code mit dem Handy scannen",
    "title": "QR-Code mit dem Handy scannen: iPhone, Samsung und Android",
    "description": "So scannst du QR-Codes mit dem eigenen Handy: Kamera, Code-Scanner, Google Lens und aus Screenshots. Für iPhone, Samsung und andere Android-Handys, mit Lösungen.",
    "og_title": "QR-Code mit dem Handy scannen | SmartQRCraft",
    "og_description": "Alle eingebauten Wege, QR-Codes auf iPhone und Android zu scannen, auch aus Screenshots.",
    "h1": "QR-Code mit dem Handy scannen",
    "lead": "Du brauchst keine extra App. iPhone und die meisten Android-Handys lesen QR-Codes mit der Kamera. Dazu kommen eingebaute Wege für Fotos und Screenshots.",
    "faq_h2": "Fragen zum Scannen",
    "sections": [
        {"kind": "prose", "id": "iphone", "h2": "QR-Code scannen mit dem iPhone",
         "steps": [
             "Öffne die <strong>Kamera</strong>-App im Foto-Modus.",
             "Richte die Rückkamera auf den Code und halte kurz still. Ein Foto musst du nicht machen.",
             "Tippe auf den gelben Link oder Button, der erscheint.",
         ],
         "after": ["Passiert nichts? Prüfe unter <strong>Einstellungen &gt; Kamera</strong>, ob <strong>QR-Codes scannen</strong> eingeschaltet ist. Im dunklen Restaurant hilft der <strong>Code-Scanner</strong> im Kontrollzentrum, denn er hat eine Taschenlampe."]},
        {"kind": "prose", "id": "android", "h2": "QR-Code scannen mit Android",
         "steps": [
             "Öffne die Kamera und richte sie auf den Code.",
             "Tippe auf den Link, der erscheint.",
             "Kein Link? Öffne die Schnelleinstellungen (zweimal von oben wischen) und tippe auf <strong>QR-Code scannen</strong>. Fehlt die Kachel, füge sie über das Stift-Symbol hinzu.",
         ],
         "after": ["Bei Samsung Galaxy schaltest du in den Kamera-Einstellungen <strong>QR-Codes scannen</strong> ein. Bei Pixel-Handys übernimmt Google Lens das Erkennen. Menüs ändern sich zwischen Versionen; such in den Einstellungen nach &quot;QR&quot;."]},
        {"kind": "prose", "id": "screenshot", "h2": "QR-Code aus einem Screenshot oder Foto scannen",
         "p": ["Wenn der Code schon auf deinem Handy ist, etwa in einem Screenshot oder Chat:"],
         "bullets": [
             "<strong>iPhone:</strong> Öffne das Bild in der Fotos-App und halte den Finger auf den Code. Bei neueren iOS-Versionen erscheint dann der Link.",
             "<strong>Android:</strong> Öffne den Screenshot in Google Fotos und tippe auf <strong>Lens</strong>.",
             "<strong>Überall:</strong> Öffne unseren <a href=\"qr-code-scanner-online.html\">QR-Code Scanner online</a> und wähle das Bild aus. Es wird auf deinem Handy gelesen, nichts wird hochgeladen.",
         ]},
        {"kind": "table", "h2": "Das Handy scannt nicht? So klappt es",
         "cols": ["Problem", "Lösung"],
         "rows": [
             ["Die Kamera reagiert nicht", "QR-Scannen in den Kamera-Einstellungen einschalten; Foto-Modus statt Porträt oder Video"],
             ["Zu nah oder zu weit", "Zurückgehen, bis der ganze Code mit weißem Rand im Bild ist"],
             ["Dunkel oder spiegelnd", "Taschenlampe einschalten, das Handy leicht kippen"],
             ["Code auf einem Bildschirm", "Helligkeit des anderen Bildschirms erhöhen, etwas Abstand nehmen"],
             ["Kleiner oder beschädigter Code", "Ein scharfes Foto machen und im Online-Scanner öffnen"],
             ["Der Link tut nichts", "Inhalt mit einem Scanner mit Vorschau prüfen; vielleicht ist die Seite offline"],
         ]},
        {"kind": "prose", "id": "sicherheit", "h2": "Vor dem Tippen: kurz prüfen",
         "p": ["Die Vorschau zeigt die Webadresse. Lies sie, bevor du sie öffnest. Sei vorsichtig bei Codes auf Parkautomaten, Aufklebern und unerwarteter Post, und gib nach dem Scannen eines fremden Codes keine Passwörter oder Bankdaten ein. Wer einen Code vorher prüfen will, nutzt den <a href=\"qr-code-scanner-online.html\">Scanner mit Vorschau</a>."]},
    ],
    "faq": [
        ("Brauche ich eine App zum QR-Code scannen?",
         "Nein. iPhone und die meisten Android-Handys scannen QR-Codes mit der eingebauten Kamera."),
        ("Wie scanne ich einen QR-Code mit dem eigenen Handy, wenn er auf dem Handy ist?",
         "Mach einen Screenshot und öffne ihn in der Fotos-App (iPhone) oder mit Google Lens (Android), oder nutze einen Online-Scanner und wähle das Bild."),
        ("Warum erkennt meine Kamera keine QR-Codes?",
         "Oft ist das QR-Scannen in den Kamera-Einstellungen ausgeschaltet, oder der Code ist zu klein, unscharf oder zu dunkel."),
        ("Wie scanne ich einen QR-Code mit einem Samsung-Handy?",
         "Öffne die Kamera und richte sie auf den Code. Klappt das nicht, schalte in den Kamera-Einstellungen QR-Codes scannen ein oder nutze die Kachel in den Schnelleinstellungen."),
        ("Ist QR-Code-Scannen sicher?",
         "Meistens ja. Prüfe aber die Adresse in der Vorschau und sei vorsichtig bei Codes, die über andere Codes geklebt wurden."),
    ],
    "related": [("qr-code-scanner-online.html", "QR-Code Scanner online"), ("qr-code-testen.html", "QR-Code testen"), ("wlan-qr-code-generator.html", "WLAN QR-Code Generator")],
}

WIDGET = {**_D,
    "slug": "qr-code-widget-website.html",
    "crumb": "QR-Code Widget für die Website",
    "widget": "embed",
    "type": "url",
    "tool_name": "QR-Code Widget",
    "field_label": "", "field_placeholder": "", "cta": "", "empty": "",
    "title": "QR-Code Widget für deine Website kostenlos | Einbinden per HTML — SmartQRCraft",
    "description": "QR-Code in die eigene Website einbinden: Zwei Zeilen HTML zeigen einen QR-Code der aktuellen Seite, damit Besucher am Handy weiterlesen. Kostenlos, ohne API-Schlüssel.",
    "og_title": "QR-Code Widget für Websites | SmartQRCraft",
    "og_description": "Zwei Zeilen HTML: ein QR-Code der aktuellen Seite auf deiner Website. Kostenlos, ohne Tracking.",
    "h1": '<span class="accent">QR-Code Widget</span> für deine Website',
    "lead": "Füge zwei Zeilen HTML ein, und deine Seite zeigt einen QR-Code von sich selbst. Besucher am Computer scannen ihn und lesen am Handy weiter. Funktioniert mit WordPress, Shopify, Wix, Jimdo und normalem HTML.",
    "faq_h2": "Fragen zum QR-Code Widget",
    "sections": [
        {"kind": "prose", "id": "anleitung", "h2": "So bindest du das Widget ein",
         "steps": [
             "Wähle oben die Einstellungen: automatisch (die aktuelle Seite) oder ein fester Link, Größe, Farbe und Beschriftung.",
             "Klicke auf <strong>Code kopieren</strong>.",
             "Füge den Code dort in deine Seite ein, wo der QR-Code erscheinen soll, zum Beispiel in die Seitenleiste, den Footer oder eine Produktseite.",
             "Öffne die Seite und scanne den Code mit dem Handy.",
         ]},
        {"kind": "table", "h2": "Wo du den Code einfügst",
         "cols": ["System", "Wo der Code hinkommt"],
         "rows": [
             ["WordPress", "In einen <strong>Individuelles HTML</strong>-Block oder ein HTML-Widget in Seitenleiste oder Footer"],
             ["Shopify", "Onlineshop &gt; Themes &gt; Anpassen, dann ein <strong>Benutzerdefiniertes Liquid</strong>-Abschnitt"],
             ["Wix", "Hinzufügen &gt; Einbetten &gt; <strong>HTML einbetten</strong>"],
             ["Jimdo", "Element hinzufügen &gt; <strong>Widget/HTML</strong>"],
             ["Eigenes HTML", "Irgendwo innerhalb von &lt;body&gt;"],
         ]},
        {"kind": "prose", "id": "datenschutz", "h2": "Datenschutz und Ladezeit",
         "p": ["Das Widget ist ein einzelnes kleines Skript ohne Cookies, ohne Tracking und ohne Aufrufe anderer Dienste. Der QR-Code wird im Browser des Besuchers gezeichnet, Seitenadressen werden nicht an uns oder Dritte gesendet. Das Skript lädt mit <code>async</code> und bremst deine Seite nicht aus.",
               "Beim Laden des Skripts von unserem Server wird wie bei jeder eingebundenen Datei die IP-Adresse des Besuchers übertragen. Erwähne das Widget deshalb in deiner Datenschutzerklärung, oder lade die Datei embed.js herunter und binde sie von deinem eigenen Server ein."]},
    ],
    "faq": [
        ("Ist das QR-Code Widget kostenlos?",
         "Ja, für private und gewerbliche Websites, ohne API-Schlüssel und ohne Anmeldung."),
        ("Setzt das Widget Cookies?",
         "Nein. Es setzt keine Cookies und sendet keine Daten. Der Code entsteht im Browser des Besuchers."),
        ("Zeigt ein Code-Schnipsel auf jeder Seite einen anderen QR-Code?",
         "Ja. Im automatischen Modus zeigt jede Seite einen Code ihrer eigenen Adresse. Du kannst den Schnipsel also in ein gemeinsames Template einbauen."),
        ("Kann ich den SmartQRCraft-Link entfernen?",
         "Ja, mit data-credit=\"off\". Wir freuen uns aber, wenn du ihn drin lässt."),
        ("Muss ich das Widget in der Datenschutzerklärung erwähnen?",
         "Wenn du die Datei von unserem Server lädst, ist ein kurzer Hinweis sinnvoll, weil dabei die IP-Adresse übertragen wird. Alternativ hostest du embed.js selbst."),
    ],
    "related": [
        ("index.html#generator", "Kostenloser QR-Code Generator"),
        ("qr-code-mit-logo.html", "QR-Code mit Logo"),
        ("qr-code-scanner-online.html", "QR-Code Scanner online"),
    ],
}

DE_PAGES_2 = [TELEFON, EMAIL, SMS, TEXT, APP, DRUCKEN, VORLAGEN, SCANNEN, WIDGET]
