"""German (smartqrcraft.de) pages from the head-term research (research/keywords-de-head.csv, Sept 2026):
dauerhaft 2.6K kd52-60, wie erstelle ich einen qr code 2.1K kd24-53, link in qr code 5.5K kd55-64,
canva 1.3K kd35, qr code beispiel 720 kd36, bild als qr code 590 kd36."""

_D = {"domain": "smartqrcraft.de", "lang": "de"}
_ART = {**_D, "static": True, "noindex": False, "type": "url"}

DAUERHAFT = {**_D,
    "slug": "qr-code-erstellen-kostenlos-dauerhaft.html",
    "crumb": "QR-Code dauerhaft kostenlos",
    "type": "url",
    "types": "url,text,wifi,email,phone,sms,vcard,location,pdf,app",
    "lock": False,
    "tool_name": "Dauerhafter QR-Code Generator",
    "field_label": "", "field_placeholder": "",
    "cta": "JETZT SCANNEN",
    "empty": "Gib deine Daten ein, um den QR-Code zu erstellen.",
    "title": "QR-Code erstellen kostenlos und dauerhaft | Ohne Ablaufdatum, ohne Abo",
    "description": "QR-Code kostenlos und dauerhaft erstellen: statische Codes ohne Ablaufdatum, ohne Abo und ohne Anmeldung. So erkennst du Codes, die nach einer Testphase abschalten.",
    "og_title": "QR-Code dauerhaft kostenlos erstellen | SmartQRCraft",
    "og_description": "Statische QR-Codes, die nie ablaufen. Kostenlos, ohne Abo, ohne Anmeldung.",
    "h1": 'QR-Code erstellen: <span class="accent">kostenlos und dauerhaft</span>',
    "lead": "Die Codes aus diesem Generator laufen nie ab. Sie brauchen kein Konto, kein Abo und keinen Server von uns, denn der Inhalt steckt direkt im Code.",
    "faq_h2": "Fragen zu dauerhaften QR-Codes",
    "sections": [
        {"kind": "prose", "id": "warum", "h2": "Warum funktionieren manche kostenlosen QR-Codes plötzlich nicht mehr?",
         "p": ["Viele Anbieter erstellen im Testzeitraum <strong>dynamische</strong> QR-Codes. Solche Codes enthalten nicht deinen Link, sondern eine Kurz-Adresse des Anbieters, die erst weiterleitet. Endet die Testphase oder das Abo, schaltet der Anbieter die Weiterleitung ab oder zeigt eine Seite mit Zahlungsaufforderung. Die gedruckten Codes sind dann nutzlos.",
               "Ein <strong>statischer</strong> QR-Code enthält den Inhalt selbst, also zum Beispiel deinen Link, deine WLAN-Daten oder deine Kontaktdaten. Er hängt von keinem Server ab und kann deshalb nicht abgeschaltet werden."]},
        {"kind": "table", "h2": "Statisch oder dynamisch: der Unterschied",
         "cols": ["", "Statischer QR-Code (hier)", "Dynamischer QR-Code"],
         "rows": [
             ["Läuft ab?", "Nie", "Wenn Abo oder Testphase endet"],
             ["Kosten", "Kostenlos", "Meist Abo"],
             ["Inhalt änderbar?", "Nein, neuer Code nötig", "Ja, Ziel lässt sich ändern"],
             ["Scan-Statistik?", "Nein", "Ja"],
             ["Abhängig vom Anbieter?", "Nein", "Ja"],
         ]},
        {"kind": "prose", "id": "erkennen", "h2": "So erkennst du, ob dein QR-Code dauerhaft ist",
         "steps": [
             "Scanne den Code mit unserem <a href=\"qr-code-scanner-online.html\">QR-Code Scanner</a>. Er zeigt den Inhalt, ohne ihn zu öffnen.",
             "Steht dort <strong>deine eigene Adresse</strong> (zum Beispiel deinefirma.de/speisekarte) oder deine WLAN- bzw. Kontaktdaten, ist der Code statisch und dauerhaft.",
             "Steht dort eine <strong>fremde Kurz-Adresse</strong> eines QR-Anbieters, ist der Code dynamisch und hängt von diesem Anbieter ab.",
         ]},
        {"kind": "prose", "id": "tipp", "h2": "Tipp: dauerhaft und trotzdem änderbar",
         "p": ["Du willst den Inhalt später ändern können, ohne neu zu drucken? Erstelle einen statischen Code für eine Adresse auf <strong>deiner eigenen Domain</strong>, zum Beispiel deinefirma.de/menu. Wohin diese Adresse führt, stellst du auf deiner Website ein. Der gedruckte Code bleibt dauerhaft gültig, solange dir die Domain gehört."]},
        {"kind": "cards", "eyebrow": "Dauerhaft kostenlos", "h2": "Was du hier dauerhaft kostenlos bekommst",
         "cards": [
             ("Kein Ablaufdatum", "Der Code funktioniert, solange der Inhalt gültig ist."),
             ("Keine Anmeldung", "Kein Konto, keine E-Mail-Adresse, kein Abo."),
             ("Kein Wasserzeichen", "Auch nicht beim Download in hoher Auflösung."),
             ("Gewerblich nutzbar", "Für Speisekarten, Flyer, Verpackungen und Visitenkarten."),
             ("PNG, SVG, PDF, EPS", "Druckfertige Vektordateien inklusive."),
             ("Datenschutz", "Der Code entsteht in deinem Browser. Nichts wird hochgeladen."),
         ]},
    ],
    "faq": [
        ("Kann ich einen QR-Code kostenlos und dauerhaft erstellen?",
         "Ja. Die Codes aus diesem Generator sind statisch: Sie enthalten den Inhalt selbst und laufen nie ab. Es gibt keine Anmeldung und kein Abo."),
        ("Warum hat mein alter QR-Code aufgehört zu funktionieren?",
         "Meist war es ein dynamischer Code eines Anbieters, dessen Testphase oder Abo abgelaufen ist. Die Weiterleitung wurde abgeschaltet. Prüfe den Inhalt mit einem Scanner."),
        ("Kann ich den Inhalt eines dauerhaften QR-Codes ändern?",
         "Nein, der Inhalt steckt im Code. Mit einem Link auf deine eigene Domain kannst du aber das Ziel auf deiner Website ändern."),
        ("Darf ich die QR-Codes gewerblich nutzen?",
         "Ja, auch für Werbung, Verpackungen und Speisekarten."),
        ("Sieht man, wie oft der Code gescannt wurde?",
         "Nicht bei statischen Codes. Zähle stattdessen die Besuche der Zielseite, zum Beispiel mit einem eigenen Link-Parameter in deiner Website-Statistik."),
    ],
    "related": [
        ("link-in-qr-code-umwandeln.html", "Link in QR-Code umwandeln"),
        ("qr-code-scanner-online.html", "QR-Code Scanner online"),
        ("wie-erstelle-ich-einen-qr-code.html", "Wie erstelle ich einen QR-Code?"),
    ],
}

LINK = {**_D,
    "slug": "link-in-qr-code-umwandeln.html",
    "crumb": "Link in QR-Code umwandeln",
    "type": "url",
    "tool_name": "Link in QR-Code umwandeln",
    "field_label": "Dein Link (URL)",
    "field_placeholder": "https://deinefirma.de/angebot",
    "cta": "JETZT SCANNEN",
    "empty": "Füge einen Link ein, um den QR-Code zu erstellen.",
    "title": "Link in QR-Code umwandeln kostenlos | URL zu QR-Code — SmartQRCraft",
    "description": "Link in QR-Code umwandeln: URL einfügen, Design wählen, als PNG oder SVG herunterladen. Kostenlos, ohne Anmeldung, der QR-Code mit Link läuft nie ab.",
    "og_title": "Link in QR-Code umwandeln | SmartQRCraft",
    "og_description": "Aus jeder URL einen QR-Code machen. Kostenlos, ohne Anmeldung, dauerhaft.",
    "h1": '<span class="accent">Link in QR-Code</span> umwandeln',
    "lead": "Füge eine Webadresse ein und lade den QR-Code herunter. Wer ihn scannt, landet direkt auf deiner Seite, ohne die Adresse abzutippen.",
    "faq_h2": "Fragen zum QR-Code mit Link",
    "sections": [
        {"kind": "prose", "id": "anleitung", "h2": "So machst du aus einem Link einen QR-Code",
         "steps": [
             "Kopiere die Adresse aus der Adresszeile deines Browsers.",
             "Füge sie oben ein. Fehlt <code>https://</code>, ergänzen wir es automatisch.",
             "Wähle Farben, einen Rahmen mit Text und bei Bedarf dein Logo.",
             "Lade PNG für Bildschirme oder SVG und PDF für den Druck herunter.",
             "Scanne den Code einmal zur Kontrolle, bevor du ihn verteilst.",
         ]},
        {"kind": "table", "h2": "Welcher Link eignet sich?",
         "cols": ["Link", "Gut für", "Hinweis"],
         "rows": [
             ["Startseite", "Visitenkarten, Firmenschilder", "Kurz und dauerhaft"],
             ["Unterseite (Angebot, Speisekarte)", "Flyer, Tischaufsteller", "Seite sollte am Handy gut aussehen"],
             ["Google-Maps-Link", "Anfahrt", "Oder den Standort-Typ im <a href=\"index.html#generator\">Generator</a> nutzen"],
             ["Link zu PDF", "Preislisten, Broschüren", "Siehe <a href=\"pdf-in-qr-code.html\">PDF in QR-Code</a>"],
             ["Link mit Kampagnen-Parameter", "Messen, ob Scans Besuche bringen", "z. B. ?utm_source=flyer"],
         ]},
        {"kind": "prose", "id": "kurz", "h2": "Kurze Links machen bessere QR-Codes",
         "p": ["Je länger die Adresse, desto dichter wird der Code und desto größer musst du ihn drucken. Lange Adressen mit vielen Parametern lohnen sich zu kürzen. Am besten nutzt du eine kurze Adresse auf deiner eigenen Domain, etwa deinefirma.de/flyer, und leitest sie auf die lange Seite weiter. So bleibt der Code klein und dauerhaft gültig."]},
        {"kind": "prose", "id": "sicherheit", "h2": "Link vor dem Druck prüfen",
         "bullets": [
             "<strong>Funktioniert die Seite am Handy?</strong> Die meisten Scans kommen vom Smartphone.",
             "<strong>Bleibt die Adresse gültig?</strong> Aktionsseiten werden oft gelöscht, dann führt der Code ins Leere.",
             "<strong>Stimmt die Schreibweise?</strong> Ein Tippfehler im Link ist nach dem Druck nicht mehr zu korrigieren.",
         ]},
    ],
    "faq": [
        ("Wie wandle ich einen Link in einen QR-Code um?",
         "Füge den Link in das Feld oben ein und lade den QR-Code herunter. Das dauert wenige Sekunden."),
        ("Ist der QR-Code mit Link kostenlos?",
         "Ja, ohne Anmeldung, ohne Wasserzeichen und ohne Ablaufdatum."),
        ("Kann ich den Link später ändern?",
         "Nicht im Code selbst. Wenn der Code auf eine Adresse deiner eigenen Domain zeigt, kannst du dort eine Weiterleitung ändern."),
        ("Warum ist mein QR-Code so dicht?",
         "Der Link ist lang. Kürze ihn, zum Beispiel mit einer kurzen Adresse auf deiner Domain."),
        ("Kann ich einen QR-Code für eine Instagram- oder Facebook-Seite erstellen?",
         "Ja. Kopiere einfach den Link zu deinem Profil und füge ihn oben ein."),
    ],
    "related": [
        ("qr-code-erstellen-kostenlos-dauerhaft.html", "QR-Code dauerhaft kostenlos"),
        ("qr-code-mit-logo.html", "QR-Code mit Logo"),
        ("pdf-in-qr-code.html", "PDF in QR-Code umwandeln"),
    ],
}

WIE = {**_ART,
    "slug": "wie-erstelle-ich-einen-qr-code.html",
    "crumb": "Wie erstelle ich einen QR-Code?",
    "title": "Wie erstelle ich einen QR-Code? Anleitung in 4 Schritten (kostenlos)",
    "description": "Wie erstellt man einen QR-Code? Schritt-für-Schritt-Anleitung: Inhalt wählen, gestalten, herunterladen und testen. Mit Vergleich der Wege: online, am Handy, in Canva.",
    "og_title": "Wie erstelle ich einen QR-Code? | SmartQRCraft",
    "og_description": "QR-Code erstellen in 4 Schritten, plus die besten Wege am Computer und Handy.",
    "h1": "Wie erstelle ich einen QR-Code?",
    "lead": "Einen QR-Code zu erstellen dauert keine Minute. Hier ist die Anleitung in vier Schritten, dazu die verschiedenen Wege im Vergleich und die häufigsten Fehler.",
    "faq_h2": "Häufige Fragen",
    "sections": [
        {"kind": "prose", "id": "schritte", "h2": "QR-Code erstellen in 4 Schritten",
         "steps": [
             "<strong>Inhalt wählen:</strong> Was soll beim Scannen passieren? Eine Webseite öffnen, ins WLAN verbinden, einen Kontakt speichern oder anrufen. Öffne dazu den <a href=\"index.html#generator\">QR-Code Generator</a> und wähle die Art.",
             "<strong>Daten eingeben:</strong> zum Beispiel den Link, den WLAN-Namen mit Passwort oder deine Kontaktdaten.",
             "<strong>Gestalten:</strong> Farbe, Form, Rahmen mit Aufforderung wie &quot;Scan mich&quot; und optional ein Logo. Bleib bei dunklem Code auf hellem Grund.",
             "<strong>Herunterladen und testen:</strong> PNG für Bildschirm und Office, SVG oder PDF für den Druck. Scanne den Code vor dem Verteilen mit zwei Handys.",
         ]},
        {"kind": "table", "h2": "Welche Art von QR-Code brauchst du?",
         "cols": ["Du willst ...", "QR-Code-Art", "Seite"],
         "rows": [
             ["auf eine Webseite verlinken", "Link (URL)", "<a href=\"link-in-qr-code-umwandeln.html\">Link in QR-Code</a>"],
             ["Gäste ins WLAN lassen", "WLAN", "<a href=\"wlan-qr-code-generator.html\">WLAN QR-Code</a>"],
             ["Kontaktdaten teilen", "Visitenkarte (vCard)", "<a href=\"visitenkarte-qr-code-generator.html\">QR-Code Visitenkarte</a>"],
             ["Überweisungen erleichtern", "GiroCode", "<a href=\"qr-code-ueberweisung-erstellen.html\">QR-Code Überweisung</a>"],
             ["ein Dokument teilen", "PDF-Link", "<a href=\"pdf-in-qr-code.html\">PDF in QR-Code</a>"],
             ["Anrufe bekommen", "Telefon", "<a href=\"qr-code-telefonnummer.html\">QR-Code Telefonnummer</a>"],
         ]},
        {"kind": "table", "h2": "Die Wege im Vergleich",
         "cols": ["Weg", "Vorteile", "Nachteile"],
         "rows": [
             ["Online-Generator (wie dieser)", "Alle Arten, eigenes Design, Druckdateien, kostenlos", "Braucht einen Browser"],
             ["Browser-Funktion (Chrome: Teilen &gt; QR-Code erstellen)", "Schnell für die aktuelle Seite", "Nur Links, kein Design, kleine Datei"],
             ["Grafikprogramm (Canva, Adobe Express)", "Direkt im Layout", "Wenig Arten, teils kostenpflichtig; siehe <a href=\"qr-code-in-canva.html\">QR-Code in Canva</a>"],
             ["Abo-Anbieter mit dynamischen Codes", "Ziel änderbar, Statistik", "Kostet meist Geld, Code kann nach dem Abo abschalten"],
         ]},
        {"kind": "prose", "id": "fehler", "h2": "Die 5 häufigsten Fehler",
         "bullets": [
             "<strong>Zu klein gedruckt:</strong> unter 2 cm wird es schwierig. Mehr dazu unter <a href=\"qr-code-drucken.html\">QR-Code drucken</a>.",
             "<strong>Kein weißer Rand:</strong> Der Code braucht rundherum eine Ruhezone.",
             "<strong>Zu wenig Kontrast:</strong> hellgrau auf weiß oder helle Codes auf dunklem Grund.",
             "<strong>Nicht getestet:</strong> ein Tippfehler im Link fällt erst nach dem Druck auf.",
             "<strong>Dynamischer Probecode:</strong> Er hört auf zu funktionieren, wenn die Testphase endet. Statische Codes laufen nie ab, siehe <a href=\"qr-code-erstellen-kostenlos-dauerhaft.html\">QR-Code dauerhaft kostenlos</a>.",
         ]},
        {"kind": "cta", "h2": "Jetzt deinen QR-Code erstellen",
         "p": "Kostenlos, ohne Anmeldung und ohne Ablaufdatum.",
         "href": "index.html#generator", "label": "Zum QR-Code Generator"},
    ],
    "faq": [
        ("Wie erstellt man einen QR-Code kostenlos?",
         "Öffne einen kostenlosen Generator wie den von SmartQRCraft, wähle die Art, gib deine Daten ein und lade den Code herunter. Eine Anmeldung ist nicht nötig."),
        ("Kann ich einen QR-Code mit dem Handy erstellen?",
         "Ja. Der Generator funktioniert auch im Handy-Browser. In Chrome kannst du außerdem über Teilen einen QR-Code für die aktuelle Seite erstellen."),
        ("Wie lange ist ein QR-Code gültig?",
         "Ein statischer QR-Code ist unbegrenzt gültig. Dynamische Codes von Abo-Anbietern können abschalten, wenn das Abo endet."),
        ("Brauche ich eine App, um einen QR-Code zu erstellen?",
         "Nein. Ein Browser reicht."),
        ("Kann ich mein Logo in den QR-Code einfügen?",
         "Ja, siehe <a href=\"qr-code-mit-logo.html\">QR-Code mit Logo</a>. Halte das Logo klein, damit der Code lesbar bleibt."),
    ],
    "related": [("index.html#generator", "QR-Code Generator"), ("qr-code-beispiele.html", "QR-Code Beispiele"), ("qr-code-testen.html", "QR-Code testen")],
}

CANVA = {**_ART,
    "slug": "qr-code-in-canva.html",
    "crumb": "QR-Code in Canva",
    "title": "QR-Code in Canva erstellen und einfügen: 2 Wege (Anleitung)",
    "description": "QR-Code in Canva einfügen: mit der eingebauten QR-Code-App oder als gestaltetes SVG mit Logo und Farben. Schritt-für-Schritt, mit Tipps für den Druck.",
    "og_title": "QR-Code in Canva erstellen | SmartQRCraft",
    "og_description": "Zwei Wege, einen QR-Code in Canva zu nutzen, und wann welcher besser ist.",
    "h1": "QR-Code in Canva erstellen und einfügen",
    "lead": "Canva hat eine eingebaute QR-Code-Funktion für Links, als statischen oder dynamischen Code. Für WLAN, Visitenkarten, Überweisungen oder ein kostenloses Logo erstellst du den Code besser separat und lädst ihn als SVG in Canva hoch.",
    "faq_h2": "Fragen zu QR-Codes in Canva",
    "sections": [
        {"kind": "prose", "id": "weg1", "h2": "Weg 1: die QR-Code-App in Canva",
         "steps": [
             "Öffne dein Design in Canva.",
             "Öffne links <strong>Elemente</strong> und suche nach &quot;QR-Code&quot; (oder suche unter <strong>Apps</strong>).",
             "Wähle einen <strong>statischen</strong> Code (fester Link) oder einen <strong>dynamischen</strong> Code (Link später änderbar).",
             "Füge deinen Link ein, passe Farben und Ecken an und erstelle den Code. Er erscheint in deinem Design.",
         ],
         "after": ["Menünamen können sich bei Canva ändern. Canva erstellt Codes für Links. Scan-Statistiken, ein Ablaufdatum und ein eigenes Logo im Code nennt Canva als Funktionen der Business- und Enterprise-Tarife. Ein dynamischer Code hängt vom Canva-Dienst ab, ein statischer nicht."]},
        {"kind": "prose", "id": "weg2", "h2": "Weg 2: gestalteten QR-Code als SVG hochladen",
         "steps": [
             "Erstelle deinen Code im <a href=\"index.html#generator\">QR-Code Generator</a>: Link, WLAN, Visitenkarte, Überweisung und mehr, mit Farben, Rahmen und Logo.",
             "Lade ihn als <strong>SVG</strong> herunter. SVG bleibt in jeder Größe scharf.",
             "Ziehe die Datei in Canva in deine Uploads und von dort in dein Design.",
             "Skaliere den Code proportional und lass rundherum einen weißen Rand.",
         ]},
        {"kind": "table", "h2": "Welcher Weg passt?",
         "cols": ["", "Canva-App", "SVG von SmartQRCraft"],
         "rows": [
             ["Link-QR-Code", "Ja", "Ja"],
             ["WLAN, Visitenkarte, GiroCode, Telefon", "Nein", "Ja"],
             ["Eigene Farben", "Farben und Ecken", "Farben, Verläufe, Formen, Rahmen"],
             ["Logo in der Mitte", "In Business- und Enterprise-Tarifen", "Ja, kostenlos"],
             ["Link später ändern", "Mit dynamischem Code", "Nein (statisch, läuft nie ab)"],
             ["Druckfertige Vektordatei", "Im Canva-Export", "SVG, PDF, EPS"],
         ]},
        {"kind": "prose", "id": "druck", "h2": "Tipps für den Druck aus Canva",
         "bullets": [
             "Exportiere für die Druckerei als <strong>PDF (Druck)</strong>.",
             "Lege keine Effekte, Transparenz oder Schatten auf den Code.",
             "Platziere den Code nicht über Fotos oder Muster, sondern auf einer ruhigen, hellen Fläche.",
             "Drucke eine Probe in Originalgröße und scanne sie. Mehr dazu unter <a href=\"qr-code-drucken.html\">QR-Code drucken</a>.",
         ]},
    ],
    "faq": [
        ("Kann man in Canva einen QR-Code erstellen?",
         "Ja. Suche unter Elemente oder Apps nach &quot;QR-Code&quot;. Canva erstellt statische und dynamische Codes für Links."),
        ("Wie füge ich einen eigenen QR-Code in Canva ein?",
         "Lade den Code als SVG oder PNG herunter, lade ihn in Canva unter Uploads hoch und ziehe ihn in dein Design."),
        ("Kann ich in Canva einen WLAN-QR-Code machen?",
         "Nicht mit der eingebauten App. Erstelle ihn mit dem <a href=\"wlan-qr-code-generator.html\">WLAN QR-Code Generator</a> und lade ihn als SVG hoch."),
        ("Ist der QR-Code aus Canva dauerhaft?",
         "Ein Code für einen Link enthält den Link selbst und läuft nicht ab, solange die Seite existiert."),
    ],
    "related": [("qr-code-drucken.html", "QR-Code drucken"), ("qr-code-mit-logo.html", "QR-Code mit Logo"), ("qr-code-vorlagen-drucken.html", "QR-Code Vorlagen zum Drucken")],
}

BEISPIELE = {**_ART,
    "slug": "qr-code-beispiele.html",
    "crumb": "QR-Code Beispiele",
    "title": "QR-Code Beispiele: 6 Arten zum Ausprobieren und Scannen",
    "description": "QR-Code Beispiele zum Scannen: Link, WLAN, Visitenkarte, Telefon, E-Mail und Text. Sieh, was jeder Code enthält, und erstelle deinen eigenen kostenlos.",
    "og_title": "QR-Code Beispiele zum Scannen | SmartQRCraft",
    "og_description": "Sechs echte Beispiel-QR-Codes zum Scannen, mit Erklärung und Generator.",
    "h1": "QR-Code Beispiele zum Scannen",
    "lead": "Hier sind sechs echte QR-Codes. Scanne sie mit der Handykamera und sieh, was passiert. Unter jedem Beispiel steht, was im Code steckt und wie du deinen eigenen erstellst.",
    "faq_h2": "Fragen zu den Beispielen",
    "sections": [
        {"kind": "gallery", "h2": "Sechs Beispiele",
         "p": ["Alle Beispiele sind harmlos: Die Telefonnummer ist eine für Film und Fernsehen reservierte Nummer, die E-Mail-Adresse gehört zur reservierten Domain example.com."],
         "items": [
             {"img": "assets/beispiele/link.svg", "alt": "Beispiel QR-Code mit Link zu smartqrcraft.de", "h3": "Link", "p": "Öffnet eine Webseite, hier smartqrcraft.de.", "href": "link-in-qr-code-umwandeln.html", "label": "Link-QR-Code erstellen"},
             {"img": "assets/beispiele/wlan.svg", "alt": "Beispiel WLAN QR-Code für das Netzwerk Cafe_Gast", "h3": "WLAN", "p": "Bietet an, sich mit dem Netzwerk Cafe_Gast zu verbinden (Passwort Beispiel2026).", "href": "wlan-qr-code-generator.html", "label": "WLAN-QR-Code erstellen"},
             {"img": "assets/beispiele/visitenkarte.svg", "alt": "Beispiel Visitenkarte QR-Code für Anna Beispiel", "h3": "Visitenkarte", "p": "Speichert den Kontakt Anna Beispiel, Muster GmbH, im Adressbuch.", "href": "visitenkarte-qr-code-generator.html", "label": "Visitenkarten-QR-Code erstellen"},
             {"img": "assets/beispiele/telefon.svg", "alt": "Beispiel QR-Code für eine Telefonnummer", "h3": "Telefon", "p": "Zeigt eine Nummer mit Anruf-Button. Angerufen wird erst nach einem Tipp.", "href": "qr-code-telefonnummer.html", "label": "Telefon-QR-Code erstellen"},
             {"img": "assets/beispiele/e-mail.svg", "alt": "Beispiel E-Mail QR-Code mit Betreff", "h3": "E-Mail", "p": "Öffnet eine neue E-Mail mit Empfänger und Betreff &quot;Anfrage&quot;.", "href": "e-mail-qr-code-erstellen.html", "label": "E-Mail-QR-Code erstellen"},
             {"img": "assets/beispiele/text.svg", "alt": "Beispiel Text QR-Code", "h3": "Text", "p": "Zeigt einen kurzen Text auf dem Bildschirm, ganz ohne Internet.", "href": "text-in-qr-code.html", "label": "Text-QR-Code erstellen"},
         ]},
        {"kind": "table", "h2": "Was steckt in den Beispielen?",
         "p": ["Ein QR-Code speichert nur Text. Das Handy erkennt am Anfang des Textes, was es tun soll:"],
         "cols": ["Beispiel", "Inhalt des Codes"],
         "rows": [
             ["Link", "<code>https://smartqrcraft.de</code>"],
             ["WLAN", "<code>WIFI:T:WPA;S:Cafe_Gast;P:Beispiel2026;;</code>"],
             ["Visitenkarte", "<code>BEGIN:VCARD ... END:VCARD</code> mit Name, Firma, Telefon und E-Mail"],
             ["Telefon", "<code>tel:+493023125123</code>"],
             ["E-Mail", "<code>mailto:hallo@example.com?subject=Anfrage</code>"],
             ["Text", "Der Text selbst"],
         ]},
        {"kind": "cards", "eyebrow": "Aus der Praxis", "h2": "Beispiele für den Einsatz",
         "cards": [
             ("Restaurant", "Speisekarte als Link, WLAN für Gäste, Bewertungslink an der Kasse."),
             ("Handwerk", "Telefon-QR-Code am Firmenwagen, Visitenkarte mit Kontakt-Code."),
             ("Einzelhandel", "Produktinfos auf dem Regal, GiroCode auf der Rechnung."),
             ("Veranstaltungen", "Programm als Link, Anmeldung per E-Mail-Code."),
             ("Vermietung", "WLAN-Karte und Hausordnung als Text in der Ferienwohnung."),
             ("Vereine", "Spendenkonto als GiroCode, Mitgliedsantrag als PDF-Link."),
         ]},
    ],
    "faq": [
        ("Kann ich die Beispiel-QR-Codes scannen?",
         "Ja. Sie sind echt und harmlos. Die Telefonnummer ist für Film und Fernsehen reserviert, die E-Mail-Domain ist eine reservierte Beispiel-Domain."),
        ("Wie sieht ein QR-Code aus?",
         "Ein Quadrat aus schwarzen und weißen Modulen mit drei großen Eckquadraten, an denen der Scanner die Lage erkennt."),
        ("Darf ich die Beispiele verwenden?",
         "Als Anschauung ja. Für deine eigenen Zwecke erstellst du besser einen eigenen Code mit deinen Daten."),
        ("Kann ein QR-Code farbig sein?",
         "Ja, wie die Beispiele zeigen. Wichtig ist ein dunkler Code auf hellem Grund."),
    ],
    "related": [("wie-erstelle-ich-einen-qr-code.html", "Wie erstelle ich einen QR-Code?"), ("index.html#generator", "QR-Code Generator"), ("qr-code-scanner-online.html", "QR-Code Scanner online")],
}

BILD = {**_D,
    "slug": "bild-als-qr-code.html",
    "crumb": "Bild als QR-Code",
    "type": "url",
    "tool_name": "Bild als QR-Code",
    "field_label": "Link zu deinem Bild",
    "field_placeholder": "https://photos.app.goo.gl/deinbild",
    "cta": "BILD ANSEHEN",
    "empty": "Füge den Link zu deinem Bild ein.",
    "title": "Bild als QR-Code erstellen kostenlos | Foto per QR-Code teilen — SmartQRCraft",
    "description": "Bild als QR-Code: Foto online teilen, Link einfügen, QR-Code herunterladen. Oder dein Foto als Hintergrund im QR-Code gestalten. Kostenlos und ohne Anmeldung.",
    "og_title": "Bild als QR-Code erstellen | SmartQRCraft",
    "og_description": "Ein Foto per QR-Code teilen, oder ein Foto hinter den QR-Code legen. Kostenlos.",
    "h1": '<span class="accent">Bild als QR-Code</span> erstellen',
    "lead": "Ein QR-Code kann kein Foto speichern, dafür ist er zu klein. Du kannst aber ein Bild online teilen und den Link als QR-Code drucken. Oder du nutzt dein Foto als Hintergrund eines QR-Codes.",
    "faq_h2": "Fragen zum Bild-QR-Code",
    "sections": [
        {"kind": "prose", "id": "teilen", "h2": "Weg 1: ein Bild per QR-Code teilen",
         "steps": [
             "Lade das Bild in einen Online-Speicher hoch, zum Beispiel Google Fotos, Google Drive, Dropbox, OneDrive oder deine eigene Website.",
             "Erstelle dort einen Freigabe-Link und stelle ein, dass <strong>jeder mit dem Link</strong> das Bild sehen darf.",
             "Füge den Link oben ein und lade den QR-Code herunter.",
             "Teste den Code mit einem Handy, das nicht in deinem Konto angemeldet ist, damit du siehst, was Fremde sehen.",
         ]},
        {"kind": "prose", "id": "hintergrund", "h2": "Weg 2: dein Foto im QR-Code",
         "p": ["Im <a href=\"index.html#generator\">QR-Code Generator</a> findest du unter <strong>Logo</strong> die Option <strong>Bild-QR (Foto hinter dem Code)</strong>. Dein Foto scheint dann durch kleine Punkte hindurch. Der Code bleibt scannbar, sieht aber aus wie ein Bild. Download als PNG oder JPG; größere Punkte scannen zuverlässiger.",
               "Für ein kleines Logo in der Mitte nutzt du stattdessen <a href=\"qr-code-mit-logo.html\">QR-Code mit Logo</a>."]},
        {"kind": "table", "h2": "Was passt zu deinem Ziel?",
         "cols": ["Du willst ...", "So geht's"],
         "rows": [
             ["Fotos von einer Hochzeit oder Feier teilen", "Album-Link (z. B. Google Fotos) als QR-Code, Weg 1"],
             ["ein Plakat oder Menü als Bild zeigen", "Bild oder PDF online stellen, Link als QR-Code"],
             ["einen QR-Code, der wie ein Foto aussieht", "Bild-QR im Generator, Weg 2"],
             ["dein Logo im Code", "QR-Code mit Logo"],
         ]},
        {"kind": "prose", "id": "datenschutz", "h2": "Datenschutz beim Teilen von Bildern",
         "bullets": [
             "Jeder, der den Code scannt, kann das Bild sehen. Teile keine privaten Fotos über öffentlich ausgehängte Codes.",
             "Frage Personen auf Fotos, ob sie mit dem Teilen einverstanden sind.",
             "Du kannst den Zugriff jederzeit beenden, indem du die Freigabe im Online-Speicher aufhebst.",
         ]},
    ],
    "faq": [
        ("Kann ich ein Bild direkt in einem QR-Code speichern?",
         "Nein. Ein QR-Code fasst nur wenige Kilobyte Text. Du teilst das Bild online und speicherst den Link im Code."),
        ("Wie erstelle ich einen QR-Code für ein Foto?",
         "Lade das Foto hoch, zum Beispiel bei Google Fotos, erstelle einen Freigabe-Link und mach daraus oben einen QR-Code."),
        ("Kann ich ein Foto als Hintergrund im QR-Code verwenden?",
         "Ja, mit der Option Bild-QR unter Logo im Generator. Download als PNG oder JPG."),
        ("Ist das kostenlos?",
         "Ja, ohne Anmeldung und ohne Ablaufdatum. Der Speicherdienst für dein Bild hat eigene Bedingungen."),
    ],
    "related": [("qr-code-mit-logo.html", "QR-Code mit Logo"), ("pdf-in-qr-code.html", "PDF in QR-Code umwandeln"), ("link-in-qr-code-umwandeln.html", "Link in QR-Code umwandeln")],
}

DE_PAGES_3 = [DAUERHAFT, LINK, WIE, CANVA, BEISPIELE, BILD]
