"""Expanded WiFi and vCard pages (English, shared on .com/.co.uk/.in). These replace the original short hand-written pages."""

WIFI = {
    "slug": "wifi-qr-code-generator.html",
    "crumb": "WiFi QR Code Generator",
    "type": "wifi",
    "tool_name": "WiFi QR Code Generator",
    "field_label": "",
    "field_placeholder": "",
    "cta": "CONNECT TO WIFI",
    "empty": "Enter your network name to generate the QR code.",
    "title": "Free WiFi QR Code Generator | Share Your WiFi Without the Password — SmartQRCraft",
    "description": "Create a free WiFi QR code so guests can join your network without typing a password. Works on iPhone and Android. Download PNG or SVG. No signup.",
    "og_title": "Free WiFi QR Code Generator | SmartQRCraft",
    "og_description": "Generate a WiFi QR code guests can scan to connect instantly. No typing, no signup, free PNG and SVG.",
    "h1": 'Free <span class="accent">WiFi QR Code</span> Generator',
    "lead": "Enter your network name and password, download the code, and guests can join your WiFi with one scan, with no spelling out a long password.",
    "faq_h2": "WiFi QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to create a WiFi QR code",
         "p": ["You need the exact network name and password of the WiFi you want to share."],
         "steps": [
             "Type the <strong>network name (SSID)</strong> exactly as it appears on a phone, including capital letters, spaces and symbols.",
             "Enter the <strong>password</strong>.",
             "Choose the <strong>security type</strong>. Most routers use WPA/WPA2/WPA3, so keep the default unless you know otherwise. If your network has no password, choose No password.",
             "If your network name is hidden, set <strong>Hidden network</strong> to Yes.",
             "Pick a style, download the PNG or SVG, and print it or show it on a screen.",
             "Scan the code with another phone to confirm it joins the network."]},
        {"kind": "prose", "id": "how-guests-connect", "h2": "How guests connect",
         "p": [
             "Guests open the normal camera app and point it at the code. A prompt appears with the network name and an option to join, and one tap connects them. No extra app is needed. This works on current iPhones and on Android phones from Android 10, and many older Android phones can do it through Google Lens or a scanner app.",
             "You can check how the code behaves first with the <a href=\"qr-code-scanner.html\">QR code scanner</a>, which shows the network name and security type stored in the code."]},
        {"kind": "table", "h2": "Which security type should I choose?",
         "p": ["The code has to match the way your router is set up."],
         "cols": ["Setting", "When to use it", "Notes"],
         "rows": [
             ["WPA/WPA2/WPA3", "Almost every modern router", "The right choice for most networks. This is the default."],
             ["WEP", "Very old routers only", "Outdated and easy to break. If you still use WEP, consider upgrading your router."],
             ["No password", "Open networks", "Anyone nearby can join. Not recommended for private use."]]},
        {"kind": "cards", "eyebrow": "Where to Use It", "h2": "Where a WiFi QR code helps",
         "cards": [
             ("Cafes, restaurants and bars", "On a table card or the menu, so staff do not repeat the password all day."),
             ("Airbnb, hotels and guest houses", "In a frame at the entrance or on the welcome card. See <a href=\"qr-codes-for-hotels-and-airbnb.html\">QR codes for hotels and Airbnb</a>."),
             ("Offices and waiting rooms", "For visitors and clients at reception."),
             ("Homes", "For guests, so you do not dictate a long password."),
             ("Events and coworking spaces", "On signs and badges."),
             ("Shops and salons", "For customers who wait.")]},
        {"kind": "prose", "id": "find-existing", "h2": "Find a WiFi QR code you already have",
         "p": ["Some devices can already show a code for the network you are on."],
         "bullets": [
             "<strong>Android:</strong> on Android 10 and newer, open the WiFi settings, tap the connected network and look for a QR code or Share option. Menu names differ by manufacturer.",
             "<strong>iPhone:</strong> iOS does not show a QR code for the network. You can share the password with a nearby Apple device from the password prompt, or create a code here.",
             "<strong>Router:</strong> some routers, including many consumer models, show a WiFi QR code in the admin page, often in the guest network settings."]},
        {"kind": "prose", "id": "security", "h2": "Security: what to know before you print",
         "p": ["A WiFi QR code does not hide the password. It holds it in a form a phone can read, and anyone who scans the code can join."],
         "bullets": [
             "<strong>Use a guest network</strong> if your router has one, so visitors never touch the network your own devices use.",
             "<strong>Place the code where guests are,</strong> not on a public window facing the street.",
             "<strong>Change the password</strong> if the printed code gets shared too widely. Then make a new code.",
             "<strong>Use WPA2 or WPA3</strong> for the network itself, and a strong password.",
             "<strong>Nothing is uploaded here.</strong> The code is created in your browser and your password is not sent to a server."]},
        {"kind": "prose", "id": "printing", "h2": "Printing and placing the code",
         "p": ["A little care makes the code scan every time."],
         "bullets": [
             "Print at least 3 cm (1.2 in) wide for a table card, larger on a wall. See the <a href=\"qr-code-size-guide.html\">QR code size guide</a>.",
             "Keep a clear white margin around the code and dark-on-light colors.",
             "Add a short label such as &quot;Scan to join WiFi&quot;, and the network name in text as a backup.",
             "Laminate codes in kitchens or bars where they get wet or dirty.",
             "Test the printed card with an iPhone and an Android phone before you use it."]},
        {"kind": "prose", "id": "troubleshooting", "h2": "If the code does not connect",
         "p": ["Almost every problem is one of these."],
         "bullets": [
             "<strong>The network name or password is wrong.</strong> Both are case sensitive. Compare them with what the router shows.",
             "<strong>The wrong security type</strong> is selected. Try WPA/WPA2/WPA3.",
             "<strong>The network is hidden</strong> but Hidden network is set to No.",
             "<strong>The password contains special characters.</strong> The tool encodes them, but retype the password carefully and test it.",
             "<strong>The phone is too old</strong> to read WiFi codes with its camera. Try a scanner app.",
             "<strong>You changed the password</strong> after making the code. Make a new one."],
         "after": ["Use the <a href=\"qr-code-tester.html\">QR code tester</a> to check that a printed code decodes and stays readable when small."]},
    ],
    "faq": [
        ("How do I create a WiFi QR code?", "Enter your network name (SSID), password and security type in the generator above, then download the QR code. Anyone who scans it can join the network."),
        ("Does scanning reveal my password as text?", "The code stores the password in a form a phone reads directly and joins the network. Scanner tools that show the raw content can display it. Treat the code as if it contained the password."),
        ("Will it work on both iPhone and Android?", "Yes. It uses the standard WIFI: QR format that current iPhones and Android phones read in the camera app."),
        ("What if my WiFi has no password?", "Select No password as the security type. The code will let people join the open network."),
        ("How do I make a WiFi QR code for a hidden network?", "Set Hidden network to Yes and enter the exact network name. Hidden networks need the name to be typed exactly."),
        ("Do I need to make a new code when I change the password?", "Yes. The password is stored inside the code, so a new password needs a new code."),
        ("Is the WiFi QR code generator free and private?", "Yes. It is free, needs no signup and adds no watermark. The code is created in your browser and nothing is uploaded."),
    ],
    "related": [
        ("qr-codes-for-hotels-and-airbnb.html", "QR codes for hotels and Airbnb"),
        ("qr-codes-for-restaurants.html", "QR codes for restaurants"),
        ("qr-code-scanner.html", "QR code scanner"),
    ],
}

VCARD = {
    "slug": "vcard-qr-code-generator.html",
    "crumb": "vCard QR Code Generator",
    "type": "vcard",
    "tool_name": "vCard QR Code Generator",
    "field_label": "",
    "field_placeholder": "",
    "cta": "SAVE MY CONTACT",
    "empty": "Enter at least a first name to generate the QR code.",
    "title": "Free vCard QR Code Generator | QR Code for Your Business Card — SmartQRCraft",
    "description": "Create a free vCard QR code for your business card. One scan saves your name, phone, email and company to a phone. Size and design tips. PNG or SVG, no signup.",
    "og_title": "Free vCard QR Code Generator | SmartQRCraft",
    "og_description": "Make a business card QR code that saves your contact details in one scan. Free, no signup, PNG or SVG.",
    "h1": 'Free <span class="accent">vCard QR Code</span> Generator',
    "lead": "Enter your contact details and download a QR code for your business card. One scan lets someone save your name, number and email straight to their contacts.",
    "faq_h2": "vCard and Business Card QR Code Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to make a QR code for a business card",
         "p": ["A vCard is the standard file format for contact information, and a vCard QR code is that file stored inside the pattern."],
         "steps": [
             "Enter your <strong>first and last name</strong>. Add your company, job title, phone, email and website if you want them saved.",
             "Check every field. A typo ends up in other people's contacts.",
             "Choose colors and a style. A dark code on a light background scans best.",
             "Download the <strong>SVG</strong> for print or a high-resolution <strong>PNG</strong>.",
             "Place it on your card, then scan the printed card with two phones to test."]},
        {"kind": "table", "h2": "vCard code or link on a business card?",
         "p": ["You can put either on a card. They suit different goals."],
         "cols": ["", "vCard (contact details)", "Link (website or profile)"],
         "rows": [
             ["What happens on scan", "The phone offers to save you as a contact", "A page opens in the browser"],
             ["Best for", "Being found and called: sales, trades, consultants, agents", "Showing work: portfolios, creators, online presence"],
             ["Works without internet", "Yes, the data is in the code", "No"],
             ["Can you change it later", "No, it is static", "Only by changing the page it points to"],
             ["Density", "Denser, needs a larger print size", "Simpler, easier to scan small"]],
         },
        {"kind": "prose", "id": "what-to-include", "h2": "What to put in the vCard",
         "p": ["More fields make a denser code, and a denser code needs more room on a small card."],
         "bullets": [
             "<strong>Always:</strong> name and one way to reach you, usually a mobile number or an email.",
             "<strong>Usually:</strong> company and job title, so people remember who you are.",
             "<strong>Optional:</strong> website. A short address keeps the code simple.",
             "<strong>Think twice about:</strong> home address and private numbers. A vCard shows everything in plain form to anyone who scans it."]},
        {"kind": "prose", "id": "size-placement", "h2": "Size and placement on the card",
         "p": ["The most common mistake is a code too small for its content."],
         "bullets": [
             "<strong>Size:</strong> at least 2 cm (0.8 in) square, and about 2.5 cm (1 in) is a safer choice. A vCard with many fields may need more. Read the <a href=\"qr-code-size-guide.html\">QR code size guide</a>.",
             "<strong>Position:</strong> the back of the card is popular because it leaves a clean area for the margin and a call to action.",
             "<strong>Quiet zone:</strong> keep a blank margin of at least four modules around the code.",
             "<strong>Contrast:</strong> dark code on a light background, and avoid glossy varnish on the code area.",
             "<strong>Call to action:</strong> a short line like &quot;Scan to save my contact&quot; makes people use it."]},
        {"kind": "cards", "eyebrow": "Who Uses It", "h2": "Who benefits from a vCard QR code",
         "cards": [
             ("Sales and account managers", "Give prospects your details at meetings and trade shows."),
             ("Real estate agents", "Put it on signs and cards. See <a href=\"qr-codes-for-real-estate.html\">QR codes for real estate</a>."),
             ("Tradespeople and freelancers", "Let customers save your number instead of losing the card."),
             ("Consultants and coaches", "Pair it with your <a href=\"linkedin-qr-code-generator.html\">LinkedIn QR code</a> or website."),
             ("Event organisers and speakers", "On badges and slides."),
             ("Job seekers", "Add one to your CV. See the <a href=\"resume-qr-code-generator.html\">resume QR code</a>.")]},
        {"kind": "prose", "id": "compatibility", "h2": "How it behaves on different phones",
         "p": [
             "Current iPhones and Android phones read a vCard code with the camera and offer to save the contact, though the wording and steps differ. This tool writes vCard version 3.0, which is widely supported. Some phones and apps show fewer fields than others, so test on the phones your contacts are likely to use."]},
        {"kind": "prose", "id": "privacy", "h2": "Privacy",
         "p": ["A vCard QR code contains your details in readable form. Only include what you are happy for anyone who gets your card to have. The code is created in your browser, and what you type is not sent to our servers."]},
    ],
    "faq": [
        ("How do I create a vCard QR code?", "Enter your name and contact details in the generator above, choose a design and download the QR code. Scanning it offers to save your contact."),
        ("How big should a QR code on a business card be?", "At least 2 cm (0.8 in), and about 2.5 cm (1 in) is safer, with a clear margin. A code with many fields may need to be larger."),
        ("Should I use a vCard or a link on my business card?", "A vCard saves your details directly and works offline. A link opens a page that you can keep up to date. Choose the vCard when you want to be saved and called, the link when you want to show your work."),
        ("Can I change the details after printing the cards?", "No. Static vCard codes cannot be edited. If your number or email changes, make a new code."),
        ("Does the vCard code work on iPhone and Android?", "Yes. The camera app on current phones recognises it and offers to save the contact."),
        ("Can I add a photo or logo to the contact?", "The code stores text fields only. You can put a logo in the middle of the QR code image itself, but the saved contact will not include a photo."),
        ("Is it free?", "Yes. It is free, with no signup and no watermark, and everything is created in your browser."),
    ],
    "related": [
        ("linkedin-qr-code-generator.html", "LinkedIn QR code generator"),
        ("resume-qr-code-generator.html", "Resume QR code generator"),
        ("qr-code-size-guide.html", "QR code size guide"),
    ],
}

CORE = [WIFI, VCARD]
