"""Tool pages, round 3: printable QR code templates and the embeddable QR code widget.
Shared English pages (.com, .co.uk, .in)."""

PRINTABLE = {
    "slug": "printable-qr-code-templates.html",
    "crumb": "Printable QR Code Templates",
    "widget": "print",
    "template": "tent",
    "type": "url",
    "tool_name": "Printable QR Code Templates",
    "field_label": "", "field_placeholder": "", "cta": "", "empty": "",
    "title": "Free Printable QR Code Templates | Table Tent, WiFi Card, Labels — SmartQRCraft",
    "description": "Free printable QR code templates: table tents, Scan & Pay counter signs, WiFi cards and A4 label sheets. Add your text and colors, then print or save as PDF.",
    "og_title": "Free Printable QR Code Templates | SmartQRCraft",
    "og_description": "Table tents, counter signs, WiFi cards and label sheets with your QR code. Print or save as PDF.",
    "h1": 'Free <span class="accent">Printable QR Code</span> Templates',
    "lead": "Pick a layout, add your link, WiFi or payment details and your own text, and print it on A4 paper. No design software needed.",
    "faq_h2": "Printable Template Questions",
    "sections": [
        {"kind": "table", "h2": "Which template to use",
         "cols": ["Template", "What you get", "Good for"],
         "rows": [
             ["Table tent", "An A4 page you fold in half so it stands on a table, with the code on both sides", "Restaurant menus, feedback, WiFi on cafe tables"],
             ["Counter sign", "A full A4 sign with a large heading and a big code", "Scan &amp; Pay at the till, reception desks, shop windows"],
             ["Cards (4 per A4)", "Four A6 cards with cut marks", "Handouts, room cards, product shelves"],
             ["WiFi cards", "Four cards with the network name, optional password and a WiFi QR code", "Hotels, Airbnb, offices, guest rooms"],
             ["Label sheet", "The same code repeated in a grid, with an optional caption", "Sticker labels, packaging, inventory tags"],
         ]},
        {"kind": "prose", "id": "how-to", "h2": "How to print your QR code template",
         "steps": [
             "Choose a template and fill in what the QR code should do.",
             "Type your heading, business name and small print, and pick an accent color.",
             "Click <strong>Print / Save as PDF</strong>. In the print dialog, choose <strong>Actual size</strong> or 100% scale.",
             "To get a PDF, choose <strong>Save as PDF</strong> as the printer. Send that PDF to a print shop for card stock or lamination.",
             "Scan one printed copy with a phone before you print the rest.",
         ]},
        {"kind": "prose", "id": "table-tent", "h2": "Folding a table tent",
         "p": ["Print on thick paper (160 g/m² or more) if your printer accepts it. Fold along the dashed line so both halves face out. The top half is printed upside down on purpose, so it reads the right way up after folding. Tape the bottom edges together or slide it into a clear acrylic stand."]},
        {"kind": "prose", "id": "labels", "h2": "Printing on label sheets",
         "p": ["Label sheets differ between brands, even when they have the same number of labels. Print one page on plain paper first and hold it against your label sheet in front of a light. If it lines up, print on the labels. If not, choose a different layout or adjust your printer's margins."],
         "bullets": [
             "<strong>24 per sheet (70 × 37 mm)</strong> and <strong>65 per sheet (38 × 21 mm)</strong> match common A4 address and mini label sizes.",
             "Tiny labels only work with short content, such as a short link.",
             "Use waterproof or vinyl labels for outdoors and anything that gets wet.",
         ]},
        {"kind": "cards", "eyebrow": "Tips", "h2": "Tips for printed QR codes",
         "cards": [
             ("Keep the code dark", "A dark code on white scans best. Use your brand color for the heading and border instead."),
             ("Say what happens", "&quot;Scan to see the menu&quot; gets more scans than a bare code."),
             ("Protect it", "Laminate signs and table tents that will be handled or wiped."),
             ("WiFi passwords", "Untick &quot;Print the password&quot; if you do not want it visible on the card; the code still contains it."),
             ("Check for tampering", "In public places, check now and then that nobody has stuck another code over yours."),
             ("Size", "See the <a href=\"qr-code-size-guide.html\">size guide</a> for how big a code needs to be."),
         ]},
    ],
    "faq": [
        ("Are these QR code templates free?",
         "Yes. They are free, with no signup and no watermark. You can print as many as you like."),
        ("How do I save the template as a PDF?",
         "Click Print / Save as PDF and choose Save as PDF (or Microsoft Print to PDF) as the printer."),
        ("Why is the printed page smaller than A4?",
         "Your print dialog is probably set to Fit to page. Choose Actual size or 100% scale."),
        ("Can I print on Letter paper?",
         "The layouts are A4. On US Letter, choose Fit to page; everything scales down slightly and stays scannable, but label sheets will not line up."),
        ("Can I change the design further?",
         "Download the SVG and open it in Canva, Figma, Illustrator or Inkscape to edit anything."),
        ("Is the WiFi password stored anywhere?",
         "No. The page is created in your browser and nothing is uploaded."),
    ],
    "related": [
        ("qr-codes-in-print.html", "Printing QR codes: complete guide"),
        ("wifi-qr-code-generator.html", "WiFi QR code generator"),
        ("bulk-qr-code-generator.html", "Bulk QR code generator (different code on each label)"),
    ],
}

WIDGET = {
    "slug": "qr-code-widget.html",
    "crumb": "QR Code Widget for Websites",
    "widget": "embed",
    "type": "url",
    "tool_name": "QR Code Widget",
    "field_label": "", "field_placeholder": "", "cta": "", "empty": "",
    "title": "Free QR Code Widget for Your Website | Embed Code, No API Key — SmartQRCraft",
    "description": "Add a free QR code widget to any website with two lines of HTML. It shows a QR code of the current page so desktop visitors can open it on their phone. No API key.",
    "og_title": "Free QR Code Widget for Websites | SmartQRCraft",
    "og_description": "Two lines of HTML add a QR code of the current page to your site. Free, no API key, no tracking.",
    "h1": 'Free <span class="accent">QR Code Widget</span> for Your Website',
    "lead": "Paste two lines of HTML and your page shows a QR code of itself. Desktop visitors scan it to continue on their phone. It works on any site, including WordPress, Shopify, Wix and plain HTML.",
    "faq_h2": "QR Code Widget Questions",
    "sections": [
        {"kind": "prose", "id": "how-to", "h2": "How to add the QR code widget",
         "steps": [
             "Choose the options above: automatic (the current page) or a fixed link, size, color and caption.",
             "Click <strong>Copy code</strong>.",
             "Paste the code into your page where the QR code should appear, for example a sidebar, footer or product page.",
             "Open the page and scan the code with your phone to check it.",
         ]},
        {"kind": "table", "h2": "Where to paste it",
         "cols": ["Platform", "Where the code goes"],
         "rows": [
             ["WordPress", "A <strong>Custom HTML</strong> block in the editor, or a Custom HTML widget in the sidebar or footer"],
             ["Shopify", "Online Store &gt; Themes &gt; Customize, then a <strong>Custom Liquid</strong> section or block"],
             ["Wix", "Add &gt; Embed Code &gt; <strong>Embed HTML</strong>"],
             ["Squarespace", "A <strong>Code</strong> block"],
             ["Blogger", "Layout &gt; Add a Gadget &gt; <strong>HTML/JavaScript</strong>"],
             ["Plain HTML", "Anywhere inside &lt;body&gt;"],
         ]},
        {"kind": "table", "h2": "Options",
         "p": ["The builder writes these for you, but you can also edit the attributes by hand."],
         "cols": ["Attribute", "What it does", "Default"],
         "rows": [
             ["<code>data-smartqr</code>", "Content of the code. Leave it empty to use the current page address", "Current page"],
             ["<code>data-size</code>", "Width and height in pixels (80 to 600)", "160"],
             ["<code>data-color</code>", "Code color as a hex value; keep it dark", "#111827"],
             ["<code>data-bg</code>", "Background color", "#ffffff"],
             ["<code>data-caption</code>", "Text under the code; empty hides it", "Scan to open on your phone"],
             ["<code>data-credit=\"off\"</code>", "Hides the small SmartQRCraft link", "Shown"],
         ]},
        {"kind": "cards", "eyebrow": "Ideas", "h2": "Where a QR code widget helps",
         "cards": [
             ("Recipes &amp; guides", "Readers scan the page to follow along in the kitchen or workshop."),
             ("Product pages", "Shoppers browsing on a laptop finish on their phone."),
             ("Events &amp; tickets", "Put the event page on a phone before leaving home."),
             ("App download pages", "Desktop visitors scan to install on mobile."),
             ("Printable pages", "Printed copies carry a code back to the live page."),
             ("Signage screens", "Screens in shops or offices show a code people can scan."),
         ]},
        {"kind": "prose", "id": "privacy", "h2": "Privacy and performance",
         "p": ["The widget is one small script with no cookies, no tracking and no calls to other services. The QR code is drawn in the visitor's browser, so page addresses are never sent to us or anyone else. The script loads with <code>async</code>, so it does not slow down the rest of your page."]},
    ],
    "faq": [
        ("Is the QR code widget free?",
         "Yes. It is free for personal and commercial sites, with no API key and no signup."),
        ("Does the widget track my visitors?",
         "No. It sets no cookies and sends no data. The code is generated in the visitor's browser."),
        ("Can one snippet show a different code on every page?",
         "Yes. In automatic mode each page shows a QR code of its own address, so you can put the snippet in a shared footer or template."),
        ("Can I remove the SmartQRCraft link?",
         "Yes, set data-credit=\"off\". We appreciate it if you keep it, because it helps others find the tool."),
        ("Does it work with WordPress and Shopify?",
         "Yes. Paste it into any block or section that accepts custom HTML."),
        ("Can I use more than one widget on a page?",
         "Yes. Add several div elements with data-smartqr; include the script tag once."),
    ],
    "related": [
        ("index.html#generator", "Free QR code generator (downloadable images)"),
        ("bulk-qr-code-generator.html", "Bulk QR code generator"),
        ("qr-code-scanner.html", "QR code scanner"),
    ],
}

TOOLS3_SHARED = [PRINTABLE, WIDGET]
